# These are supported funding model platforms

github:
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:
custom:
  - https://boosty.to/yusif_musayev/single-payment/donation/817954/target?share=target_link
  - https://github.com/elnureisayeva1-cloud
  - https://github.com/Siradankullanici
  
