; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "HydraDragonAntivirus"
#define MyAppVersion "0.1"
#define MyAppPublisher "Emirhan Ucan"
#define MyAppURL "https://github.com/HydraDragonAntivirus/HydraDragonAntivirus"
#define MyAppExeName "antivirus.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9B4A19B2-69BC-4AD2-8781-BDD85DCEF0C9}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=yes
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=C:\Users\victim\Documents\HydraDragonAntivirus\LICENSE.md
InfoBeforeFile=C:\Users\victim\Documents\HydraDragonAntivirus\README.md
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\victim\Documents\output
OutputBaseFilename=HydraDragonAntivirus
SetupIconFile=C:\Users\victim\Documents\oldstuff\HydraDragonAV.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\victim\Documents\HydraDragonAntivirus\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\victim\Documents\HydraDragonAntivirus\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\victim\Documents\hydradownload\clamav-1.3.1.win.x64.msi"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\victim\Documents\hydradownload\npcap-1.79.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\victim\Documents\hydradownload\Sandboxie-Classic-x64-v5.68.7.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\victim\Documents\hydradownload\Snort_2_9_20_Installer.x64.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\victim\Documents\hydradownload\setup.bat"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "{app}\clamav-1.3.1.win.x64.msi"; Flags: shellexec waituntilterminated
Filename: "{app}\npcap-1.79.exe"; Flags: shellexec waituntilterminated
Filename: "{app}\Sandboxie-Classic-x64-v5.68.7.exe"; Flags: shellexec waituntilterminated
Filename: "{app}\Snort_2_9_20_Installer.x64.exe"; Flags: shellexec waituntilterminated
Filename: "{app}\setup.bat"; Flags: shellexec waituntilterminated