; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "HydraDragonAntivirus"
#define MyAppVersion "0.1.0"
#define MyVersionInfoVersion "0.1.0.0"
#define MyAppPublisher "Emirhan Ucan"
#define MyAppURL "https://github.com/HydraDragonAntivirus/HydraDragonAntivirus"
#define MyAppExeName "hydradragon\\HydraDragonService\\HydraDragonService.exe"
#define MyAppExeFile "HydraDragonService.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

; Owlyshield definitions
#define OwlyshieldVersion "1.2.0"
#define AgentName "Owlyshield Service"
#define FSfilter "OwlyshieldRansomFilter"
#define OwlyshieldAppId "8C19967B-1D27-4E6A-85CD-5059912C2788"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9B4A19B2-69BC-4AD2-8781-BDD85DCEF0C9}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
VersionInfoVersion={#MyVersionInfoVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf64}\{#MyAppName}
DisableDirPage=yes
ChangesAssociations=yes
DisableProgramGroupPage=yes
DisableReadyPage=yes
DisableReadyMemo=yes
LicenseFile=C:\Users\semae\OneDrive\Belgeler\HydraDragonAntivirus\LICENSE
InfoBeforeFile=C:\Users\semae\OneDrive\Belgeler\HydraDragonAntivirus\README.md
OutputDir=C:\output
OutputBaseFilename=HydraDragonAntivirus
SetupIconFile=C:\Users\semae\OneDrive\Belgeler\HydraDragonAntivirus\hydradragon\assets\HydraDragonAV.ico
UninstallDisplayIcon={app}\hydradragon\assets\HydraDragonAV.ico
Compression=lzma2/ultra64
SolidCompression=yes
LZMAUseSeparateProcess=yes
WizardStyle=modern
DiskSpanning=no
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
PrivilegesRequired=admin
RestartIfNeededByRun=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; HydraDragon main files
Source: "C:\Users\semae\OneDrive\Belgeler\HydraDragonAntivirus\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs;

; External dependencies
Source: "C:\Users\semae\OneDrive\Belgeler\hydratempinstall\7z2601-x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "C:\Users\semae\OneDrive\Belgeler\hydratempinstall\VC_redist.x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "C:\Users\semae\OneDrive\Belgeler\hydratempinstall\clamav-1.5.2.win.x64.msi"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "C:\Users\semae\OneDrive\Belgeler\hydratempinstall\npcap-1.88.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "C:\Users\semae\OneDrive\Belgeler\hydratempinstall\Suricata-7.0.14-1-64bit.msi"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "C:\Users\semae\OneDrive\Belgeler\hydratempinstall\jre-8u491-windows-x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "C:\Users\semae\OneDrive\Belgeler\hydratempinstall\jdk-25_windows-x64_bin.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "C:\Users\semae\OneDrive\Belgeler\hydratempinstall\windowsdesktop-runtime-8.0.25-win-x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "C:\Users\semae\OneDrive\Belgeler\hydratempinstall\windowsdesktop-runtime-9.0.14-win-x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
; Node.js 22.22.2 (x64) MSI
Source: "C:\Users\semae\OneDrive\Belgeler\hydratempinstall\node-v22.22.2-x64.msi"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "C:\Users\semae\OneDrive\Belgeler\hydratempinstall\python-3.12.10-amd64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "C:\Users\semae\OneDrive\Belgeler\hydratempinstall\setup.py"; DestDir: "{tmp}"; Flags: deleteafterinstall
; COMODO OpenEDR
Source: "C:\Users\semae\OneDrive\Belgeler\hydratempinstall\openedr.msi"; DestDir: "{tmp}"; Flags: deleteafterinstall

[Dirs]
Name: "{app}\hydradragon\Owlyshield\debug"
Name: "{app}\hydradragon\Owlyshield\utils"
Name: "{app}\hydradragon\Owlyshield\log"; Flags: uninsneveruninstall
Name: "{app}\hydradragon\Owlyshield\config"; Flags: uninsneveruninstall
Name: "{app}\hydradragon\Owlyshield\config\threats"; Flags: uninsneveruninstall
Name: "{pf64}\ClamAV"
Name: "{app}\hydradragon\suricata"
Name: "{app}\nodejs"
Name: "{app}\python"

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeFile}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

; Owlyshield Registry Settings
Root: HKLM64; Subkey: "Software\Owlyshield"; ValueType: string; ValueName: "NUM_VERSION"; ValueData: {#OwlyshieldVersion}; Flags: uninsdeletekey
Root: HKLM64; Subkey: "Software\Owlyshield"; ValueType: string; ValueName: "PROCESS_ACTIVITY_PATH"; ValueData: "{app}\hydradragon\Owlyshield\debug"; Flags: uninsdeletekey
Root: HKLM64; Subkey: "Software\Owlyshield"; ValueType: string; ValueName: "UTILS_PATH"; ValueData: "{app}\hydradragon\Owlyshield\utils"; Flags: uninsdeletekey
Root: HKLM64; Subkey: "Software\Owlyshield"; ValueType: string; ValueName: "CONFIG_PATH"; ValueData: "{app}\hydradragon\Owlyshield\config"; Flags: uninsdeletekey
Root: HKLM64; Subkey: "Software\Owlyshield"; ValueType: string; ValueName: "NOVELTY_PATH"; ValueData: "{app}\hydradragon\Owlyshield\novelty"; Flags: uninsdeletekey
Root: HKLM64; Subkey: "Software\Owlyshield"; ValueType: string; ValueName: "LOG_PATH"; ValueData: "{app}\hydradragon\Owlyshield\Owlyshield Service\log"; Flags: uninsdeletekey
Root: HKLM64; Subkey: "Software\Owlyshield"; ValueType: string; ValueName: "RULES_PATH"; ValueData: "{app}\hydradragon\Owlyshield\rules"; Flags: uninsdeletekey
Root: HKLM64; Subkey: "Software\Owlyshield"; ValueType: string; ValueName: "REPORTS_PATH"; ValueData: "{app}\hydradragon\Owlyshield\config\report"; Flags: uninsdeletekey
Root: HKLM64; Subkey: "Software\Owlyshield"; ValueType: string; ValueName: "REALTIME_LEARNING_DIR"; ValueData: "{app}\hydradragon\Owlyshield\realtime_learning"; Flags: uninsdeletekey

Root: HKLM64; Subkey: "Software\Owlyshield"; ValueType: string; ValueName: "APP_ID"; ValueData: "{#OwlyshieldAppId}"; Flags: uninsdeletekey
Root: HKLM64; Subkey: "Software\Owlyshield"; ValueType: string; ValueName: "LANGUAGE"; ValueData: "en-US"; Flags: uninsdeletekey
Root: HKLM64; Subkey: "Software\Owlyshield"; ValueType: string; ValueName: "KILL_POLICY"; ValueData: "KILL_AND_QUARANTINE"; Flags: uninsdeletekey
Root: HKLM64; Subkey: "Software\Owlyshield"; ValueType: string; ValueName: "TELEMETRY"; ValueData: "0"; Flags: uninsdeletekey
Root: HKLM64; Subkey: "Software\Owlyshield"; ValueType: string; ValueName: "VERBOSE_LOGGING"; ValueData: "0"; Flags: uninsdeletekey
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce"; ValueType: string; ValueName: "OwlyshieldPostInstall"; ValueData: """{app}\post_install.bat"""

Root: HKCU; Subkey: "Software\Classes\AppUserModelId\{#OwlyshieldAppId}"; ValueType: string; ValueName: "DisplayName"; ValueData: "HydraDragon Antivirus"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\AppUserModelId\{#OwlyshieldAppId}"; ValueType: string; ValueName: "IconUri"; ValueData: "{app}\hydradragon\assets\HydraDragonAV.ico"; Flags: uninsdeletekey

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\hydradragon\assets\HydraDragonAV.ico"; AppUserModelID: "{#OwlyshieldAppId}"; AppUserModelToastActivatorCLSID: "{#OwlyshieldAppId}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\hydradragon\assets\HydraDragonAV.ico"; AppUserModelID: "{#OwlyshieldAppId}"; AppUserModelToastActivatorCLSID: "{#OwlyshieldAppId}"

[Run]
; 7-Zip (silent)
Filename: "{tmp}\7z2601-x64.exe"; Parameters: "/S"; Flags: shellexec waituntilterminated

; .NET Runtime 9.0.14 (silent, no restart)
Filename: "{tmp}\windowsdesktop-runtime-9.0.14-win-x64.exe"; Parameters: "/install /quiet /norestart"; Flags: shellexec waituntilterminated

; .NET Desktop Runtime 8.0.25 (silent, no restart)
Filename: "{tmp}\windowsdesktop-runtime-8.0.25-win-x64.exe"; Parameters: "/install /quiet /norestart"; Flags: shellexec waituntilterminated

; Visual C++ Redistributable 2022 (silent, auto-install)
Filename: "{tmp}\VC_redist.x64.exe"; Parameters: "/install /quiet /norestart"; Flags: shellexec waituntilterminated

; JRE 8u491 (silent, updates enabled)
Filename: "{tmp}\jre-8u491-windows-x64.exe"; Parameters: "/s INSTALL_SILENT=Enable AUTO_UPDATE=Enable WEB_JAVA=Disable SPONSORS=Disable"; Flags: shellexec waituntilterminated

; JDK 25 (silent, environment variables)
Filename: "{tmp}\jdk-25_windows-x64_bin.exe"; Parameters: "/s"; Flags: shellexec waituntilterminated

; Python 3.12.10 amd64 (silent, all users, add to PATH, include pip, target directory)
Filename: "{tmp}\python-3.12.10-amd64.exe"; Parameters: "/quiet InstallAllUsers=1 PrependPath=1 Include_pip=1 TargetDir=""{app}\python"""; Flags: shellexec waituntilterminated

; ClamAV Installer (MSI - Silent Install)
Filename: "msiexec.exe"; Parameters: "/i ""{tmp}\clamav-1.5.2.win.x64.msi"" /quiet /norestart"; Flags: waituntilterminated

; Suricata Installer (MSI - Silent Install)
Filename: "msiexec.exe"; Parameters: "/i ""{tmp}\Suricata-7.0.14-1-64bit.msi"" /quiet /norestart INSTALLDIR=""{app}\hydradragon\suricata"""; Flags: waituntilterminated

; OpenEDR Installer (MSI - Silent Install)
Filename: "msiexec.exe"; Parameters: "/i ""{tmp}\openedr.msi"" /quiet /norestart"; Flags: waituntilterminated

; Node.js 22.22.2 (silent)
Filename: "msiexec.exe"; Parameters: "/i ""{tmp}\node-v22.22.2-x64.msi"" /quiet /norestart INSTALLDIR=""{app}\nodejs"""; Flags: waituntilterminated

; Npcap install - user-interactive GUI mode
Filename: "{tmp}\npcap-1.88.exe"; Parameters: "/winpcap_mode=yes"; Flags: shellexec waituntilterminated

; Custom setup script
Filename: "{app}\python\python.exe"; Parameters: """{tmp}\setup.py"""; Flags: waituntilterminated

[UninstallRun]
; Disable test signing mode on uninstall
Filename: "bcdedit.exe"; Parameters: "/set testsigning off"

; Owlyshield cleanup
; Filename: "sc.exe"; Parameters: "stop ""{#AgentName}"""
;  Filename: "sc.exe"; Parameters: "stop ""{#FSfilter}"""
; Filename: "sc.exe"; Parameters: "delete ""{#AgentName}"""
; Filename: "sc.exe"; Parameters: "delete ""{#FSfilter}"""
; Filename: "del.exe"; Parameters: """C:\Windows\System32\drivers\{#FSfilter}.sys"""
