/// Feature vector for PE file classification.
use std::collections::HashMap;

#[derive(Debug, Clone)]
pub struct PeFeatureVector {
    pub size_of_optional_header: f32,
    pub major_linker_version: f32,
    pub minor_linker_version: f32,
    pub size_of_code: f32,
    pub size_of_initialized_data: f32,
    pub size_of_uninitialized_data: f32,
    pub address_of_entry_point: f32,
    pub image_base: f32,
    pub subsystem: f32,
    pub dll_characteristics: f32,
    pub size_of_stack_reserve: f32,
    pub size_of_heap_reserve: f32,
    pub checksum: f32,
    pub number_of_rva_and_sizes: f32,
    pub size_of_image: f32,
    pub imports_count: f32,
    pub exports_count: f32,
    pub resources_count: f32,
    pub sections_count: f32,
    pub overlay_exists: f32,
    pub overlay_size: f32,
    pub sec_entropy_mean: f32,
    pub sec_entropy_min: f32,
    pub sec_entropy_max: f32,
    pub total_instructions: f32,
    pub total_add_instructions: f32,
    pub total_mov_instructions: f32,
    pub is_likely_packed: f32,
    pub add_mov_ratio: f32,
    pub instructions_per_kb: f32,
    pub num_tls_callbacks: f32,
    pub num_delay_imports: f32,
    pub num_reloc_entries: f32,
    pub num_reloc_blocks: f32,
    pub num_bound_imports: f32,
    pub num_debug_entries: f32,
    pub cert_size: f32,
    pub has_rich_header: f32,
}

impl PeFeatureVector {
    pub const LEN: usize = 38;

    pub fn to_array(&self) -> [f32; 38] {
        [
            self.size_of_optional_header,
            self.major_linker_version,
            self.minor_linker_version,
            self.size_of_code,
            self.size_of_initialized_data,
            self.size_of_uninitialized_data,
            self.address_of_entry_point,
            self.image_base,
            self.subsystem,
            self.dll_characteristics,
            self.size_of_stack_reserve,
            self.size_of_heap_reserve,
            self.checksum,
            self.number_of_rva_and_sizes,
            self.size_of_image,
            self.imports_count,
            self.exports_count,
            self.resources_count,
            self.overlay_exists,
            self.sections_count,
            self.sec_entropy_mean,
            self.sec_entropy_min,
            self.sec_entropy_max,
            self.total_instructions,
            self.total_add_instructions,
            self.total_mov_instructions,
            self.is_likely_packed,
            self.add_mov_ratio,
            self.instructions_per_kb,
            self.overlay_size,
            self.num_tls_callbacks,
            self.num_delay_imports,
            self.num_reloc_entries,
            self.num_reloc_blocks,
            self.num_bound_imports,
            self.num_debug_entries,
            self.cert_size,
            self.has_rich_header,
        ]
    }

    /// Converts the feature vector to a name -> value map so downstream code
    /// (behavior engine state, reports) can expose the ML features by name.
    pub fn to_map(&self) -> HashMap<String, f32> {
        [
            ("size_of_optional_header", self.size_of_optional_header),
            ("major_linker_version", self.major_linker_version),
            ("minor_linker_version", self.minor_linker_version),
            ("size_of_code", self.size_of_code),
            ("size_of_initialized_data", self.size_of_initialized_data),
            (
                "size_of_uninitialized_data",
                self.size_of_uninitialized_data,
            ),
            ("address_of_entry_point", self.address_of_entry_point),
            ("image_base", self.image_base),
            ("subsystem", self.subsystem),
            ("dll_characteristics", self.dll_characteristics),
            ("size_of_stack_reserve", self.size_of_stack_reserve),
            ("size_of_heap_reserve", self.size_of_heap_reserve),
            ("checksum", self.checksum),
            ("number_of_rva_and_sizes", self.number_of_rva_and_sizes),
            ("size_of_image", self.size_of_image),
            ("imports_count", self.imports_count),
            ("exports_count", self.exports_count),
            ("resources_count", self.resources_count),
            ("sections_count", self.sections_count),
            ("overlay_exists", self.overlay_exists),
            ("overlay_size", self.overlay_size),
            ("sec_entropy_mean", self.sec_entropy_mean),
            ("sec_entropy_min", self.sec_entropy_min),
            ("sec_entropy_max", self.sec_entropy_max),
            ("total_instructions", self.total_instructions),
            ("total_add_instructions", self.total_add_instructions),
            ("total_mov_instructions", self.total_mov_instructions),
            ("is_likely_packed", self.is_likely_packed),
            ("add_mov_ratio", self.add_mov_ratio),
            ("instructions_per_kb", self.instructions_per_kb),
            ("num_tls_callbacks", self.num_tls_callbacks),
            ("num_delay_imports", self.num_delay_imports),
            ("num_reloc_entries", self.num_reloc_entries),
            ("num_reloc_blocks", self.num_reloc_blocks),
            ("num_bound_imports", self.num_bound_imports),
            ("num_debug_entries", self.num_debug_entries),
            ("cert_size", self.cert_size),
            ("has_rich_header", self.has_rich_header),
        ]
        .into_iter()
        .map(|(k, v)| (k.to_string(), v))
        .collect()
    }
}

#[derive(Debug, Clone)]
pub struct JsFeatureVector {
    pub file_size: f32,
    pub entropy: f32,
    pub parse_success: f32,
    pub function_count: f32,
    pub variable_declarations: f32,
    pub call_expressions: f32,
    pub member_expressions: f32,
    pub binary_expressions: f32,
    pub conditional_statements: f32,
    pub loop_statements: f32,
    pub try_catch_blocks: f32,
    pub array_literals: f32,
    pub object_literals: f32,
    pub max_nesting_depth: f32,
    pub eval_usage: f32,
    pub suspicious_call_count: f32,
    pub hex_encoded_strings: f32,
    pub unicode_encoded_strings: f32,
    pub char_code_usage: f32,
    pub base64_usage: f32,
    pub escape_usage: f32,
    pub bracket_notation_calls: f32,
    pub obfuscation_score: f32,
    pub is_obfuscated: f32,
    pub crypto_references: f32,
    pub network_operations: f32,
    pub file_system_operations: f32,
    pub registry_operations: f32,
    pub process_operations: f32,
    pub suspicious_api_calls: f32,
    pub suspicious_score: f32,
    pub total_strings: f32,
    pub avg_string_length: f32,
    pub max_string_length: f32,
    pub long_strings_count: f32,
    pub base64_like_strings: f32,
    pub url_strings: f32,
    pub hex_strings: f32,
    pub total_lines: f32,
    pub code_lines: f32,
    pub comment_lines: f32,
    pub blank_lines: f32,
    pub avg_line_length: f32,
    pub max_line_length: f32,
    pub cyclomatic_complexity: f32,
    pub total_identifiers: f32,
    pub short_identifiers: f32,
    pub long_identifiers: f32,
    pub avg_identifier_length: f32,
    pub suspicious_naming: f32,
    pub random_like_identifiers: f32,
}

impl JsFeatureVector {
    pub const LEN: usize = 51;

    pub fn to_array(&self) -> [f32; 51] {
        [
            self.file_size,
            self.entropy,
            self.parse_success,
            self.function_count,
            self.variable_declarations,
            self.call_expressions,
            self.member_expressions,
            self.binary_expressions,
            self.conditional_statements,
            self.loop_statements,
            self.try_catch_blocks,
            self.array_literals,
            self.object_literals,
            self.max_nesting_depth,
            self.eval_usage,
            self.suspicious_call_count,
            self.hex_encoded_strings,
            self.unicode_encoded_strings,
            self.char_code_usage,
            self.base64_usage,
            self.escape_usage,
            self.bracket_notation_calls,
            self.obfuscation_score,
            self.is_obfuscated,
            self.crypto_references,
            self.network_operations,
            self.file_system_operations,
            self.registry_operations,
            self.process_operations,
            self.suspicious_api_calls,
            self.suspicious_score,
            self.total_strings,
            self.avg_string_length,
            self.max_string_length,
            self.long_strings_count,
            self.base64_like_strings,
            self.url_strings,
            self.hex_strings,
            self.total_lines,
            self.code_lines,
            self.comment_lines,
            self.blank_lines,
            self.avg_line_length,
            self.max_line_length,
            self.cyclomatic_complexity,
            self.total_identifiers,
            self.short_identifiers,
            self.long_identifiers,
            self.avg_identifier_length,
            self.suspicious_naming,
            self.random_like_identifiers,
        ]
    }

    /// Converts the feature vector to a name -> value map so downstream code
    /// (behavior engine state, reports) can expose the ML features by name.
    pub fn to_map(&self) -> HashMap<String, f32> {
        [
            ("file_size", self.file_size),
            ("entropy", self.entropy),
            ("parse_success", self.parse_success),
            ("function_count", self.function_count),
            ("variable_declarations", self.variable_declarations),
            ("call_expressions", self.call_expressions),
            ("member_expressions", self.member_expressions),
            ("binary_expressions", self.binary_expressions),
            ("conditional_statements", self.conditional_statements),
            ("loop_statements", self.loop_statements),
            ("try_catch_blocks", self.try_catch_blocks),
            ("array_literals", self.array_literals),
            ("object_literals", self.object_literals),
            ("max_nesting_depth", self.max_nesting_depth),
            ("eval_usage", self.eval_usage),
            ("suspicious_call_count", self.suspicious_call_count),
            ("hex_encoded_strings", self.hex_encoded_strings),
            ("unicode_encoded_strings", self.unicode_encoded_strings),
            ("char_code_usage", self.char_code_usage),
            ("base64_usage", self.base64_usage),
            ("escape_usage", self.escape_usage),
            ("bracket_notation_calls", self.bracket_notation_calls),
            ("obfuscation_score", self.obfuscation_score),
            ("is_obfuscated", self.is_obfuscated),
            ("crypto_references", self.crypto_references),
            ("network_operations", self.network_operations),
            ("file_system_operations", self.file_system_operations),
            ("registry_operations", self.registry_operations),
            ("process_operations", self.process_operations),
            ("suspicious_api_calls", self.suspicious_api_calls),
            ("suspicious_score", self.suspicious_score),
            ("total_strings", self.total_strings),
            ("avg_string_length", self.avg_string_length),
            ("max_string_length", self.max_string_length),
            ("long_strings_count", self.long_strings_count),
            ("base64_like_strings", self.base64_like_strings),
            ("url_strings", self.url_strings),
            ("hex_strings", self.hex_strings),
            ("total_lines", self.total_lines),
            ("code_lines", self.code_lines),
            ("comment_lines", self.comment_lines),
            ("blank_lines", self.blank_lines),
            ("avg_line_length", self.avg_line_length),
            ("max_line_length", self.max_line_length),
            ("cyclomatic_complexity", self.cyclomatic_complexity),
            ("total_identifiers", self.total_identifiers),
            ("short_identifiers", self.short_identifiers),
            ("long_identifiers", self.long_identifiers),
            ("avg_identifier_length", self.avg_identifier_length),
            ("suspicious_naming", self.suspicious_naming),
            ("random_like_identifiers", self.random_like_identifiers),
        ]
        .into_iter()
        .map(|(k, v)| (k.to_string(), v))
        .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pe_to_map_covers_all_features() {
        let f = PeFeatureVector {
            size_of_optional_header: 1.0,
            major_linker_version: 2.0,
            minor_linker_version: 3.0,
            size_of_code: 4.0,
            size_of_initialized_data: 5.0,
            size_of_uninitialized_data: 6.0,
            address_of_entry_point: 7.0,
            image_base: 8.0,
            subsystem: 9.0,
            dll_characteristics: 10.0,
            size_of_stack_reserve: 11.0,
            size_of_heap_reserve: 12.0,
            checksum: 13.0,
            number_of_rva_and_sizes: 14.0,
            size_of_image: 15.0,
            imports_count: 16.0,
            exports_count: 17.0,
            resources_count: 18.0,
            sections_count: 19.0,
            overlay_exists: 20.0,
            overlay_size: 21.0,
            sec_entropy_mean: 22.0,
            sec_entropy_min: 23.0,
            sec_entropy_max: 24.0,
            total_instructions: 25.0,
            total_add_instructions: 26.0,
            total_mov_instructions: 27.0,
            is_likely_packed: 28.0,
            add_mov_ratio: 29.0,
            instructions_per_kb: 30.0,
            num_tls_callbacks: 31.0,
            num_delay_imports: 32.0,
            num_reloc_entries: 33.0,
            num_reloc_blocks: 34.0,
            num_bound_imports: 35.0,
            num_debug_entries: 36.0,
            cert_size: 37.0,
            has_rich_header: 38.0,
        };
        let map = f.to_map();
        assert_eq!(map.len(), PeFeatureVector::LEN);
        assert_eq!(map["sec_entropy_mean"], 22.0);
        assert_eq!(map["is_likely_packed"], 28.0);
        assert_eq!(map["has_rich_header"], 38.0);
    }

    #[test]
    fn js_to_map_covers_all_features() {
        let f = JsFeatureVector {
            file_size: 1.0,
            entropy: 7.5,
            parse_success: 1.0,
            function_count: 2.0,
            variable_declarations: 3.0,
            call_expressions: 4.0,
            member_expressions: 5.0,
            binary_expressions: 6.0,
            conditional_statements: 7.0,
            loop_statements: 8.0,
            try_catch_blocks: 9.0,
            array_literals: 10.0,
            object_literals: 11.0,
            max_nesting_depth: 12.0,
            eval_usage: 13.0,
            suspicious_call_count: 14.0,
            hex_encoded_strings: 15.0,
            unicode_encoded_strings: 16.0,
            char_code_usage: 17.0,
            base64_usage: 18.0,
            escape_usage: 19.0,
            bracket_notation_calls: 20.0,
            obfuscation_score: 21.0,
            is_obfuscated: 0.0,
            crypto_references: 22.0,
            network_operations: 23.0,
            file_system_operations: 24.0,
            registry_operations: 25.0,
            process_operations: 26.0,
            suspicious_api_calls: 27.0,
            suspicious_score: 28.0,
            total_strings: 29.0,
            avg_string_length: 30.0,
            max_string_length: 31.0,
            long_strings_count: 32.0,
            base64_like_strings: 33.0,
            url_strings: 34.0,
            hex_strings: 35.0,
            total_lines: 36.0,
            code_lines: 37.0,
            comment_lines: 38.0,
            blank_lines: 39.0,
            avg_line_length: 40.0,
            max_line_length: 41.0,
            cyclomatic_complexity: 42.0,
            total_identifiers: 43.0,
            short_identifiers: 44.0,
            long_identifiers: 45.0,
            avg_identifier_length: 46.0,
            suspicious_naming: 47.0,
            random_like_identifiers: 48.0,
        };
        let map = f.to_map();
        assert_eq!(map.len(), JsFeatureVector::LEN);
        assert_eq!(map["entropy"], 7.5);
        assert_eq!(map["is_obfuscated"], 0.0);
        assert_eq!(map["suspicious_score"], 28.0);
    }
}
