/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AVEngineClient */

#ifndef _Included_AVEngineClient
#define _Included_AVEngineClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AVEngineClient
 * Method:    Init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_AVEngineClient_Init
  (JNIEnv *, jobject);

/*
 * Class:     AVEngineClient
 * Method:    Free
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_AVEngineClient_Free
  (JNIEnv *, jobject);

/*
 * Class:     AVEngineClient
 * Method:    SendRequest
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_AVEngineClient_SendRequest
  (JNIEnv *, jobject, jstring);

/*
 * Class:     AVEngineClient
 * Method:    GetNextAnswer
 * Signature: (LAVEngineRpcResponse;)I
 */
JNIEXPORT jint JNICALL Java_AVEngineClient_GetNextAnswer
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
