::
:: Boost build script
::   Usage:
::     - set path to vcvarsall.bat for your Visual Studio
::     - run this script
::     - wait and watch build_cmd.log
::     - after finish the lib subdirectory will contains *.lib and  *.pdb files
@echo off
setlocal EnableExtensions DisableDelayedExpansion

:: Execute from MSVC environment
set "vcvarsall="
set toolset_name=msvc-14.3

:: Define build path
set "BoostRootDir=%~dp0"
set "BoostRootDir=%BoostRootDir:~0,-1%"
set "BoostBuildTmpDir=%BoostRootDir%\tmp"

:: Declare b2 commandlines
set LibrariesRestrictions= --with-system --with-chrono --with-thread --with-locale --with-filesystem --with-date_time --with-regex
set BuildBoost="%BoostRootDir%\b2.exe" stage toolset=%toolset_name% link=static debug-symbols=on debug-store=database --build-dir="%BoostBuildTmpDir%" --stagedir="%BoostRootDir%" --hash -a -d0 %LibrariesRestrictions%
set BuildBoostMthreadRltshared=%BuildBoost% threading=multi runtime-link=shared
set BuildBoostMthreadRltstatic=%BuildBoost% threading=multi runtime-link=static

if /I not "%~1"=="--force" (
	call :HavePrebuiltBoostLibs
	if not errorlevel 1 (
		echo [INFO] Boost libraries already exist. Skipping rebuild. Use build.cmd --force to rebuild Boost.
		exit /b 0
	)
)

:: Call StartBuild directly so vcvarsall environment changes remain visible.
call :StartBuild
exit /b %errorlevel%

:: Build boost
:StartBuild

echo Start Build
echo LibrariesRestrictions: %LibrariesRestrictions%

call :FindVcVars
if errorlevel 1 exit /b %errorlevel%

echo ----------------------------------------------------------
echo build b2 tool
echo ----------------------------------------------------------

call "%vcvarsall%" x64
if errorlevel 1 exit /b %errorlevel%

where cl >nul 2>nul
if errorlevel 1 (
	echo ERROR: cl.exe is not available after initializing Visual Studio x64 environment.
	exit /b 1
)

call bootstrap.bat vc142
if errorlevel 1 exit /b %errorlevel%
@echo off

if not exist "%BoostRootDir%\b2.exe" (
	echo ERROR: b2.exe was not generated by bootstrap.bat
	exit /b 1
)

echo ----------------------------------------------------------
echo Build x86
echo ----------------------------------------------------------

setlocal
call "%vcvarsall%" x86
if errorlevel 1 exit /b %errorlevel%
where cl >nul 2>nul
if errorlevel 1 (
	echo ERROR: cl.exe is not available after initializing Visual Studio x86 environment.
	exit /b 1
)
%BuildBoostMthreadRltstatic% address-model=32 variant=debug
if errorlevel 1 exit /b %errorlevel%
%BuildBoostMthreadRltshared% address-model=32 variant=debug
if errorlevel 1 exit /b %errorlevel%
%BuildBoostMthreadRltstatic% address-model=32 variant=release
if errorlevel 1 exit /b %errorlevel%
%BuildBoostMthreadRltshared% address-model=32 variant=release
if errorlevel 1 exit /b %errorlevel%
endlocal

echo ----------------------------------------------------------
echo Build x64
echo ----------------------------------------------------------

setlocal
call "%vcvarsall%" x64
if errorlevel 1 exit /b %errorlevel%
where cl >nul 2>nul
if errorlevel 1 (
	echo ERROR: cl.exe is not available after initializing Visual Studio x64 environment.
	exit /b 1
)
%BuildBoostMthreadRltstatic% address-model=64 variant=debug
if errorlevel 1 exit /b %errorlevel%
%BuildBoostMthreadRltshared% address-model=64 variant=debug
if errorlevel 1 exit /b %errorlevel%
%BuildBoostMthreadRltstatic% address-model=64 variant=release
if errorlevel 1 exit /b %errorlevel%
%BuildBoostMthreadRltshared% address-model=64 variant=release
if errorlevel 1 exit /b %errorlevel%
endlocal

:CopyPdb

echo ----------------------------------------------------------
echo Copying PDB
echo ----------------------------------------------------------

set "PdbSrcDirectory=%BoostBuildTmpDir%\boost\bin.v2\libs"
for /r "%PdbSrcDirectory%" %%f in (*.pdb) do xcopy "%%f" "%BoostRootDir%\lib\" /y /exclude:%BoostRootDir%\excluded_pdb_list.txt

echo ----------------------------------------------------------
echo Creating vc142 compatibility aliases
echo ----------------------------------------------------------

for %%f in ("%BoostRootDir%\lib\*vc143*.lib") do (
	if exist "%%~ff" (
		set "AliasName=%%~nxf"
		setlocal EnableDelayedExpansion
		set "AliasName=!AliasName:vc143=vc142!"
		copy /y "%%~ff" "%BoostRootDir%\lib\!AliasName!" >nul
		endlocal
	)
)

echo ----------------------------------------------------------
echo Build is complete
echo ----------------------------------------------------------

exit /b 0

:FindVcVars
if defined vcvarsall (
	if exist "%vcvarsall%" exit /b 0
)

set "VsWhere=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
if not exist "%VsWhere%" set "VsWhere=%ProgramFiles%\Microsoft Visual Studio\Installer\vswhere.exe"

if exist "%VsWhere%" (
	for /f "usebackq tokens=*" %%i in (`"%VsWhere%" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do (
		if exist "%%i\VC\Auxiliary\Build\vcvarsall.bat" set "vcvarsall=%%i\VC\Auxiliary\Build\vcvarsall.bat"
		if exist "%%i\VC\Auxiliary\Build\vcvarsall.cmd" set "vcvarsall=%%i\VC\Auxiliary\Build\vcvarsall.cmd"
	)
)

if not defined vcvarsall (
	for %%P in (BuildTools Community Professional Enterprise) do (
		if not defined vcvarsall (
			if exist "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\%%P\VC\Auxiliary\Build\vcvarsall.bat" set "vcvarsall=%ProgramFiles(x86)%\Microsoft Visual Studio\2022\%%P\VC\Auxiliary\Build\vcvarsall.bat"
			if exist "%ProgramFiles%\Microsoft Visual Studio\2022\%%P\VC\Auxiliary\Build\vcvarsall.bat" set "vcvarsall=%ProgramFiles%\Microsoft Visual Studio\2022\%%P\VC\Auxiliary\Build\vcvarsall.bat"
		)
	)
)

if not defined vcvarsall (
	echo ERROR: Could not find Visual Studio 2022 vcvarsall.bat/cmd.
	exit /b 1
)

echo Using Visual Studio environment: %vcvarsall%
exit /b 0

:HavePrebuiltBoostLibs
if not exist "%BoostRootDir%\lib" exit /b 1

for %%L in (system chrono thread locale filesystem date_time regex) do (
	dir /b "%BoostRootDir%\lib\libboost_%%L-vc14*.lib" >nul 2>nul
	if errorlevel 1 exit /b 1
)

exit /b 0
