#!/usr/bin/env python3
"""
HydraDragon Universal "Coach" Model Trainer (LightGBM & ONNX)
Trains a high-speed, zero-day string & IOC detection model using the disk-cached
chunks generated by `extract_universal_chunks.py`.

Ensures exact 50% Benign / 50% Malicious balance and exports to ONNX for OpenEDR.
"""

import os
import sys
import glob
import argparse
import numpy as np
import lightgbm as lgb
import joblib
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import onnxmltools
from onnxmltools.convert.common.data_types import FloatTensorType

# Mirroring OpenEDR/owlyshield_predict/src/ml/url_predict.rs exactly
URL_FEATURE_NAMES = [
    "url_len",
    "domain_len",
    "path_len",
    "query_len",
    "path_depth",
    "subdomain_count",
    "query_param_count",
    "is_ip_host",
    "has_port",
    "is_https",
    "digit_count",
    "letter_count",
    "special_count",
    "digit_ratio",
    "letter_ratio",
    "special_ratio",
    "token_count",
    "max_token_len",
    "avg_token_len",
    "url_entropy",
    "host_entropy",
    "count_at",
    "count_question",
    "count_hyphen",
    "count_equal",
    "count_dot",
    "count_percent",
    "count_slash",
    "count_semicolon",
    "count_ampersand",
    "has_suspicious_tld",
    "has_hacked_keywords",
]


def load_chunks_from_disk(chunks_dir: str) -> Tuple[np.ndarray, np.ndarray]:
    """
    Loads and combines chunk files from disk.
    Balances to exact 50% Benign and 50% Malicious.
    """
    chunk_files = sorted(glob.glob(os.path.join(chunks_dir, "chunk_*.joblib")))
    if not chunk_files:
        print(f"[!] Error: No chunk files found in {chunks_dir}.")
        print("    Please run `extract_universal_chunks.py` first to generate chunks.")
        sys.exit(1)

    print(f"[*] Found {len(chunk_files)} disk chunks in {chunks_dir}...")
    X_list = []
    y_list = []

    for cfile in chunk_files:
        print(f"  -> Loading {os.path.basename(cfile)}...")
        data = joblib.load(cfile)
        X_list.append(data["X"])
        y_list.append(data["y"])

    X_all = np.vstack(X_list)
    y_all = np.concatenate(y_list)

    total_benign = int(np.sum(y_all == 0))
    total_malicious = int(np.sum(y_all == 1))
    print(f"[+] Total raw loaded: {len(y_all):,} samples ({total_benign:,} Benign, {total_malicious:,} Malicious)")

    # Strict 50 / 50 Subsampling
    min_count = min(total_benign, total_malicious)
    benign_indices = np.where(y_all == 0)[0][:min_count]
    malicious_indices = np.where(y_all == 1)[0][:min_count]
    final_indices = np.concatenate([benign_indices, malicious_indices])

    np.random.seed(42)
    np.random.shuffle(final_indices)

    X_final = X_all[final_indices]
    y_final = y_all[final_indices]

    print("=" * 68)
    print(f"[+] Final Balanced Dataset: {len(X_final):,} samples")
    print(f"    Class 0 (Benign):    {np.sum(y_final == 0):,} (50.0%)")
    print(f"    Class 1 (Malicious): {np.sum(y_final == 1):,} (50.0%)")
    print("=" * 68)
    return X_final, y_final


def parse_args():
    default_chunks = os.path.abspath(os.path.join(os.path.dirname(__file__), "cache_chunks"))
    default_onnx = os.path.abspath(os.path.join(os.path.dirname(__file__), "universal_coach_model.onnx"))

    parser = argparse.ArgumentParser(description="Train Universal Coach Model on Disk Chunks")
    parser.add_argument("--chunks-dir", default=default_chunks, help="Directory containing cached chunk_*.joblib files")
    parser.add_argument("--output-onnx", default=default_onnx, help="Path to save exported ONNX model")
    parser.add_argument("--n-estimators", type=int, default=350, help="Number of LightGBM trees")
    parser.add_argument("--learning-rate", type=float, default=0.03, help="Learning rate")
    return parser.parse_args()


def main():
    args = parse_args()
    print("=" * 72)
    print(" HydraDragon - Universal Coach Model Trainer ")
    print("=" * 72)

    X, y = load_chunks_from_disk(args.chunks_dir)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.15, random_state=42, stratify=y
    )
    print(f"[*] Train set: {len(X_train):,} | Test set: {len(X_test):,}")

    print("[*] Training LightGBM Classifier (50/50 Balanced with Zero False-Positive Tuning)...")
    clf = lgb.LGBMClassifier(
        n_estimators=args.n_estimators,
        learning_rate=args.learning_rate,
        num_leaves=63,
        max_depth=8,
        min_child_samples=30,
        subsample=0.85,
        colsample_bytree=0.85,
        scale_pos_weight=1.0,  # Exactly 50/50
        random_state=42,
        n_jobs=-1
    )
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)

    print("\n" + "=" * 30 + " EVALUATION REPORT " + "=" * 30)
    print(classification_report(y_test, y_pred, target_names=["Benign (0)", "Malicious (1)"], digits=4))
    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()
    fpr = fp / (fp + tn) * 100.0
    recall = tp / (tp + fn) * 100.0
    print(f"Confusion Matrix: TP={tp:,}, FN={fn:,}, TN={tn:,}, FP={fp:,}")
    print(f"Malicious Recall (Detection Rate): {recall:.2f}%")
    print(f"False Positive Rate (FPR):         {fpr:.2f}%")
    print("=" * 79)

    # Sanity checks
    print("\n[*] Sanity checks on benchmark IOCs:")
    from extract_universal_chunks import extract_url_features
    test_cases = [
        ("https://www.google.com", 0),
        ("http://nic.in", 0),
        ("8.8.8.8", 0),
        ("1.1.1.1", 0),
        ("https://github.com/HydraDragonAntivirus", 0),
        ("http://paypal-security-update-login.verify-account.xyz/signin", 1),
        ("http://x89qzk-malw.top/payload.bin", 1),
        ("185.220.101.5", 1),
        ("powershell.exe -enc aQB3AHIAIABoAHQAdABwADoALwAv", 1),
    ]
    for target, expected in test_cases:
        feat = np.array([extract_url_features(target)], dtype=np.float32)
        pred = int(clf.predict(feat)[0])
        prob = float(clf.predict_proba(feat)[0][1])
        status = "PASSED" if pred == expected else "FAILED"
        label_str = "MALICIOUS" if pred == 1 else "BENIGN"
        print(f"  [{status}] {target:55} -> {label_str} (Malicious Prob: {prob*100:.1f}%)")

    print(f"\n[*] Converting Universal Coach model to ONNX: {args.output_onnx}...")
    try:
        initial_type = [("float_input", FloatTensorType([None, len(URL_FEATURE_NAMES)]))]
        onnx_model = onnxmltools.convert_lightgbm(clf, initial_types=initial_type, target_opset=14)
        with open(args.output_onnx, "wb") as f:
            f.write(onnx_model.SerializeToString())
        print(f"[+] Universal Coach ONNX model successfully saved to: {args.output_onnx}")
    except Exception as e:
        print(f"[!] ONNX conversion warning/error: {e}")

    joblib_path = args.output_onnx.replace(".onnx", ".joblib")
    joblib.dump(clf, joblib_path)
    print(f"[+] Joblib model saved to: {joblib_path}")


if __name__ == "__main__":
    main()
