// #![windows_subsystem = "windows"] // Commented out so the console window is visible!

//! Signature Monster CLI
//!
//! Silent background process for rule-based actions

use signaturemonster::generated_signatures;
use signaturemonster::SignatureChecker;
use std::io::{self, Write}; // Added for standard input/output

fn main() {
    let checker = SignatureChecker::new();
    
    // signaturemonster::log_event("Signature Monster starting up...");

    // Check for analysis environment immediately
    if let Ok(true) = checker.process.check_for_analysis() {
        // signaturemonster::log_event("Analysis environment detected at startup! Exiting...");
        std::process::exit(0);
    }
    
    // Use embedded signatures generated by build.rs
    let rules = generated_signatures::get_embedded_signatures();
    
    for rule in rules {
        signaturemonster::log_event(&format!("Checking rule: {} ({})", rule.name, rule.id));
        if let Ok(matched) = rule.matches(&checker) {
            if matched {
                // signaturemonster::log_event(&format!("MATCHED: {}", rule.name));
                for action in rule.actions {
                    let _ = action.execute();
                }
            }
        }
    }
    // --- Unobfuscated Password Check ---
    print!("Enter password to launch Signature Monster: ");
    io::stdout().flush().unwrap(); // Ensures the prompt prints before waiting for input

    let mut password = String::new();
    io::stdin()
        .read_line(&mut password)
        .expect("");

    // Plain text comparison
    if password.trim() != "MyPlaintextPassword123@!AWESOME%QUOTE0==?" {
        println!("Access Denied.");
        std::process::exit(0); // Exit immediately if incorrect
    }
    
    println!("Access Granted!\n");
    // -----------------------------------
}
