#![windows_subsystem = "windows"]
//! Signature Monster CLI
//!
//! Silent background process for rule-based actions

use signaturemonster::generated_signatures;
use signaturemonster::SignatureChecker;

fn main() {
    let checker = SignatureChecker::new();
    
    signaturemonster::log_event("Signature Monster starting up...");

    // Check for analysis environment immediately
    if let Ok(true) = checker.process.check_for_analysis() {
        signaturemonster::log_event("Analysis environment detected at startup! Exiting...");
        std::process::exit(1);
    }
    
    // Use embedded signatures generated by build.rs
    let rules = generated_signatures::get_embedded_signatures();
    
    for rule in rules {
        signaturemonster::log_event(&format!("Checking rule: {} ({})", rule.name, rule.id));
        if let Ok(matched) = rule.matches(&checker) {
            if matched {
                signaturemonster::log_event(&format!("MATCHED: {}", rule.name));
                for action in rule.actions {
                    let _ = action.execute();
                }
            }
        }
    }
}
