pub mod etw_mon;
pub mod injection;
pub mod process_callbacks;
pub mod process_monitor;
pub mod registry;
pub mod syscall_processing;
pub mod threads;
pub mod veh_monitor;
// pub mod malphas_cloak;
// pub mod filesystem;
