/// Feature vector for PE file classification.
#[derive(Debug, Clone)]
pub struct PeFeatureVector {
    pub size_of_optional_header: f32,
    pub major_linker_version: f32,
    pub minor_linker_version: f32,
    pub size_of_code: f32,
    pub size_of_initialized_data: f32,
    pub size_of_uninitialized_data: f32,
    pub address_of_entry_point: f32,
    pub image_base: f32,
    pub subsystem: f32,
    pub dll_characteristics: f32,
    pub size_of_stack_reserve: f32,
    pub size_of_heap_reserve: f32,
    pub checksum: f32,
    pub number_of_rva_and_sizes: f32,
    pub size_of_image: f32,
    pub imports_count: f32,
    pub exports_count: f32,
    pub resources_count: f32,
    pub sections_count: f32,
    pub overlay_exists: f32,
    pub overlay_size: f32,
    pub sec_entropy_mean: f32,
    pub sec_entropy_min: f32,
    pub sec_entropy_max: f32,
    pub total_instructions: f32,
    pub total_add_instructions: f32,
    pub total_mov_instructions: f32,
    pub is_likely_packed: f32,
    pub add_mov_ratio: f32,
    pub instructions_per_kb: f32,
    pub num_tls_callbacks: f32,
    pub num_delay_imports: f32,
    pub num_reloc_entries: f32,
    pub num_reloc_blocks: f32,
    pub num_bound_imports: f32,
    pub num_debug_entries: f32,
    pub cert_size: f32,
    pub has_rich_header: f32,
}

impl PeFeatureVector {
    pub const LEN: usize = 38;

    pub fn to_array(&self) -> [f32; 38] {
        [
            self.size_of_optional_header,
            self.major_linker_version,
            self.minor_linker_version,
            self.size_of_code,
            self.size_of_initialized_data,
            self.size_of_uninitialized_data,
            self.address_of_entry_point,
            self.image_base,
            self.subsystem,
            self.dll_characteristics,
            self.size_of_stack_reserve,
            self.size_of_heap_reserve,
            self.checksum,
            self.number_of_rva_and_sizes,
            self.size_of_image,
            self.imports_count,
            self.exports_count,
            self.resources_count,
            self.overlay_exists,
            self.sections_count,
            self.sec_entropy_mean,
            self.sec_entropy_min,
            self.sec_entropy_max,
            self.total_instructions,
            self.total_add_instructions,
            self.total_mov_instructions,
            self.is_likely_packed,
            self.add_mov_ratio,
            self.instructions_per_kb,
            self.overlay_size,
            self.num_tls_callbacks,
            self.num_delay_imports,
            self.num_reloc_entries,
            self.num_reloc_blocks,
            self.num_bound_imports,
            self.num_debug_entries,
            self.cert_size,
            self.has_rich_header,
        ]
    }
}

#[derive(Debug, Clone)]
pub struct JsFeatureVector {
    pub file_size: f32,
    pub entropy: f32,
    pub parse_success: f32,
    pub function_count: f32,
    pub variable_declarations: f32,
    pub call_expressions: f32,
    pub member_expressions: f32,
    pub binary_expressions: f32,
    pub conditional_statements: f32,
    pub loop_statements: f32,
    pub try_catch_blocks: f32,
    pub array_literals: f32,
    pub object_literals: f32,
    pub max_nesting_depth: f32,
    pub eval_usage: f32,
    pub suspicious_call_count: f32,
    pub hex_encoded_strings: f32,
    pub unicode_encoded_strings: f32,
    pub char_code_usage: f32,
    pub base64_usage: f32,
    pub escape_usage: f32,
    pub bracket_notation_calls: f32,
    pub obfuscation_score: f32,
    pub is_obfuscated: f32,
    pub crypto_references: f32,
    pub network_operations: f32,
    pub file_system_operations: f32,
    pub registry_operations: f32,
    pub process_operations: f32,
    pub suspicious_api_calls: f32,
    pub suspicious_score: f32,
    pub total_strings: f32,
    pub avg_string_length: f32,
    pub max_string_length: f32,
    pub long_strings_count: f32,
    pub base64_like_strings: f32,
    pub url_strings: f32,
    pub hex_strings: f32,
    pub total_lines: f32,
    pub code_lines: f32,
    pub comment_lines: f32,
    pub blank_lines: f32,
    pub avg_line_length: f32,
    pub max_line_length: f32,
    pub cyclomatic_complexity: f32,
    pub total_identifiers: f32,
    pub short_identifiers: f32,
    pub long_identifiers: f32,
    pub avg_identifier_length: f32,
    pub suspicious_naming: f32,
    pub random_like_identifiers: f32,
}

impl JsFeatureVector {
    pub const LEN: usize = 51;

    pub fn to_array(&self) -> [f32; 51] {
        [
            self.file_size,
            self.entropy,
            self.parse_success,
            self.function_count,
            self.variable_declarations,
            self.call_expressions,
            self.member_expressions,
            self.binary_expressions,
            self.conditional_statements,
            self.loop_statements,
            self.try_catch_blocks,
            self.array_literals,
            self.object_literals,
            self.max_nesting_depth,
            self.eval_usage,
            self.suspicious_call_count,
            self.hex_encoded_strings,
            self.unicode_encoded_strings,
            self.char_code_usage,
            self.base64_usage,
            self.escape_usage,
            self.bracket_notation_calls,
            self.obfuscation_score,
            self.is_obfuscated,
            self.crypto_references,
            self.network_operations,
            self.file_system_operations,
            self.registry_operations,
            self.process_operations,
            self.suspicious_api_calls,
            self.suspicious_score,
            self.total_strings,
            self.avg_string_length,
            self.max_string_length,
            self.long_strings_count,
            self.base64_like_strings,
            self.url_strings,
            self.hex_strings,
            self.total_lines,
            self.code_lines,
            self.comment_lines,
            self.blank_lines,
            self.avg_line_length,
            self.max_line_length,
            self.cyclomatic_complexity,
            self.total_identifiers,
            self.short_identifiers,
            self.long_identifiers,
            self.avg_identifier_length,
            self.suspicious_naming,
            self.random_like_identifiers,
        ]
    }
}
