# Reconstructed from integrated Nuitka blob
# Module: upygments.lexers

a__qualname__
a__getattr__
u_automodule.__getattr__
a__orig_bases__
modules
oldmod
T upygments.lexers
newmod
update
upygments\lexers\__init__.py
u<module pygments.lexers>
T aself
name
info
cls
T a__class__
T afn
glob
pattern
T aplugins
key
module_name
name
T amodule_name
mod
lexer_name
cls
T aname
module_name
lname
aliases
w_acls
T a_alias
module_name
name
aliases
w_acls
T a_fn
code
matches
fn
modname
name
w_afilenames
filename
cls
get_rating
T aplugins
item
lexer
T a_alias
options
module_name
name
aliases
w_acls
T a_fn
code
options
res
T a_mime
options
modname
name
w_amimetypes
cls
T ainfo
cls
filename
bonus
code
T acode
T a_text
options
inencoding
w_aft
best_lexer
lexer
rv
T a_fn
a_text
options
fn
primary
matching_lexers
lexer
filename
result
rv
type_sort
T afilename
lexername
options
custom_namespace
wfalexer_class
err
T wtaprimary
T aprimary
.pygments.modeline
modeline_re
search
group
T l asplitlines
q l aget_filetype_from_line
a__doc__
a__file__
a__spec__
origin
has_location
a__cached__
re
l
get_filetype_from_buffer
a__all__
compile

(?: vi | vim | ex ) (?: [<=>]? \d* )? :
.* (?: ft | filetype | syn | syntax ) = ( [^:\s]+ )
aVERBOSE
T l upygments\modeline.py
u<module pygments.modeline>
T abuf
max_lines
lines
line
ret
wiT wlwmu
.pygments.plugin
99
aEntryPoints
aEntryPoint
accelerate
uaccelerate.commands.accelerate_cli:main
console_scripts
T aname
value
group
uaccelerate-config
uaccelerate.commands.config:main
uaccelerate-estimate-memory
uaccelerate.commands.estimate:main
uaccelerate-launch
uaccelerate.commands.launch:main
uaccelerate-merge-weights
uaccelerate.commands.merge:main
anyio
uanyio.pytest_plugin
pytest11
bottle
ubottle:main
cffi_modules
ucffi.setuptools_ext:cffi_modules
udistutils.setup_keywords
normalizer
ucharset_normalizer.cli:cli_detect
clear_comtypes_cache
ucomtypes.clear_cache:main
udatasets-cli
udatasets.commands.datasets_cli:main
distro
udistro.distro:main
fastapi
ufastapi.cli:main
flask
uflask.cli:main
futurize
ulibfuturize.main:main
pasteurize
ulibpasteurize.main:main
httpx
uhttpx:main
hf
uhuggingface_hub.cli.hf:main
uhuggingface-cli
uhuggingface_hub.commands.huggingface_cli:main
utiny-agents
uhuggingface_hub.inference._mcp.cli:app
uhuggingface_hub.HfFileSystem
ufsspec.specs
jinja2
ujinja2.ext:babel_extract[i18n]
ubabel.extractors
jsonschema
ujsonschema.cli:main
keyring
ukeyring.cli:main
ukeyring.devpi_client
devpi_client
aKWallet
ukeyring.backends.kwallet
ukeyring.backends
aSecretService
ukeyring.backends.SecretService
aWindows
ukeyring.backends.Windows
chainer
ukeyring.backends.chainer
libsecret
ukeyring.backends.libsecret
macOS
ukeyring.backends.macOS
uinstall-wheel-from-presigned
ullama_stack.cli.scripts.run:install_wheel_from_presigned
llama
ullama_stack.cli.llama:main
ullama-stack-client
ullama_stack_client.lib.cli.llama_stack_client:main
umarkdown-it
umarkdown_it.cli.parse:main
mss
umss.__main__:main
nx_loopback
unetworkx.classes.tests.dispatch_interface:backend_interface
unetworkx.backends
bdist_nuitka
unuitka.distutils.DistutilCommands:bdist_nuitka
udistutils.commands
build_nuitka
unuitka.distutils.DistutilCommands:build
install_nuitka
unuitka.distutils.DistutilCommands:install
build_with_nuitka
unuitka.distutils.DistutilCommands:setupNuitkaDistutilsCommands
numpy
array_api
uhook-dirs
unumpy:_pyinstaller_hooks_dir
pyinstaller40
f2py
unumpy.f2py.f2py2e:main
unumpy-config
unumpy._configtool:main
openai
uopenai.cli:main
contextvars_context
uopentelemetry.context.contextvars_context:ContextVarsRuntimeContext
opentelemetry_context
api
uopentelemetry.environment_variables
opentelemetry_environment_variables
default_meter_provider
uopentelemetry.metrics:NoOpMeterProvider
opentelemetry_meter_provider
baggage
uopentelemetry.baggage.propagation:W3CBaggagePropagator
opentelemetry_propagator
tracecontext
uopentelemetry.trace.propagation.tracecontext:TraceContextTextMapPropagator
default_tracer_provider
uopentelemetry.trace:NoOpTracerProvider
opentelemetry_tracer_provider
otlp_proto_http
uopentelemetry.exporter.otlp.proto.http._log_exporter:OTLPLogExporter
opentelemetry_logs_exporter
uopentelemetry.exporter.otlp.proto.http.metric_exporter:OTLPMetricExporter
opentelemetry_metrics_exporter
uopentelemetry.exporter.otlp.proto.http.trace_exporter:OTLPSpanExporter
opentelemetry_traces_exporter
sdk
uopentelemetry.sdk.environment_variables
random
uopentelemetry.sdk.trace.id_generator:RandomIdGenerator
opentelemetry_id_generator
sdk_logger_provider
uopentelemetry.sdk._logs:LoggerProvider
opentelemetry_logger_provider
console
uopentelemetry.sdk._logs.export:ConsoleLogRecordExporter
sdk_meter_provider
uopentelemetry.sdk.metrics:MeterProvider
uopentelemetry.sdk.metrics.export:ConsoleMetricExporter
host
uopentelemetry.sdk.resources:_HostResourceDetector
opentelemetry_resource_detector
os
uopentelemetry.sdk.resources:OsResourceDetector
otel
uopentelemetry.sdk.resources:OTELResourceDetector
process
uopentelemetry.sdk.resources:ProcessResourceDetector
sdk_tracer_provider
uopentelemetry.sdk.trace:TracerProvider
uopentelemetry.sdk.trace.export:ConsoleSpanExporter
always_off
uopentelemetry.sdk.trace.sampling:_AlwaysOff
opentelemetry_traces_sampler
always_on
uopentelemetry.sdk.trace.sampling:_AlwaysOn
parentbased_always_off
uopentelemetry.sdk.trace.sampling:_ParentBasedAlwaysOff
parentbased_always_on
uopentelemetry.sdk.trace.sampling:_ParentBasedAlwaysOn
parentbased_traceidratio
uopentelemetry.sdk.trace.sampling:ParentBasedTraceIdRatio
traceidratio
uopentelemetry.sdk.trace.sampling:TraceIdRatioBased
eggcacher
udirect.directscripts.eggcacher:main
pfreeze
udirect.dist.pfreeze:main
apply_patch
upanda3d_tools:apply_patch
ubam-info
upanda3d_tools:bam_info
bam2egg
upanda3d_tools:bam2egg
build_patch
upanda3d_tools:build_patch
cginfo
upanda3d_tools:cginfo
check_adler
upanda3d_tools:check_adler
check_crc
upanda3d_tools:check_crc
check_md5
upanda3d_tools:check_md5
dae2egg
upanda3d_tools:dae2egg
udeploy-stub
upanda3d_tools:deploy_stub
udeploy-stubw
upanda3d_tools:deploy_stubw
udxf-points
upanda3d_tools:dxf_points
dxf2egg
upanda3d_tools:dxf2egg
uegg-crop
upanda3d_tools:egg_crop
uegg-list-textures
upanda3d_tools:egg_list_textures
uegg-make-tube
upanda3d_tools:egg_make_tube
uegg-mkfont
upanda3d_tools:egg_mkfont
uegg-optchar
upanda3d_tools:egg_optchar
uegg-palettize
upanda3d_tools:egg_palettize
uegg-qtess
upanda3d_tools:egg_qtess
uegg-rename
upanda3d_tools:egg_rename
uegg-retarget-anim
upanda3d_tools:egg_retarget_anim
uegg-texture-cards
upanda3d_tools:egg_texture_cards
uegg-topstrip
upanda3d_tools:egg_topstrip
uegg-trans
upanda3d_tools:egg_trans
egg2bam
upanda3d_tools:egg2bam
egg2c
upanda3d_tools:egg2c
egg2dxf
upanda3d_tools:egg2dxf
egg2flt
upanda3d_tools:egg2flt
egg2maya2008
upanda3d_tools:egg2maya2008
egg2maya2009
upanda3d_tools:egg2maya2009
egg2maya2011
upanda3d_tools:egg2maya2011
egg2maya2012
upanda3d_tools:egg2maya2012
egg2maya2013
upanda3d_tools:egg2maya2013
egg2maya2014
upanda3d_tools:egg2maya2014
egg2maya2015
upanda3d_tools:egg2maya2015
egg2maya2016
upanda3d_tools:egg2maya2016
egg2maya20165
upanda3d_tools:egg2maya20165
egg2maya2017
upanda3d_tools:egg2maya2017
egg2maya2018
upanda3d_tools:egg2maya2018
egg2maya2019
upanda3d_tools:egg2maya2019
egg2maya2020
upanda3d_tools:egg2maya2020
egg2maya2022
upanda3d_tools:egg2maya2022
egg2maya85
upanda3d_tools:egg2maya85
egg2obj
upanda3d_tools:egg2obj
egg2x
upanda3d_tools:egg2x
ffmpeg
upanda3d_tools:ffmpeg
ffplay
upanda3d_tools:ffplay
ffprobe
upanda3d_tools:ffprobe
uflt-info
upanda3d_tools:flt_info
uflt-trans
upanda3d_tools:flt_trans
flt2egg
upanda3d_tools:flt2egg
fltcopy
upanda3d_tools:fltcopy
uimage-info
upanda3d_tools:image_info
uimage-resize
upanda3d_tools:image_resize
uimage-trans
upanda3d_tools:image_trans
interrogate
upanda3d_tools:interrogate
interrogate_module
upanda3d_tools:interrogate_module
ulwo-scan
upanda3d_tools:lwo_scan
lwo2egg
upanda3d_tools:lwo2egg
umake-prc-key
upanda3d_tools:make_prc_key
maya2egg2008
upanda3d_tools:maya2egg2008
maya2egg2009
upanda3d_tools:maya2egg2009
maya2egg2011
upanda3d_tools:maya2egg2011
maya2egg2012
upanda3d_tools:maya2egg2012
maya2egg2013
upanda3d_tools:maya2egg2013
maya2egg2014
upanda3d_tools:maya2egg2014
maya2egg2015
upanda3d_tools:maya2egg2015
maya2egg2016
upanda3d_tools:maya2egg2016
maya2egg20165
upanda3d_tools:maya2egg20165
maya2egg2017
upanda3d_tools:maya2egg2017
maya2egg2018
upanda3d_tools:maya2egg2018
maya2egg2019
upanda3d_tools:maya2egg2019
maya2egg2020
upanda3d_tools:maya2egg2020
maya2egg2022
upanda3d_tools:maya2egg2022
maya2egg85
upanda3d_tools:maya2egg85
mayacopy2008
upanda3d_tools:mayacopy2008
mayacopy2009
upanda3d_tools:mayacopy2009
mayacopy2011
upanda3d_tools:mayacopy2011
mayacopy2012
upanda3d_tools:mayacopy2012
mayacopy2013
upanda3d_tools:mayacopy2013
mayacopy2014
upanda3d_tools:mayacopy2014
mayacopy2015
upanda3d_tools:mayacopy2015
mayacopy2016
upanda3d_tools:mayacopy2016
mayacopy20165
upanda3d_tools:mayacopy20165
mayacopy2017
upanda3d_tools:mayacopy2017
mayacopy2018
upanda3d_tools:mayacopy2018
mayacopy2019
upanda3d_tools:mayacopy2019
mayacopy2020
upanda3d_tools:mayacopy2020
mayacopy2022
upanda3d_tools:mayacopy2022
mayacopy85
upanda3d_tools:mayacopy85
multify
upanda3d_tools:multify
obj2egg
upanda3d_tools:obj2egg
p3dcparse
upanda3d_tools:p3dcparse
parse_file
upanda3d_tools:parse_file
pdecrypt
upanda3d_tools:pdecrypt
pencrypt
upanda3d_tools:pencrypt
upfm-bba
upanda3d_tools:pfm_bba
upfm-trans
upanda3d_tools:pfm_trans
pstats
upanda3d_tools:pstats
punzip
upanda3d_tools:punzip
pview
upanda3d_tools:pview
pzip
upanda3d_tools:pzip
show_ddb
upanda3d_tools:show_ddb
test_interrogate
upanda3d_tools:test_interrogate
utext-stats
upanda3d_tools:text_stats
uvrml-trans
upanda3d_tools:vrml_trans
vrml2egg
upanda3d_tools:vrml2egg
ux-trans
upanda3d_tools:x_trans
x2egg
upanda3d_tools:x2egg
build_apps
udirect.dist.commands:build_apps
bdist_apps
udirect.dist.commands:bdist_apps
udirect.dist._dist_hooks:finalize_distribution_options
usetuptools.finalize_distribution_options
gltf2bam
ugltf.cli:main
ugltf-viewer
ugltf.viewer:main
gui_scripts
glb
ugltf._loader:GltfLoader
upanda3d.loaders
gltf
hdr2env
usimplepbr.hdr2env:main
matplotlib
upandas:plotting._matplotlib
pandas_plotting_backends
pip
upip._internal.cli.main:main
pip3
playwright
uplaywright.__main__:main
uplaywright._impl.__pyinstaller:get_hook_dirs
pyaml
upyaml.cli:main
pycookie
upycookie.main:main
upygame.__pyinstaller:get_hook_dirs
pygmentize
upygments.cmdline:main
pylupdate5
uPyQt5.pylupdate_main:main
pyrcc5
uPyQt5.pyrcc_main:main
pyuic5
uPyQt5.uic.pyuic:main
pylupdate6
uPyQt6.lupdate.pylupdate:main
pyuic6
uPyQt6.uic.pyuic:main
upyside6-assistant
uPySide6.scripts.pyside_tool:assistant
upyside6-balsam
uPySide6.scripts.pyside_tool:balsam
upyside6-balsamui
uPySide6.scripts.pyside_tool:balsamui
upyside6-deploy
uPySide6.scripts.pyside_tool:deploy
upyside6-designer
uPySide6.scripts.pyside_tool:designer
upyside6-genpyi
uPySide6.scripts.pyside_tool:genpyi
upyside6-linguist
uPySide6.scripts.pyside_tool:linguist
upyside6-lrelease
uPySide6.scripts.pyside_tool:lrelease
upyside6-lupdate
uPySide6.scripts.pyside_tool:lupdate
upyside6-metaobjectdump
uPySide6.scripts.pyside_tool:metaobjectdump
upyside6-project
uPySide6.scripts.pyside_tool:project
upyside6-qml
uPySide6.scripts.pyside_tool:qml
upyside6-qmlcachegen
uPySide6.scripts.pyside_tool:qmlcachegen
upyside6-qmlformat
uPySide6.scripts.pyside_tool:qmlformat
upyside6-qmlimportscanner
uPySide6.scripts.pyside_tool:qmlimportscanner
upyside6-qmllint
uPySide6.scripts.pyside_tool:qmllint
upyside6-qmlls
uPySide6.scripts.pyside_tool:qmlls
upyside6-qmltyperegistrar
uPySide6.scripts.pyside_tool:qmltyperegistrar
upyside6-qsb
uPySide6.scripts.pyside_tool:qsb
upyside6-qtpy2cpp
uPySide6.scripts.pyside_tool:qtpy2cpp
upyside6-rcc
uPySide6.scripts.pyside_tool:rcc
upyside6-svgtoqml
uPySide6.scripts.pyside_tool:svgtoqml
upyside6-uic
uPySide6.scripts.pyside_tool:uic
pytesseract
upytesseract.pytesseract:main
dotenv
udotenv.__main__:cli
uwebview.__pyinstaller:get_hook_dirs
pywin32_postinstall
uwin32.scripts.pywin32_postinstall:main
pywin32_testall
uwin32.scripts.pywin32_testall:main
scapy
uscapy.main:interact
alias
usetuptools.command.alias:alias
bdist_egg
usetuptools.command.bdist_egg:bdist_egg
bdist_rpm
usetuptools.command.bdist_rpm:bdist_rpm
bdist_wheel
usetuptools.command.bdist_wheel:bdist_wheel
build
usetuptools.command.build:build
build_clib
usetuptools.command.build_clib:build_clib
build_ext
usetuptools.command.build_ext:build_ext
build_py
usetuptools.command.build_py:build_py
develop
usetuptools.command.develop:develop
dist_info
usetuptools.command.dist_info:dist_info
easy_install
usetuptools.command.easy_install:easy_install
editable_wheel
usetuptools.command.editable_wheel:editable_wheel
egg_info
usetuptools.command.egg_info:egg_info
install
usetuptools.command.install:install
install_egg_info
usetuptools.command.install_egg_info:install_egg_info
install_lib
usetuptools.command.install_lib:install_lib
install_scripts
usetuptools.command.install_scripts:install_scripts
rotate
usetuptools.command.rotate:rotate
saveopts
usetuptools.command.saveopts:saveopts
sdist
usetuptools.command.sdist:sdist
setopt
usetuptools.command.setopt:setopt
test
usetuptools.command.test:test
upload_docs
usetuptools.command.upload_docs:upload_docs
dependency_links
usetuptools.dist:assert_string_list
eager_resources
entry_points
usetuptools.dist:check_entry_points
exclude_package_data
usetuptools.dist:check_package_data
extras_require
usetuptools.dist:check_extras
include_package_data
usetuptools.dist:assert_bool
install_requires
usetuptools.dist:check_requirements
namespace_packages
usetuptools.dist:check_nsp
package_data
packages
usetuptools.dist:check_packages
python_requires
usetuptools.dist:check_specifier
setup_requires
test_loader
usetuptools.dist:check_importable
test_runner
test_suite
usetuptools.dist:check_test_suite
tests_require
use_2to3
usetuptools.dist:invalid_unless_false
zip_safe
uPKG-INFO
usetuptools.command.egg_info:write_pkg_info
uegg_info.writers
udependency_links.txt
usetuptools.command.egg_info:overwrite_arg
ueager_resources.txt
uentry_points.txt
usetuptools.command.egg_info:write_entries
unamespace_packages.txt
urequires.txt
usetuptools.command.egg_info:write_requirements
utop_level.txt
usetuptools.command.egg_info:write_toplevel_names
keywords
usetuptools.dist:Distribution._finalize_setup_keywords
parent_finalize
usetuptools.dist:_Distribution.finalize_options
uspark-parser-coverage
uspark_parser.bin.parser_coverage:run
sprc
uspeech_recognition.cli:main
isympy
uisympy:main
uconvert-caffe2-to-onnx
ucaffe2.python.onnx.bin.conversion:caffe2_to_onnx
uconvert-onnx-to-caffe2
ucaffe2.python.onnx.bin.conversion:onnx_to_caffe2
torchfrtrace
utools.flight_recorder.fr_trace:main
torchrun
utorch.distributed.run:main
default
utorch.distributed.elastic.multiprocessing:DefaultLogsSpecs
utorchrun.logs_specs
tqdm
utqdm.cli:main
transformers
utransformers.commands.transformers_cli:main
utransformers-cli
utransformers.commands.transformers_cli:main_cli
trio
utrio._core._run:_hypothesis_plugin_setup
hypothesis
uncompyle6
uuncompyle6.bin.uncompile:main_bin
uuncompyle6-tokenize
uuncompyle6.bin.pydisassemble:main
uvicorn
uuvicorn.main:main
websockets
uwebsockets.cli:main
wsdump
uwebsocket._wsdump:main
pydisasm
uxdis.bin.pydisasm:main
select
T agroup
get
iter_entry_points
aLEXER_ENTRY_POINT
load
find_plugin_lexers
aFORMATTER_ENTRY_POINT
name
find_plugin_formatters
aSTYLE_ENTRY_POINT
find_plugin_styles
aFILTER_ENTRY_POINT
find_plugin_filters
a__doc__
a__file__
a__spec__
origin
has_location
a__cached__
upygments.lexers
upygments.formatters
upygments.styles
upygments.filters
upygments\plugin.py
u<module pygments.plugin>
T aentrypoint
T agroup_name
groups

.pygments.regexopt
>
w[aCS_ESCAPE
sub
u<lambda>
umake_charset.<locals>.<lambda>

w]w\agroup
w)l
escape
regex_opt_inner
:l nnu(?:
w?aoneletter
rest
w|amake_charset
commonprefix
:nnq asorted
groupby
uregex_opt_inner.<locals>.<lambda>
slen
u<genexpr>
uregex_opt_inner.<locals>.<genexpr>
first
l w(a__doc__
a__file__
a__spec__
origin
has_location
a__cached__
re
T aescape
uos.path
T acommonprefix
itertools
T agroupby
operator
T aitemgetter
itemgetter
compile
T u[\[\^\\\-\]]
T l
aFIRST_ELEMENT
T u
paregex_opt
upygments\regexopt.py
T a.0
group
T a.0
wsaslen
T wmT wsafirst
T afirst
u<module pygments.regexopt>
T aletters
T astrings
prefix
suffix
T astrings
open_paren
close_paren
first
oneletter
rest
wsaprefix
plen
strings_rev
suffix
slen
.pygments.style
s
a__new__
aSTANDARD_TYPES
obj
styles

colorformat
uStyleMeta.__new__.<locals>.colorformat
a_styles
split
parent
get
L	u
l
ppu
pl
ppanoinherit
aToken
:nnnabold
l andef
nobold
l
italic
l anoitalic
underline
l anounderline
:nl nubg:
:l nnl :nl nuborder:
:l nnl aroman
l asans
l amono
l aansicolors
:l
l nw#:l nnastartswith
T avar
T acalc
a_deprecated_ansicolors
a_ansimap
color
bgcolor
border
ansicolor
bgansicolor
cls
style_for_token
a__iter__
uStyleMeta.__iter__
a__doc__
a__file__
a__spec__
origin
has_location
a__cached__
upygments.token
T aToken
aSTANDARD_TYPES
D aansiblack
ansired
ansigreen
ansiyellow
ansiblue
ansimagenta
ansicyan
ansigray
ansibrightblack
ansibrightred
ansibrightgreen
ansibrightyellow
ansibrightblue
ansibrightmagenta
ansibrightcyan
ansiwhite
u000000
u7f0000
u007f00
u7f7fe0
u00007f
u7f007f
u007f7f
e5e5e5
u555555
ff0000
u00ff00
ffff00
u0000ff
ff00ff
u00ffff
ffffff
D u#ansiblack
u#ansidarkred
u#ansidarkgreen
u#ansibrown
u#ansidarkblue
u#ansipurple
u#ansiteal
u#ansilightgray
u#ansidarkgray
u#ansired
u#ansigreen
u#ansiyellow
u#ansiblue
u#ansifuchsia
u#ansiturquoise
u#ansiwhite
ansiblack
ansired
ansigreen
ansiyellow
ansiblue
ansimagenta
ansicyan
ansigray
ansibrightblack
ansibrightred
ansibrightgreen
ansibrightyellow
ansibrightblue
ansibrightmagenta
ansibrightcyan
ansiwhite
T Otype
a__prepare__
aStyleMeta
a__getitem__
u%s.__prepare__() must return a mapping, not %s
a__name__
u<metaclass>
