# Reconstructed from integrated Nuitka blob
# Module: upsutil.tests.test_windows

a__qualname__
a__orig_bases__
powershell
T Oint
wmic
aTestCpuAPIs
D areason
uNUMBER_OF_PROCESSORS env var is not available
test_cpu_count_vs_NUMBER_OF_PROCESSORS
uTestCpuAPIs.test_cpu_count_vs_NUMBER_OF_PROCESSORS
test_cpu_count_vs_GetSystemInfo
uTestCpuAPIs.test_cpu_count_vs_GetSystemInfo
test_cpu_count_logical_vs_wmi
uTestCpuAPIs.test_cpu_count_logical_vs_wmi
test_cpu_count_cores_vs_wmi
uTestCpuAPIs.test_cpu_count_cores_vs_wmi
test_cpu_count_vs_cpu_times
uTestCpuAPIs.test_cpu_count_vs_cpu_times
test_cpu_freq
uTestCpuAPIs.test_cpu_freq
aTestSystemAPIs
test_nic_names
uTestSystemAPIs.test_nic_names
test_total_phymem
uTestSystemAPIs.test_total_phymem
test_free_phymem
uTestSystemAPIs.test_free_phymem
test_total_swapmem
uTestSystemAPIs.test_total_swapmem
test_percent_swapmem
uTestSystemAPIs.test_percent_swapmem
test_pids
uTestSystemAPIs.test_pids
test_disks
uTestSystemAPIs.test_disks
test_disk_usage
uTestSystemAPIs.test_disk_usage
test_disk_partitions
uTestSystemAPIs.test_disk_partitions
test_convert_dos_path_drive
uTestSystemAPIs.test_convert_dos_path_drive
test_convert_dos_path_unc
uTestSystemAPIs.test_convert_dos_path_unc
test_net_if_stats
uTestSystemAPIs.test_net_if_stats
test_boot_time
uTestSystemAPIs.test_boot_time
test_uptime
uTestSystemAPIs.test_uptime
aTestSensorsBattery
test_has_battery
uTestSensorsBattery.test_has_battery
D areason
uno battery
test_percent
uTestSensorsBattery.test_percent
test_power_plugged
uTestSensorsBattery.test_power_plugged
test_emulate_no_battery
uTestSensorsBattery.test_emulate_no_battery
test_emulate_power_connected
uTestSensorsBattery.test_emulate_power_connected
test_emulate_power_charging
uTestSensorsBattery.test_emulate_power_charging
test_emulate_secs_left_unknown
uTestSensorsBattery.test_emulate_secs_left_unknown
aTestProcess
classmethod
setUpClass
uTestProcess.setUpClass
tearDownClass
uTestProcess.tearDownClass
test_issue_24
uTestProcess.test_issue_24
test_special_pid
uTestProcess.test_special_pid
test_send_signal
uTestProcess.test_send_signal
test_num_handles_increment
uTestProcess.test_num_handles_increment
test_ctrl_signals
uTestProcess.test_ctrl_signals
test_username
uTestProcess.test_username
test_cmdline
uTestProcess.test_cmdline
test_nice
uTestProcess.test_nice
test_memory_info
uTestProcess.test_memory_info
test_wait
uTestProcess.test_wait
test_cpu_affinity
uTestProcess.test_cpu_affinity
test_io_counters
uTestProcess.test_io_counters
test_num_handles
uTestProcess.test_num_handles
test_error_partial_copy
uTestProcess.test_error_partial_copy
test_exe
uTestProcess.test_exe
aTestProcessWMI
uTestProcessWMI.setUpClass
uTestProcessWMI.tearDownClass
test_name
uTestProcessWMI.test_name
D areason
uunreliable path on GITHUB_ACTIONS
uTestProcessWMI.test_exe
uTestProcessWMI.test_cmdline
uTestProcessWMI.test_username
test_memory_rss
uTestProcessWMI.test_memory_rss
test_memory_vms
uTestProcessWMI.test_memory_vms
test_create_time
uTestProcessWMI.test_create_time
aTestDualProcessImplementation
uTestDualProcessImplementation.setUpClass
uTestDualProcessImplementation.tearDownClass
uTestDualProcessImplementation.test_memory_info
uTestDualProcessImplementation.test_create_time
test_cpu_times
uTestDualProcessImplementation.test_cpu_times
uTestDualProcessImplementation.test_io_counters
uTestDualProcessImplementation.test_num_handles
uTestDualProcessImplementation.test_cmdline
aRemoteProcessTestCase
staticmethod
uRemoteProcessTestCase.find_other_interpreter
uimport sys; sys.stdin.read()
uRemoteProcessTestCase.setUp
uRemoteProcessTestCase.tearDown
test_cmdline_32
uRemoteProcessTestCase.test_cmdline_32
test_cmdline_64
uRemoteProcessTestCase.test_cmdline_64
test_cwd_32
uRemoteProcessTestCase.test_cwd_32
test_cwd_64
uRemoteProcessTestCase.test_cwd_64
test_environ_32
uRemoteProcessTestCase.test_environ_32
test_environ_64
uRemoteProcessTestCase.test_environ_64
aTestServices
test_win_service_iter
uTestServices.test_win_service_iter
test_win_service_get
uTestServices.test_win_service_get
upsutil\tests\test_windows.py
T a.0
proc
T a.0
wxaconverter
u<module psutil.tests.test_windows>
T a__class__
T acode
filename
proc
output
w_T wxT acmd
cmdline
T aself
other_python
env
a__class__
T acls
T aself
a__class__
T aself
wmi_os
wmi_btime_str
wmi_btime_dt
psutil_dt
diff
T aself
pid
wawbaerr
T aself
sys_value
psutil_value
T aself
wwwpT aself
wpT aself
winpath
driveletter
devicepath
ntpath1
ntpath2
devices
wmT aself
winpath
ntpath1
ntpath2
T aself
from_bitmask
handle
sys_value
psutil_value
T aself
wwacores
T aself
wwaprocs
T aself
num_cpus
T aself
T aself
wwaproc
T aself
cpu_times_1
fun
cpu_times_2
T aself
ctime
fun
T aself
wwwpawmic_create
psutil_create
T aself
disk
sys_value
psutil_value
T aself
ps_parts
wmi_parts
ps_part
wmi_part
usage
wmi_free
T aself
wmT aself
wpweT aself
exc
wmwpT aself
pid
proc
T aself
wwT aself
io_counters_1
fun
io_counters_2
wiT aself
handle
sys_value
psutil_value
T aself
mem_1
fun
mem_2
wiT aself
wwwparss
T aself
wwwpavms
wmi_usage
T aself
ps_names
wmi_adapters
wmi_names
wmi_adapter
T aself
out
nics
nic
T aself
num_handles
fun
T aself
ctypes
aPROCESS_QUERY_INFORMATION
handle
hndcnt
sys_value
psutil_value
T aself
wpabefore
handle
after
T aself
wwabattery_wmi
battery_psutil
T aself
wwapercentSwap
T aself
wwawmi_pids
psutil_pids
T aself
wparss
a_vms
T aself
ms
secs
T aself
name
T aself
wwwpadomain
w_ausername
T aself
handle
wpapsutil_value
sys_value
T aself
aERROR_SERVICE_DOES_NOT_EXIST
aERROR_ACCESS_DENIED
name
cm
service
exc
T aself
valid_statuses
valid_start_types
serv
data
pid
wpwsT apath
what
converter
out
data
.pygame.__pyinstaller
N
a__file__
a__doc__
path
dirname
join
environ
get
T aNUITKA_PACKAGE_pygame
u\not_existing
a__pyinstaller
T aNUITKA_PACKAGE_pygame___pyinstaller
u\not_existing
a__path__
a__spec__
origin
has_location
submodule_search_locations
a__cached__
os
get_hook_dirs
upygame\__pyinstaller\__init__.py
u<module pygame.__pyinstaller>

.pygame._camera_opencv
l
failed
l acv2
aVideoCapture
index
read
l adevice_idx
release
subprocess
uxml.etree
T aElementTree
aElementTree
aPopen
aPIPE
T usystem_profiler -xml SPCameraDataType
T ashell
stdout
stderr
communicate
utoo many values to unpack (expected 2)
fromstring
iterfind
T u./array/dict/array/dict/*
last_text
a_name
cameras
text
a_device_index
a_size
api_preference
aCAP_DSHOW
aRGB
aCOLOR_BGR2RGB
a_fmt
aYUV
aCOLOR_BGR2YUV
aHSV
aCOLOR_BGR2HSV
uNot a supported mode
a_open
a_cam
isOpened
uCould not open camera.
set
aCAP_PROP_FRAME_WIDTH
aCAP_PROP_FRAME_HEIGHT
get
a_flipx
a_flipy
a_brightness
aCAP_PROP_FPS
a_frametime
a_last_frame_time
pygame
error
T uCamera must be started
a_check_open
aCAP_PROP_BRIGHTNESS
get_controls
time
cvtColor
q aflip
numpy
fliplr
rot90
surfarray
make_surface
blit
T l
patobytes
list_cameras_darwin
uOpenCV-Mac backend can take device indices or names, ints or strings, not
a__class__
a__init__
a__doc__
a__file__
a__spec__
origin
has_location
a__cached__
sys
list_cameras
