# Reconstructed from integrated Nuitka blob
# Module: unumba.core.dispatcher

a__qualname__
uOmittedArg.__init__
a__repr__
uOmittedArg.__repr__
property
a_numba_type_
uOmittedArg._numba_type_
a__orig_bases__
u_FunctionCompiler.__init__
u_FunctionCompiler.fold_argument_types
u_FunctionCompiler.compile
u_FunctionCompiler._compile_cached
u_FunctionCompiler._compile_core
get_globals_for_reduction
u_FunctionCompiler.get_globals_for_reduction
u_FunctionCompiler._get_implementation
u_FunctionCompiler._customize_flags
u_GeneratedFunctionCompiler.__init__
u_GeneratedFunctionCompiler.get_globals_for_reduction
u_GeneratedFunctionCompiler._get_implementation
namedtuple
T a_CompileStats
T acache_path
cache_hits
cache_misses
uCompilingCounter.__init__
uCompilingCounter.__enter__
uCompilingCounter.__exit__
a__bool__
uCompilingCounter.__bool__
a__nonzero__
a__numba__
u_DispatcherBase.__init__
u_DispatcherBase._compilation_chain_init_hook
u_DispatcherBase._reset_overloads
u_DispatcherBase._make_finalizer
u_DispatcherBase.signatures
u_DispatcherBase.nopython_signatures
T tadisable_compile
u_DispatcherBase.disable_compile
u_DispatcherBase.add_overload
u_DispatcherBase.fold_argument_types
get_call_template
u_DispatcherBase.get_call_template
get_overload
u_DispatcherBase.get_overload
is_compiling
u_DispatcherBase.is_compiling
u_DispatcherBase._compile_for_args
u_DispatcherBase.inspect_llvm
u_DispatcherBase.inspect_asm
T nnFadefault
inspect_types
u_DispatcherBase.inspect_types
T nnu_DispatcherBase.inspect_cfg
u_DispatcherBase.inspect_disasm_cfg
get_annotation_info
u_DispatcherBase.get_annotation_info
a_explain_ambiguous
u_DispatcherBase._explain_ambiguous
a_explain_matching_error
u_DispatcherBase._explain_matching_error
a_search_new_conversions
u_DispatcherBase._search_new_conversions
u_DispatcherBase.__repr__
u_DispatcherBase.typeof_pyval
u_DispatcherBase._callback_add_timer
u_DispatcherBase._callback_add_compiler_timer
u_DispatcherBase._callback_add_llvm_timer
a_MemoMixin
aWeakValueDictionary
deque
aFUNCTION_CACHE_SIZE
T amaxlen
u_MemoMixin._uuid
u_MemoMixin._set_uuid
aReduceMixin
aCompiler
uDispatcher.__init__
T u
uDispatcher.dump
uDispatcher._numba_type_
enable_caching
uDispatcher.enable_caching
a__get__
uDispatcher.__get__
a_reduce_states
uDispatcher._reduce_states
classmethod
a_rebuild
uDispatcher._rebuild
uDispatcher.compile
get_compile_result
uDispatcher.get_compile_result
recompile
uDispatcher.recompile
stats
uDispatcher.stats
T nl aparallel_diagnostics
uDispatcher.parallel_diagnostics
get_metadata
uDispatcher.get_metadata
get_function_type
uDispatcher.get_function_type
aLiftedCode
can_cache
uLiftedCode.__init__
uLiftedCode._reduce_states
uLiftedCode._reduce_extras
uLiftedCode._rebuild
get_source_location
uLiftedCode.get_source_location
uLiftedCode._pre_compile
uLiftedCode.compile
a_get_dispatcher_for_current_target
uLiftedCode._get_dispatcher_for_current_target
aLiftedLoop
uLiftedLoop._pre_compile
uLiftedLoop.compile
uLiftedWith._reduce_extras
uLiftedWith._numba_type_
uLiftedWith.get_call_template
uLiftedWith.compile
aObjModeLiftedWith
uObjModeLiftedWith.__init__
uObjModeLiftedWith._numba_type_
uObjModeLiftedWith.get_call_template
uObjModeLiftedWith._legalize_arg_types
uObjModeLiftedWith.compile
aUSE_LEGACY_TYPE_SYSTEM
typeof_init
number_domain
np_number_domain
unumba\core\dispatcher.py
T a.0
wtT a.0
sig
self
T a.0
val
T a.0
wiaargs
T a.0
wiaerr
T a.0
sig
self
show_wrapper
T wxu<module numba.core.dispatcher>
T a__class__
T aself
T aself
args
kwargs
T aself
obj
objtype
T	aself
py_func
locals
targetoptions
pipeline_class
pysig
arg_count
can_fallback
compiler_class
T aself
func_ir
typingctx
targetctx
flags
locals
T aself
args
kwargs
a__class__
T aself
value
T aself
arg_count
py_func
pysig
can_fallback
exact_match_required
argnames
default_values
defargs
lastarg
has_stararg
T aself
py_func
targetdescr
targetoptions
locals
pipeline_class
T aself
py_func
targetdescr
targetoptions
locals
pipeline_class
a__class__
T aself
duration
cres
T aself
duration
cres
lock_name
md
timers
msg
T aself
args
return_type
key
retval
weT aself
args
return_type
flags
impl
cres
T aself
args
kws
error_rewrite
argtypes
waareturn_val
weaalready_lit_pos
wmainfo
failed_args
wiaarg
val
tp
typeof_exc
args_str
msg
help_msg
T aself
flags
T aself
args
kws
sigs
T aself
args
kws
msg
T aself
args
kws
T	aself
args
kws
impl
pysig
implsig
ok
pyparam
implparam
T aself
args
wiwaamsg
T aself
overloads
targetctx
finalizer
T aself
args
return_type
flags
T	acls
uuid
py_func
locals
targetoptions
can_compile
sigs
self
sig
T
cls
uuid
func_ir
flags
locals
extras
registry
typingctx
targetctx
self
T aself
sigs
T aself
args
kws
found
sig
conv
T aself
wuT aself
cres
args
sig
T adur
cres
self
T acres
self
T aself
sig
scope
cres
cb_compiler
cb_llvm
args
return_type
existing
ev_details
weafolded
T aself
sig
T aself
sig
scope
cres
cb_compiler
cb_llvm
flags
args
return_type
existing
npm_loop_flags
pyobject_loop_flags
cloned_func_ir_npm
cloned_func_ir_fbk
ev_details
T aself
sig
scope
cres
cb_compiler
cb_llvm
flags
args
return_type
existing
cloned_func_ir
ev_details
T aself
sig
args
w_a__class__
T aself
args
return_type
status
retval
T aindex
param
default
T aself
val
T aself
tab
cres
T asig
ol
pfdiag
msg
self
level
T alevel
self
T weaissue_type
help_msg
T ashutting_down
cres
overloads
targetctx
T aoverloads
targetctx
T aself
args
kws
normal_handler
default_handler
stararg_handler
T aargs
kws
self
T aself
signature
signatures
out
sig
cres
ta
key
T aself
args
kws
pysig
func_name
name
call_template
T aself
args
kws
signatures
pysig
func_name
name
call_template
T aself
sig
atypes
msg
T aself
cres
T aself
signature
T aself
sig
args
return_type
T aself
signature
lib
T aself
signature
show_wrapper
kwargs
cres
lib
fname
T aself
signature
cres
lib
T
self
file
signature
pretty
style
kwargs
overloads
ver
res
aAnnotate
T aindex
param
value
T aself
signature
level
dump
T aself
sigs
old_can_compile
sig
T aindex
param
values
T aself
val
tp
.numba.core.entrypoints
9
a_already_initialized
load_ep
uinit_all.<locals>.load_ep
aEntryPoints
aEntryPoint
accelerate
uaccelerate.commands.accelerate_cli:main
console_scripts
T aname
value
group
uaccelerate-config
uaccelerate.commands.config:main
uaccelerate-estimate-memory
uaccelerate.commands.estimate:main
uaccelerate-launch
uaccelerate.commands.launch:main
uaccelerate-merge-weights
uaccelerate.commands.merge:main
anyio
uanyio.pytest_plugin
pytest11
bottle
ubottle:main
cffi_modules
ucffi.setuptools_ext:cffi_modules
udistutils.setup_keywords
normalizer
ucharset_normalizer.cli:cli_detect
clear_comtypes_cache
ucomtypes.clear_cache:main
udatasets-cli
udatasets.commands.datasets_cli:main
distro
udistro.distro:main
fastapi
ufastapi.cli:main
flask
uflask.cli:main
futurize
ulibfuturize.main:main
pasteurize
ulibpasteurize.main:main
httpx
uhttpx:main
hf
uhuggingface_hub.cli.hf:main
uhuggingface-cli
uhuggingface_hub.commands.huggingface_cli:main
utiny-agents
uhuggingface_hub.inference._mcp.cli:app
uhuggingface_hub.HfFileSystem
ufsspec.specs
jinja2
ujinja2.ext:babel_extract[i18n]
ubabel.extractors
jsonschema
ujsonschema.cli:main
keyring
ukeyring.cli:main
ukeyring.devpi_client
devpi_client
aKWallet
ukeyring.backends.kwallet
ukeyring.backends
aSecretService
ukeyring.backends.SecretService
aWindows
ukeyring.backends.Windows
chainer
ukeyring.backends.chainer
libsecret
ukeyring.backends.libsecret
macOS
ukeyring.backends.macOS
uinstall-wheel-from-presigned
ullama_stack.cli.scripts.run:install_wheel_from_presigned
llama
ullama_stack.cli.llama:main
ullama-stack-client
ullama_stack_client.lib.cli.llama_stack_client:main
umarkdown-it
umarkdown_it.cli.parse:main
mss
umss.__main__:main
nx_loopback
unetworkx.classes.tests.dispatch_interface:backend_interface
unetworkx.backends
bdist_nuitka
unuitka.distutils.DistutilCommands:bdist_nuitka
udistutils.commands
build_nuitka
unuitka.distutils.DistutilCommands:build
install_nuitka
unuitka.distutils.DistutilCommands:install
build_with_nuitka
unuitka.distutils.DistutilCommands:setupNuitkaDistutilsCommands
numpy
array_api
uhook-dirs
unumpy:_pyinstaller_hooks_dir
pyinstaller40
f2py
unumpy.f2py.f2py2e:main
unumpy-config
unumpy._configtool:main
openai
uopenai.cli:main
contextvars_context
uopentelemetry.context.contextvars_context:ContextVarsRuntimeContext
opentelemetry_context
api
uopentelemetry.environment_variables
opentelemetry_environment_variables
default_meter_provider
uopentelemetry.metrics:NoOpMeterProvider
opentelemetry_meter_provider
baggage
uopentelemetry.baggage.propagation:W3CBaggagePropagator
opentelemetry_propagator
tracecontext
uopentelemetry.trace.propagation.tracecontext:TraceContextTextMapPropagator
default_tracer_provider
uopentelemetry.trace:NoOpTracerProvider
opentelemetry_tracer_provider
otlp_proto_http
uopentelemetry.exporter.otlp.proto.http._log_exporter:OTLPLogExporter
opentelemetry_logs_exporter
uopentelemetry.exporter.otlp.proto.http.metric_exporter:OTLPMetricExporter
opentelemetry_metrics_exporter
uopentelemetry.exporter.otlp.proto.http.trace_exporter:OTLPSpanExporter
opentelemetry_traces_exporter
sdk
uopentelemetry.sdk.environment_variables
random
uopentelemetry.sdk.trace.id_generator:RandomIdGenerator
opentelemetry_id_generator
sdk_logger_provider
uopentelemetry.sdk._logs:LoggerProvider
opentelemetry_logger_provider
console
uopentelemetry.sdk._logs.export:ConsoleLogRecordExporter
sdk_meter_provider
uopentelemetry.sdk.metrics:MeterProvider
uopentelemetry.sdk.metrics.export:ConsoleMetricExporter
host
uopentelemetry.sdk.resources:_HostResourceDetector
opentelemetry_resource_detector
os
uopentelemetry.sdk.resources:OsResourceDetector
otel
uopentelemetry.sdk.resources:OTELResourceDetector
process
uopentelemetry.sdk.resources:ProcessResourceDetector
sdk_tracer_provider
uopentelemetry.sdk.trace:TracerProvider
uopentelemetry.sdk.trace.export:ConsoleSpanExporter
always_off
uopentelemetry.sdk.trace.sampling:_AlwaysOff
opentelemetry_traces_sampler
always_on
uopentelemetry.sdk.trace.sampling:_AlwaysOn
parentbased_always_off
uopentelemetry.sdk.trace.sampling:_ParentBasedAlwaysOff
parentbased_always_on
uopentelemetry.sdk.trace.sampling:_ParentBasedAlwaysOn
parentbased_traceidratio
uopentelemetry.sdk.trace.sampling:ParentBasedTraceIdRatio
traceidratio
uopentelemetry.sdk.trace.sampling:TraceIdRatioBased
eggcacher
udirect.directscripts.eggcacher:main
pfreeze
udirect.dist.pfreeze:main
apply_patch
upanda3d_tools:apply_patch
ubam-info
upanda3d_tools:bam_info
bam2egg
upanda3d_tools:bam2egg
build_patch
upanda3d_tools:build_patch
cginfo
upanda3d_tools:cginfo
check_adler
upanda3d_tools:check_adler
check_crc
upanda3d_tools:check_crc
check_md5
upanda3d_tools:check_md5
dae2egg
upanda3d_tools:dae2egg
udeploy-stub
upanda3d_tools:deploy_stub
udeploy-stubw
upanda3d_tools:deploy_stubw
udxf-points
upanda3d_tools:dxf_points
dxf2egg
upanda3d_tools:dxf2egg
uegg-crop
upanda3d_tools:egg_crop
uegg-list-textures
upanda3d_tools:egg_list_textures
uegg-make-tube
upanda3d_tools:egg_make_tube
uegg-mkfont
upanda3d_tools:egg_mkfont
uegg-optchar
upanda3d_tools:egg_optchar
uegg-palettize
upanda3d_tools:egg_palettize
uegg-qtess
upanda3d_tools:egg_qtess
uegg-rename
upanda3d_tools:egg_rename
uegg-retarget-anim
upanda3d_tools:egg_retarget_anim
uegg-texture-cards
upanda3d_tools:egg_texture_cards
uegg-topstrip
upanda3d_tools:egg_topstrip
uegg-trans
upanda3d_tools:egg_trans
egg2bam
upanda3d_tools:egg2bam
egg2c
upanda3d_tools:egg2c
egg2dxf
upanda3d_tools:egg2dxf
egg2flt
upanda3d_tools:egg2flt
egg2maya2008
upanda3d_tools:egg2maya2008
egg2maya2009
upanda3d_tools:egg2maya2009
egg2maya2011
upanda3d_tools:egg2maya2011
egg2maya2012
upanda3d_tools:egg2maya2012
egg2maya2013
upanda3d_tools:egg2maya2013
egg2maya2014
upanda3d_tools:egg2maya2014
egg2maya2015
upanda3d_tools:egg2maya2015
egg2maya2016
upanda3d_tools:egg2maya2016
egg2maya20165
upanda3d_tools:egg2maya20165
egg2maya2017
upanda3d_tools:egg2maya2017
egg2maya2018
upanda3d_tools:egg2maya2018
egg2maya2019
upanda3d_tools:egg2maya2019
egg2maya2020
upanda3d_tools:egg2maya2020
egg2maya2022
upanda3d_tools:egg2maya2022
egg2maya85
upanda3d_tools:egg2maya85
egg2obj
upanda3d_tools:egg2obj
egg2x
upanda3d_tools:egg2x
ffmpeg
upanda3d_tools:ffmpeg
ffplay
upanda3d_tools:ffplay
ffprobe
upanda3d_tools:ffprobe
uflt-info
upanda3d_tools:flt_info
uflt-trans
upanda3d_tools:flt_trans
flt2egg
upanda3d_tools:flt2egg
fltcopy
upanda3d_tools:fltcopy
uimage-info
upanda3d_tools:image_info
uimage-resize
upanda3d_tools:image_resize
uimage-trans
upanda3d_tools:image_trans
interrogate
upanda3d_tools:interrogate
interrogate_module
upanda3d_tools:interrogate_module
ulwo-scan
upanda3d_tools:lwo_scan
lwo2egg
upanda3d_tools:lwo2egg
umake-prc-key
upanda3d_tools:make_prc_key
maya2egg2008
upanda3d_tools:maya2egg2008
maya2egg2009
upanda3d_tools:maya2egg2009
maya2egg2011
upanda3d_tools:maya2egg2011
maya2egg2012
upanda3d_tools:maya2egg2012
maya2egg2013
upanda3d_tools:maya2egg2013
maya2egg2014
upanda3d_tools:maya2egg2014
maya2egg2015
upanda3d_tools:maya2egg2015
maya2egg2016
upanda3d_tools:maya2egg2016
maya2egg20165
upanda3d_tools:maya2egg20165
maya2egg2017
upanda3d_tools:maya2egg2017
maya2egg2018
upanda3d_tools:maya2egg2018
maya2egg2019
upanda3d_tools:maya2egg2019
maya2egg2020
upanda3d_tools:maya2egg2020
maya2egg2022
upanda3d_tools:maya2egg2022
maya2egg85
upanda3d_tools:maya2egg85
mayacopy2008
upanda3d_tools:mayacopy2008
mayacopy2009
upanda3d_tools:mayacopy2009
mayacopy2011
upanda3d_tools:mayacopy2011
mayacopy2012
upanda3d_tools:mayacopy2012
mayacopy2013
upanda3d_tools:mayacopy2013
mayacopy2014
upanda3d_tools:mayacopy2014
mayacopy2015
upanda3d_tools:mayacopy2015
mayacopy2016
upanda3d_tools:mayacopy2016
mayacopy20165
upanda3d_tools:mayacopy20165
mayacopy2017
upanda3d_tools:mayacopy2017
mayacopy2018
upanda3d_tools:mayacopy2018
mayacopy2019
upanda3d_tools:mayacopy2019
mayacopy2020
upanda3d_tools:mayacopy2020
mayacopy2022
upanda3d_tools:mayacopy2022
mayacopy85
upanda3d_tools:mayacopy85
multify
upanda3d_tools:multify
obj2egg
upanda3d_tools:obj2egg
p3dcparse
upanda3d_tools:p3dcparse
parse_file
upanda3d_tools:parse_file
pdecrypt
upanda3d_tools:pdecrypt
pencrypt
upanda3d_tools:pencrypt
upfm-bba
upanda3d_tools:pfm_bba
upfm-trans
upanda3d_tools:pfm_trans
pstats
upanda3d_tools:pstats
punzip
upanda3d_tools:punzip
pview
upanda3d_tools:pview
pzip
upanda3d_tools:pzip
show_ddb
upanda3d_tools:show_ddb
test_interrogate
upanda3d_tools:test_interrogate
utext-stats
upanda3d_tools:text_stats
uvrml-trans
upanda3d_tools:vrml_trans
vrml2egg
upanda3d_tools:vrml2egg
ux-trans
upanda3d_tools:x_trans
x2egg
upanda3d_tools:x2egg
build_apps
udirect.dist.commands:build_apps
bdist_apps
udirect.dist.commands:bdist_apps
udirect.dist._dist_hooks:finalize_distribution_options
usetuptools.finalize_distribution_options
gltf2bam
ugltf.cli:main
ugltf-viewer
ugltf.viewer:main
gui_scripts
glb
ugltf._loader:GltfLoader
upanda3d.loaders
gltf
hdr2env
usimplepbr.hdr2env:main
matplotlib
upandas:plotting._matplotlib
pandas_plotting_backends
pip
upip._internal.cli.main:main
pip3
playwright
uplaywright.__main__:main
uplaywright._impl.__pyinstaller:get_hook_dirs
pyaml
upyaml.cli:main
pycookie
upycookie.main:main
upygame.__pyinstaller:get_hook_dirs
pygmentize
upygments.cmdline:main
pylupdate5
uPyQt5.pylupdate_main:main
pyrcc5
uPyQt5.pyrcc_main:main
pyuic5
uPyQt5.uic.pyuic:main
pylupdate6
uPyQt6.lupdate.pylupdate:main
pyuic6
uPyQt6.uic.pyuic:main
upyside6-assistant
uPySide6.scripts.pyside_tool:assistant
upyside6-balsam
uPySide6.scripts.pyside_tool:balsam
upyside6-balsamui
uPySide6.scripts.pyside_tool:balsamui
upyside6-deploy
uPySide6.scripts.pyside_tool:deploy
upyside6-designer
uPySide6.scripts.pyside_tool:designer
upyside6-genpyi
uPySide6.scripts.pyside_tool:genpyi
upyside6-linguist
uPySide6.scripts.pyside_tool:linguist
upyside6-lrelease
uPySide6.scripts.pyside_tool:lrelease
upyside6-lupdate
uPySide6.scripts.pyside_tool:lupdate
upyside6-metaobjectdump
uPySide6.scripts.pyside_tool:metaobjectdump
upyside6-project
uPySide6.scripts.pyside_tool:project
upyside6-qml
uPySide6.scripts.pyside_tool:qml
upyside6-qmlcachegen
uPySide6.scripts.pyside_tool:qmlcachegen
upyside6-qmlformat
uPySide6.scripts.pyside_tool:qmlformat
upyside6-qmlimportscanner
uPySide6.scripts.pyside_tool:qmlimportscanner
upyside6-qmllint
uPySide6.scripts.pyside_tool:qmllint
upyside6-qmlls
uPySide6.scripts.pyside_tool:qmlls
upyside6-qmltyperegistrar
uPySide6.scripts.pyside_tool:qmltyperegistrar
upyside6-qsb
uPySide6.scripts.pyside_tool:qsb
upyside6-qtpy2cpp
uPySide6.scripts.pyside_tool:qtpy2cpp
upyside6-rcc
uPySide6.scripts.pyside_tool:rcc
upyside6-svgtoqml
uPySide6.scripts.pyside_tool:svgtoqml
upyside6-uic
uPySide6.scripts.pyside_tool:uic
pytesseract
upytesseract.pytesseract:main
dotenv
udotenv.__main__:cli
uwebview.__pyinstaller:get_hook_dirs
pywin32_postinstall
uwin32.scripts.pywin32_postinstall:main
pywin32_testall
uwin32.scripts.pywin32_testall:main
scapy
uscapy.main:interact
alias
usetuptools.command.alias:alias
bdist_egg
usetuptools.command.bdist_egg:bdist_egg
bdist_rpm
usetuptools.command.bdist_rpm:bdist_rpm
bdist_wheel
usetuptools.command.bdist_wheel:bdist_wheel
build
usetuptools.command.build:build
build_clib
usetuptools.command.build_clib:build_clib
build_ext
usetuptools.command.build_ext:build_ext
build_py
usetuptools.command.build_py:build_py
develop
usetuptools.command.develop:develop
dist_info
usetuptools.command.dist_info:dist_info
easy_install
usetuptools.command.easy_install:easy_install
editable_wheel
usetuptools.command.editable_wheel:editable_wheel
egg_info
usetuptools.command.egg_info:egg_info
install
usetuptools.command.install:install
install_egg_info
usetuptools.command.install_egg_info:install_egg_info
install_lib
usetuptools.command.install_lib:install_lib
install_scripts
usetuptools.command.install_scripts:install_scripts
rotate
usetuptools.command.rotate:rotate
saveopts
usetuptools.command.saveopts:saveopts
sdist
usetuptools.command.sdist:sdist
setopt
usetuptools.command.setopt:setopt
test
usetuptools.command.test:test
upload_docs
usetuptools.command.upload_docs:upload_docs
dependency_links
usetuptools.dist:assert_string_list
eager_resources
entry_points
usetuptools.dist:check_entry_points
exclude_package_data
usetuptools.dist:check_package_data
extras_require
usetuptools.dist:check_extras
include_package_data
usetuptools.dist:assert_bool
install_requires
usetuptools.dist:check_requirements
namespace_packages
usetuptools.dist:check_nsp
package_data
packages
usetuptools.dist:check_packages
python_requires
usetuptools.dist:check_specifier
setup_requires
test_loader
usetuptools.dist:check_importable
test_runner
test_suite
usetuptools.dist:check_test_suite
tests_require
use_2to3
usetuptools.dist:invalid_unless_false
zip_safe
uPKG-INFO
usetuptools.command.egg_info:write_pkg_info
uegg_info.writers
udependency_links.txt
usetuptools.command.egg_info:overwrite_arg
ueager_resources.txt
uentry_points.txt
usetuptools.command.egg_info:write_entries
unamespace_packages.txt
urequires.txt
usetuptools.command.egg_info:write_requirements
utop_level.txt
usetuptools.command.egg_info:write_toplevel_names
keywords
usetuptools.dist:Distribution._finalize_setup_keywords
parent_finalize
usetuptools.dist:_Distribution.finalize_options
uspark-parser-coverage
uspark_parser.bin.parser_coverage:run
sprc
uspeech_recognition.cli:main
isympy
uisympy:main
uconvert-caffe2-to-onnx
ucaffe2.python.onnx.bin.conversion:caffe2_to_onnx
uconvert-onnx-to-caffe2
ucaffe2.python.onnx.bin.conversion:onnx_to_caffe2
torchfrtrace
utools.flight_recorder.fr_trace:main
torchrun
utorch.distributed.run:main
default
utorch.distributed.elastic.multiprocessing:DefaultLogsSpecs
utorchrun.logs_specs
tqdm
utqdm.cli:main
transformers
utransformers.commands.transformers_cli:main
utransformers-cli
utransformers.commands.transformers_cli:main_cli
trio
utrio._core._run:_hypothesis_plugin_setup
hypothesis
uncompyle6
uuncompyle6.bin.uncompile:main_bin
uuncompyle6-tokenize
uuncompyle6.bin.pydisassemble:main
uvicorn
uuvicorn.main:main
websockets
uwebsockets.cli:main
wsdump
uwebsocket._wsdump:main
pydisasm
uxdis.bin.pydisasm:main
select
T anumba_extensions
init
T agroup
name
get
T anumba_extensions
T
name
init
logger
debug
uLoading extension: %s
load
uNumba extension module '
module

u' failed to load due to '
a__name__
w(u)'.
warnings
warn
D astacklevel
l uExtension loading failed for: %s
a__doc__
a__file__
a__spec__
origin
has_location
a__cached__
logging
l
importlib_metadata
getLogger
T unumba.core.entrypoints
init_all
unumba\core\entrypoints.py
u<module numba.core.entrypoints>
T aload_ep
eps
entry_point
T aentry_point
func
weamsg
.numba.core.environment
K
:
a_memo
env_name
lookup_globals
a__name__
globals
a_rebuild_env
get
T a__name__
consts
u<Environment

u >
lookup_environment
import_module
aEnvironment
:nnna__doc__
a__file__
a__spec__
origin
has_location
a__cached__
weakref
l
importlib
numba
T a_dynfunc
a_dynfunc
a__prepare__
a__getitem__
u%s.__prepare__() must return a mapping, not %s
u<metaclass>
