# Reconstructed from integrated Nuitka blob
# Module: upsutil.tests.test_linux

a__qualname__
test_total
uTestSystemVirtualMemoryAgainstFree.test_total
test_used
uTestSystemVirtualMemoryAgainstFree.test_used
test_free
uTestSystemVirtualMemoryAgainstFree.test_free
test_shared
uTestSystemVirtualMemoryAgainstFree.test_shared
test_available
uTestSystemVirtualMemoryAgainstFree.test_available
a__orig_bases__
aTestSystemVirtualMemoryAgainstVmstat
uTestSystemVirtualMemoryAgainstVmstat.test_total
uTestSystemVirtualMemoryAgainstVmstat.test_used
uTestSystemVirtualMemoryAgainstVmstat.test_free
test_buffers
uTestSystemVirtualMemoryAgainstVmstat.test_buffers
test_active
uTestSystemVirtualMemoryAgainstVmstat.test_active
test_inactive
uTestSystemVirtualMemoryAgainstVmstat.test_inactive
aTestSystemVirtualMemoryMocks
test_warnings_on_misses
uTestSystemVirtualMemoryMocks.test_warnings_on_misses
test_avail_old_percent
uTestSystemVirtualMemoryMocks.test_avail_old_percent
test_avail_old_comes_from_kernel
uTestSystemVirtualMemoryMocks.test_avail_old_comes_from_kernel
test_avail_old_missing_fields
uTestSystemVirtualMemoryMocks.test_avail_old_missing_fields
test_avail_old_missing_zoneinfo
uTestSystemVirtualMemoryMocks.test_avail_old_missing_zoneinfo
test_virtual_memory_mocked
uTestSystemVirtualMemoryMocks.test_virtual_memory_mocked
aTestSystemSwapMemory
staticmethod
uTestSystemSwapMemory.meminfo_has_swap_info
uTestSystemSwapMemory.test_total
uTestSystemSwapMemory.test_used
uTestSystemSwapMemory.test_free
test_missing_sin_sout
uTestSystemSwapMemory.test_missing_sin_sout
test_no_vmstat_mocked
uTestSystemSwapMemory.test_no_vmstat_mocked
test_meminfo_against_sysinfo
uTestSystemSwapMemory.test_meminfo_against_sysinfo
test_emulate_meminfo_has_no_metrics
uTestSystemSwapMemory.test_emulate_meminfo_has_no_metrics
aTestSystemCPUTimes
test_fields
uTestSystemCPUTimes.test_fields
aTestSystemCPUCountLogical
T u/sys/devices/system/cpu/online
D areason
u/sys/devices/system/cpu/online does not exist
test_against_sysdev_cpu_online
uTestSystemCPUCountLogical.test_against_sysdev_cpu_online
T u/sys/devices/system/cpu
D areason
u/sys/devices/system/cpu does not exist
test_against_sysdev_cpu_num
uTestSystemCPUCountLogical.test_against_sysdev_cpu_num
which
T anproc
D areason
unproc utility not available
test_against_nproc
uTestSystemCPUCountLogical.test_against_nproc
T alscpu
D areason
ulscpu utility not available
test_against_lscpu
uTestSystemCPUCountLogical.test_against_lscpu
test_emulate_fallbacks
uTestSystemCPUCountLogical.test_emulate_fallbacks
aTestSystemCPUCountCores
uTestSystemCPUCountCores.test_against_lscpu
machine
P ai686
x86_64
D areason
ux86_64/i686 only
test_method_2
uTestSystemCPUCountCores.test_method_2
test_emulate_none
uTestSystemCPUCountCores.test_emulate_none
aTestSystemCPUFrequency
D areason
unot supported
D areason
uaarch64 does not always expose frequency
test_emulate_use_second_file
uTestSystemCPUFrequency.test_emulate_use_second_file
u does not report mhz in /proc/cpuinfo
T areason
test_emulate_use_cpuinfo
uTestSystemCPUFrequency.test_emulate_use_cpuinfo
test_emulate_data
uTestSystemCPUFrequency.test_emulate_data
test_emulate_multi_cpu
uTestSystemCPUFrequency.test_emulate_multi_cpu
test_emulate_no_scaling_cur_freq_file
uTestSystemCPUFrequency.test_emulate_no_scaling_cur_freq_file
aTestSystemCPUStats
test_interrupts
uTestSystemCPUStats.test_interrupts
aTestLoadAvg
test_getloadavg
uTestLoadAvg.test_getloadavg
aTestSystemNetIfAddrs
test_ips
uTestSystemNetIfAddrs.test_ips
aTestSystemNetIfStats
T aifconfig
D areason
uifconfig utility not available
test_against_ifconfig
uTestSystemNetIfStats.test_against_ifconfig
test_mtu
uTestSystemNetIfStats.test_mtu
test_flags
uTestSystemNetIfStats.test_flags
aTestSystemNetIOCounters
uTestSystemNetIOCounters.test_against_ifconfig
aTestSystemNetConnections
aValueError
T upsutil._pslinux.socket.inet_ntop
T upsutil._pslinux.supports_ipv6
Fatest_emulate_ipv6_unsupported
uTestSystemNetConnections.test_emulate_ipv6_unsupported
test_emulate_unix
uTestSystemNetConnections.test_emulate_unix
aTestSystemDiskPartitions
hasattr
statvfs
D areason
uos.statvfs() not available
test_against_df
uTestSystemDiskPartitions.test_against_df
test_zfs_fs
uTestSystemDiskPartitions.test_zfs_fs
test_emulate_realpath_fail
uTestSystemDiskPartitions.test_emulate_realpath_fail
aTestSystemDiskIoCounters
test_emulate_kernel_2_4
uTestSystemDiskIoCounters.test_emulate_kernel_2_4
test_emulate_kernel_2_6_full
uTestSystemDiskIoCounters.test_emulate_kernel_2_6_full
test_emulate_kernel_2_6_limited
uTestSystemDiskIoCounters.test_emulate_kernel_2_6_limited
test_emulate_include_partitions
uTestSystemDiskIoCounters.test_emulate_include_partitions
test_emulate_exclude_partitions
uTestSystemDiskIoCounters.test_emulate_exclude_partitions
test_emulate_use_sysfs
uTestSystemDiskIoCounters.test_emulate_use_sysfs
test_emulate_not_impl
uTestSystemDiskIoCounters.test_emulate_not_impl
aTestRootFsDeviceFinder
setUp
uTestRootFsDeviceFinder.setUp
test_call_methods
uTestRootFsDeviceFinder.test_call_methods
D areason
uunsupported on GITHUB_ACTIONS
test_comparisons
uTestRootFsDeviceFinder.test_comparisons
T afindmnt
D areason
ufindmnt utility not available
test_against_findmnt
uTestRootFsDeviceFinder.test_against_findmnt
test_disk_partitions_mocked
uTestRootFsDeviceFinder.test_disk_partitions_mocked
aTestMisc
test_boot_time
uTestMisc.test_boot_time
test_no_procfs_on_import
uTestMisc.test_no_procfs_on_import
test_cpu_steal_decrease
uTestMisc.test_cpu_steal_decrease
test_boot_time_mocked
uTestMisc.test_boot_time_mocked
test_users
uTestMisc.test_users
test_procfs_path
uTestMisc.test_procfs_path
xdist_group
T aserial
test_issue_687
uTestMisc.test_issue_687
test_pid_exists_no_proc_status
uTestMisc.test_pid_exists_no_proc_status
aTestSensorsBattery
D areason
uno battery
T aacpi
D areason
uacpi utility not available
test_percent
uTestSensorsBattery.test_percent
test_emulate_power_plugged
uTestSensorsBattery.test_emulate_power_plugged
test_emulate_power_plugged_2
uTestSensorsBattery.test_emulate_power_plugged_2
test_emulate_power_not_plugged
uTestSensorsBattery.test_emulate_power_not_plugged
test_emulate_power_not_plugged_2
uTestSensorsBattery.test_emulate_power_not_plugged_2
test_emulate_power_undetermined
uTestSensorsBattery.test_emulate_power_undetermined
test_emulate_energy_full_0
uTestSensorsBattery.test_emulate_energy_full_0
test_emulate_energy_full_not_avail
uTestSensorsBattery.test_emulate_energy_full_not_avail
test_emulate_no_power
uTestSensorsBattery.test_emulate_no_power
aTestSensorsBatteryEmulated
test_it
uTestSensorsBatteryEmulated.test_it
aTestSensorsTemperatures
test_emulate_class_hwmon
uTestSensorsTemperatures.test_emulate_class_hwmon
test_emulate_class_thermal
uTestSensorsTemperatures.test_emulate_class_thermal
aTestSensorsFans
uTestSensorsFans.test_emulate_data
aTestProcess
test_parse_smaps_vs_memory_maps
uTestProcess.test_parse_smaps_vs_memory_maps
test_parse_smaps_mocked
uTestProcess.test_parse_smaps_mocked
test_open_files_mode
uTestProcess.test_open_files_mode
test_open_files_file_gone
uTestProcess.test_open_files_file_gone
test_open_files_fd_gone
uTestProcess.test_open_files_fd_gone
test_open_files_enametoolong
uTestProcess.test_open_files_enametoolong
test_terminal_mocked
uTestProcess.test_terminal_mocked
test_cmdline_mocked
uTestProcess.test_cmdline_mocked
test_cmdline_spaces_mocked
uTestProcess.test_cmdline_spaces_mocked
test_cmdline_mixed_separators
uTestProcess.test_cmdline_mixed_separators
test_readlink_path_deleted_mocked
uTestProcess.test_readlink_path_deleted_mocked
test_threads_mocked
uTestProcess.test_threads_mocked
test_exe_mocked
uTestProcess.test_exe_mocked
test_cwd_mocked
uTestProcess.test_cwd_mocked
test_issue_1014
uTestProcess.test_issue_1014
test_issue_2418
uTestProcess.test_issue_2418
test_rlimit_zombie
uTestProcess.test_rlimit_zombie
test_stat_file_parsing
uTestProcess.test_stat_file_parsing
test_status_file_parsing
uTestProcess.test_status_file_parsing
test_net_connections_enametoolong
uTestProcess.test_net_connections_enametoolong
test_create_time_monotonic
uTestProcess.test_create_time_monotonic
aTestProcessAgainstStatus
classmethod
setUpClass
uTestProcessAgainstStatus.setUpClass
uTestProcessAgainstStatus.read_status_file
test_name
uTestProcessAgainstStatus.test_name
test_status
uTestProcessAgainstStatus.test_status
test_ppid
uTestProcessAgainstStatus.test_ppid
test_num_threads
uTestProcessAgainstStatus.test_num_threads
test_uids
uTestProcessAgainstStatus.test_uids
test_gids
uTestProcessAgainstStatus.test_gids
test_num_ctx_switches
uTestProcessAgainstStatus.test_num_ctx_switches
test_cpu_affinity
uTestProcessAgainstStatus.test_cpu_affinity
test_cpu_affinity_eligible_cpus
uTestProcessAgainstStatus.test_cpu_affinity_eligible_cpus
aTestUtils
test_readlink
uTestUtils.test_readlink
upsutil\tests\test_linux.py
T a.0
wxT wxT wpafiles
T afiles
wpu<module psutil.tests.test_linux>
T a__class__
T apath
out
lines
line
dev
total
used
free
T apath
T aout
lines
line
total
used
free
shared
nt
T aout
lines
line
w_atotal
used
free
nt
T aout
T aifname
fcntl
wsT
ifname
wfaall_fields
line
fields
wiaunformatted
groups
formatted
packed
T aifname
fcntl
wsainfo
T afname
wpagiveup_at
file
T anic
ret
out
T wfadata
T apairs
open_mock
orig_open
wmT afor_path
exc
open_mock
orig_open
wmT aname
args
kwargs
orig_open
T aorig_open
T aname
args
kwargs
wnaorig_open
T aname
args
kwargs
content
pairs
orig_open
T aorig_open
pairs
T aname
args
kwargs
for_path
exc
orig_open
T aexc
for_path
orig_open
T apath
os_path_exists
T aos_path_exists
T apath
orig_exists
T aorig_exists
T aself
linestart
wfaline
value
T aself
dev
T acls
T aself
vmstat_value
psutil_value
T aself
df
part
usage
w_atotal
used
free
T aself
psutil_value
findmnt_value
T aself
ifconfig
nio
name
stats
ifconfig_ret
T aself
name
stats
out
T aself
out
core_ids
line
fields
T aself
out
num
T aself
num
T aself
ls
count
T aself
wfavalue
T aself
content
wmaws
ret
wwT aself
content
ws
ret
wwT aself
mems
wfaline
fields
wawbadiff_percent
T aself
out
lines
free_value
psutil_value
T aself
wmT aself
finder
T aself
wpafake_file
wmT aself
finder
wawbwcabase
T aself
value
min_
max_
T aself
value
wmT aself
content
wmacpu_percent
cpu_percent_percpu
cpu_times_percent
cpu_times_percent_percpu
T aself
wpT aself
wmaret
T aself
wmapart
T aself
open_mock
orig_open
temp
T aself
open_mock
glob_mock
orig_open
temp
T aself
open_mock
orig_open
fan
T aself
open_mock
orig_open
freq
T aself
T aself
content
ret
is_storage_device
T aself
psutil
original
wmwfacpuinfo_data
fake_file
T aself
content
ret
T aself
supports_ipv6
inet_ntop
wsT aself
ret
T aself
m1
m2
T aself
exists
T aself
open_mock
orig_open
wmT aself
content
wmT aself
path_exists_mock
os_path_exists
ret
freq
T aself
path_exists_mock
orig_exists
T aself
exists
wprocfs
wsysfs
T aself
fields
kernel_ver
kernel_ver_info
T aself
matches_found
name
stats
out
match
ifconfig_flags
psutil_flags
T aself
free_value
psutil_value
T aself
cli_value
psutil_value
T aself
psutil_value
wfaproc_value
T aself
value
T aself
name
addrs
addr
address
T aself
wmwpT aself
wpanthreads
threads
tid
pt
T aself
open_mock
orig_open
mlistdir
mopen
T aself
wmaswap
cext
w_atotal
free
unit_multiplier
T aself
meth_1
wmameth_2
T aself
wmaws
ret
wwT aself
name
stats
wfT aself
my_procfs
wfaorig_open
open_mock
per_cpu_percent
per_cpu_times_percent
T aself
wpafiles
patch_point
wmT aself
wpafiles
wmT aself
get_test_file
testfn
T aself
content
wmwpauss
pss
swap
T aself
sproc
uss
pss
swap
maps
T aself
out
acpi_value
psutil_value
T aself
tdir
T aself
m1
m2
wpacm
T aself
free
free_value
psutil_value
T aself
args
content
wpacpu
T aself
content
wpauids
gids
T aself
open_mock_1
orig_open
wmaret
open_mock_2
T aself
user
T aself
content
wmamem
T aself
wfadata
part
fake_file
m1
m2
ret
T astat
out
line
.psutil.tests.test_memleaks
5$
decorator
ufewtimes_if_linux.<locals>.decorator
wraps
wrapper
ufewtimes_if_linux.<locals>.decorator.<locals>.wrapper
aLINUX
times
aFEW_TIMES
fun
process_namespace
T natest_class_coverage
getters
setters
execute
proc
name
cmdline
exe
ppid
uids
gids
status
nice
thisproc
u<lambda>
uTestProcessObjectLeaks.test_nice_set.<locals>.<lambda>
self
niceness
ionice
aWINDOWS
uTestProcessObjectLeaks.test_ionice_set.<locals>.<lambda>
partial
cext
proc_ioprio_set
getpid
q l
execute_w_exc
value
psutil
aIOPRIO_CLASS_NONE
io_counters
aProcess
username
create_time
num_threads
num_handles
num_fds
num_ctx_switches
threads
cpu_times
cpu_num
memory_info
memory_full_info
terminal
aPOSIX
resume
T atimes
cwd
cpu_affinity
uTestProcessObjectLeaks.test_cpu_affinity_set.<locals>.<lambda>
affinity
get_testfn
wwa__enter__
a__exit__
open_files
T nnnamemory_maps
uTestProcessObjectLeaks.test_rlimit.<locals>.<lambda>
rlimit
aRLIMIT_NOFILE
uTestProcessObjectLeaks.test_rlimit_set.<locals>.<lambda>
T EOSError
EValueError
limit
T q acreate_sockets
aSUNOS
inet
all
uTestProcessObjectLeaks.test_net_connections.<locals>.<lambda>
net_connections
kind
environ
uTestProcessObjectLeaks.test_proc_info.<locals>.<lambda>
proc_info
a__class__
setUpClass
spawn_subproc
subp
pid
kill
wait
tearDownClass
terminate
aNoSuchProcess
suspend
call
uTestTerminatedProcessLeaks.test_proc_info.<locals>.call
uTestProcessDualImplementation.test_cmdline_peb_true.<locals>.<lambda>
proc_cmdline
D ause_peb
tuTestProcessDualImplementation.test_cmdline_peb_false.<locals>.<lambda>
D ause_peb
Fasystem_namespace
uTestModuleFunctionsLeaks.test_cpu_count.<locals>.<lambda>
cpu_count
T tT alogical
uTestModuleFunctionsLeaks.test_cpu_count_cores.<locals>.<lambda>
T FuTestModuleFunctionsLeaks.test_per_cpu_times.<locals>.<lambda>
T apercpu
cpu_stats
cpu_freq
getloadavg
virtual_memory
swap_memory
uTestModuleFunctionsLeaks.test_pid_exists.<locals>.<lambda>
pid_exists
uTestModuleFunctionsLeaks.test_disk_usage.<locals>.<lambda>
disk_usage
T w.adisk_partitions
uTestModuleFunctionsLeaks.test_disk_io_counters.<locals>.<lambda>
disk_io_counters
T anowrap
pids
uTestModuleFunctionsLeaks.test_net_io_counters.<locals>.<lambda>
net_io_counters
T aall
T akind
uTestModuleFunctionsLeaks.test_net_connections.<locals>.<lambda>
l   atolerance
net_if_addrs
T atolerance
net_if_stats
sensors_battery
sensors_temperatures
sensors_fans
boot_time
users
uTestModuleFunctionsLeaks.test_set_debug.<locals>.<lambda>
a_set_debug
winservice_enumerate
win_service_iter
uTestModuleFunctionsLeaks.test_win_service_get_config.<locals>.<lambda>
winservice_query_config
uTestModuleFunctionsLeaks.test_win_service_get_status.<locals>.<lambda>
winservice_query_status
uTestModuleFunctionsLeaks.test_win_service_get_description.<locals>.<lambda>
winservice_query_descr
a__doc__
a__file__
a__spec__
origin
has_location
a__cached__
functools
os
T aLINUX
T aMACOS
aMACOS
T aOPENBSD
aOPENBSD
T aPOSIX
T aSUNOS
T aWINDOWS
upsutil.tests
T aAARCH64
aAARCH64
T aHAS_CPU_AFFINITY
aHAS_CPU_AFFINITY
T aHAS_CPU_FREQ
aHAS_CPU_FREQ
T aHAS_ENVIRON
aHAS_ENVIRON
T aHAS_IONICE
aHAS_IONICE
T aHAS_MEMORY_MAPS
aHAS_MEMORY_MAPS
T aHAS_NET_IO_COUNTERS
aHAS_NET_IO_COUNTERS
T aHAS_PROC_CPU_NUM
aHAS_PROC_CPU_NUM
T aHAS_PROC_IO_COUNTERS
aHAS_PROC_IO_COUNTERS
T aHAS_RLIMIT
aHAS_RLIMIT
T aHAS_SENSORS_BATTERY
aHAS_SENSORS_BATTERY
T aHAS_SENSORS_FANS
aHAS_SENSORS_FANS
T aHAS_SENSORS_TEMPERATURES
aHAS_SENSORS_TEMPERATURES
T aTestMemoryLeak
aTestMemoryLeak
T acreate_sockets
T aget_testfn
T aprocess_namespace
T apytest
pytest
T askip_on_access_denied
skip_on_access_denied
T aspawn_subproc
T asystem_namespace
T aterminate
a_psplatform
l afewtimes_if_linux
a__prepare__
aTestProcessObjectLeaks
a__getitem__
u%s.__prepare__() must return a mapping, not %s
a__name__
u<metaclass>
