# Reconstructed from integrated Nuitka blob
# Module: l ucustomtkinter.windows.widgets.scaling.scaling_base_class

aCTkScalingBaseClass
a__qualname__
T awidget
a__init__
uCTkScalingBaseClass.__init__
destroy
uCTkScalingBaseClass.destroy
uCTkScalingBaseClass._set_scaling
a_get_widget_scaling
uCTkScalingBaseClass._get_widget_scaling
a_get_window_scaling
uCTkScalingBaseClass._get_window_scaling
uCTkScalingBaseClass._apply_widget_scaling
a_reverse_widget_scaling
uCTkScalingBaseClass._reverse_widget_scaling
a_apply_window_scaling
uCTkScalingBaseClass._apply_window_scaling
a_reverse_window_scaling
uCTkScalingBaseClass._reverse_window_scaling
a_apply_font_scaling
uCTkScalingBaseClass._apply_font_scaling
a_apply_argument_scaling
uCTkScalingBaseClass._apply_argument_scaling
uCTkScalingBaseClass._parse_geometry_string
a_apply_geometry_scaling
uCTkScalingBaseClass._apply_geometry_scaling
a_reverse_geometry_scaling
uCTkScalingBaseClass._reverse_geometry_scaling
ucustomtkinter\windows\widgets\scaling\scaling_base_class.py
u<module customtkinter.windows.widgets.scaling.scaling_base_class>
T aself
scaling_type
T aself
kwargs
scaled_kwargs
T aself
font
T aself
geometry_string
width
height
wxwyT aself
value
T aself
T ageometry_string
result
width
height
wxwyT aself
scaled_geometry_string
width
height
wxwyT aself
scaled_value
T aself
new_widget_scaling
new_window_scaling
.customtkinter.windows.widgets.scaling.scaling_tracker
h
get_window_root_of_widget
window_dpi_scaling_dict
widget_scaling
window_scaling
max
f       ?aupdate_scaling_callbacks_all
current_widget
tkinter
aTk
aToplevel
master
window_widgets_dict
items
utoo many values to unpack (expected 2)
cls
deactivate_automatic_dpi_awareness
append
get_window_dpi_scaling
update_loop_running
after
ldacheck_dpi_scaling
remove
windll
shcore
aSetProcessDpiAwareness
T l l
pointer
aHWND
winfo_id
user32
aMonitorFromWindow
aDWORD
aUINT
aGetDpiForMonitor
value
l  l awinfo_exists
state
iconic
attributes
T u-alpha
f333333 ?ablock_update_dimensions_event
update_scaling_callbacks_for_window
unblock_update_dimensions_event
T u-alpha
l akeys
new_scaling_detected
loop_pause_after_new_scaling
update_loop_interval
a__doc__
a__file__
a__spec__
origin
has_location
a__cached__
sys
aCallable
