# Reconstructed from integrated Nuitka blob
# Module: ucryptography.x509.certificate_transparency

a__qualname__
aX509_CERTIFICATE
l aPRE_CERTIFICATE
a__orig_bases__
aVersion
v1
aSignatureAlgorithm
aANONYMOUS
aRSA
l aDSA
l aECDSA
aSct
aSignedCertificateTimestamp
ucryptography\x509\certificate_transparency.py
u<module cryptography.x509.certificate_transparency>
T a__class__

.cryptography.x509
a__doc__
a__file__
path
dirname
join
environ
get
T aNUITKA_PACKAGE_cryptography
u\not_existing
x509
T aNUITKA_PACKAGE_cryptography_x509
u\not_existing
a__path__
a__spec__
origin
has_location
submodule_search_locations
a__cached__
annotations
ucryptography.x509
T acertificate_transparency
verification
l
certificate_transparency
verification
ucryptography.x509.base
T aAttribute
aAttributeNotFound
aAttributes
aCertificate
aCertificateBuilder
aCertificateRevocationList
aCertificateRevocationListBuilder
aCertificateSigningRequest
aCertificateSigningRequestBuilder
aInvalidVersion
aRevokedCertificate
aRevokedCertificateBuilder
aVersion
load_der_x509_certificate
load_der_x509_crl
load_der_x509_csr
load_pem_x509_certificate
load_pem_x509_certificates
load_pem_x509_crl
load_pem_x509_csr
random_serial_number
aAttribute
aAttributeNotFound
aAttributes
aCertificate
aCertificateBuilder
aCertificateRevocationList
aCertificateRevocationListBuilder
aCertificateSigningRequest
aCertificateSigningRequestBuilder
aInvalidVersion
aRevokedCertificate
aRevokedCertificateBuilder
aVersion
load_der_x509_certificate
load_der_x509_crl
load_der_x509_csr
load_pem_x509_certificate
load_pem_x509_certificates
load_pem_x509_crl
load_pem_x509_csr
random_serial_number
ucryptography.x509.extensions
T0aAccessDescription
aAdmission
aAdmissions
aAuthorityInformationAccess
aAuthorityKeyIdentifier
aBasicConstraints
aCertificateIssuer
aCertificatePolicies
aCRLDistributionPoints
aCRLNumber
aCRLReason
aDeltaCRLIndicator
aDistributionPoint
aDuplicateExtension
aExtendedKeyUsage
aExtension
aExtensionNotFound
aExtensions
aExtensionType
aFreshestCRL
aGeneralNames
aInhibitAnyPolicy
aInvalidityDate
aIssuerAlternativeName
aIssuingDistributionPoint
aKeyUsage
aMSCertificateTemplate
aNameConstraints
aNamingAuthority
aNoticeReference
aOCSPAcceptableResponses
aOCSPNoCheck
aOCSPNonce
aPolicyConstraints
aPolicyInformation
aPrecertificateSignedCertificateTimestamps
aPrecertPoison
aPrivateKeyUsagePeriod
aProfessionInfo
aReasonFlags
aSignedCertificateTimestamps
aSubjectAlternativeName
aSubjectInformationAccess
aSubjectKeyIdentifier
aTLSFeature
aTLSFeatureType
aUnrecognizedExtension
aUserNotice
aAccessDescription
aAdmission
aAdmissions
aAuthorityInformationAccess
aAuthorityKeyIdentifier
aBasicConstraints
aCertificateIssuer
aCertificatePolicies
aCRLDistributionPoints
aCRLNumber
aCRLReason
aDeltaCRLIndicator
aDistributionPoint
aDuplicateExtension
aExtendedKeyUsage
aExtension
aExtensionNotFound
aExtensions
aExtensionType
aFreshestCRL
aGeneralNames
aInhibitAnyPolicy
aInvalidityDate
aIssuerAlternativeName
aIssuingDistributionPoint
aKeyUsage
aMSCertificateTemplate
aNameConstraints
aNamingAuthority
aNoticeReference
aOCSPAcceptableResponses
aOCSPNoCheck
aOCSPNonce
aPolicyConstraints
aPolicyInformation
aPrecertificateSignedCertificateTimestamps
aPrecertPoison
aPrivateKeyUsagePeriod
aProfessionInfo
aReasonFlags
aSignedCertificateTimestamps
aSubjectAlternativeName
aSubjectInformationAccess
aSubjectKeyIdentifier
aTLSFeature
aTLSFeatureType
aUnrecognizedExtension
aUserNotice
ucryptography.x509.general_name
T	aDirectoryName
aDNSName
aGeneralName
aIPAddress
aOtherName
aRegisteredID
aRFC822Name
aUniformResourceIdentifier
aUnsupportedGeneralNameType
aDirectoryName
aDNSName
aGeneralName
aIPAddress
aOtherName
aRegisteredID
aRFC822Name
aUniformResourceIdentifier
aUnsupportedGeneralNameType
ucryptography.x509.name
T aName
aNameAttribute
aRelativeDistinguishedName
aName
aNameAttribute
aRelativeDistinguishedName
ucryptography.x509.oid
T	aAuthorityInformationAccessOID
aCertificatePoliciesOID
aCRLEntryExtensionOID
aExtendedKeyUsageOID
aExtensionOID
aNameOID
aObjectIdentifier
aPublicKeyAlgorithmOID
aSignatureAlgorithmOID
aAuthorityInformationAccessOID
aCertificatePoliciesOID
aCRLEntryExtensionOID
aExtendedKeyUsageOID
aExtensionOID
aNameOID
aObjectIdentifier
aPublicKeyAlgorithmOID
aSignatureAlgorithmOID
aAUTHORITY_INFORMATION_ACCESS
aOID_AUTHORITY_INFORMATION_ACCESS
aAUTHORITY_KEY_IDENTIFIER
aOID_AUTHORITY_KEY_IDENTIFIER
aBASIC_CONSTRAINTS
aOID_BASIC_CONSTRAINTS
aCERTIFICATE_POLICIES
aOID_CERTIFICATE_POLICIES
aCRL_DISTRIBUTION_POINTS
aOID_CRL_DISTRIBUTION_POINTS
aEXTENDED_KEY_USAGE
aOID_EXTENDED_KEY_USAGE
aFRESHEST_CRL
aOID_FRESHEST_CRL
aINHIBIT_ANY_POLICY
aOID_INHIBIT_ANY_POLICY
aISSUER_ALTERNATIVE_NAME
aOID_ISSUER_ALTERNATIVE_NAME
aKEY_USAGE
aOID_KEY_USAGE
aPRIVATE_KEY_USAGE_PERIOD
aOID_PRIVATE_KEY_USAGE_PERIOD
aNAME_CONSTRAINTS
aOID_NAME_CONSTRAINTS
aOCSP_NO_CHECK
aOID_OCSP_NO_CHECK
aPOLICY_CONSTRAINTS
aOID_POLICY_CONSTRAINTS
aPOLICY_MAPPINGS
aOID_POLICY_MAPPINGS
aSUBJECT_ALTERNATIVE_NAME
aOID_SUBJECT_ALTERNATIVE_NAME
aSUBJECT_DIRECTORY_ATTRIBUTES
aOID_SUBJECT_DIRECTORY_ATTRIBUTES
aSUBJECT_INFORMATION_ACCESS
aOID_SUBJECT_INFORMATION_ACCESS
aSUBJECT_KEY_IDENTIFIER
aOID_SUBJECT_KEY_IDENTIFIER
aDSA_WITH_SHA1
aOID_DSA_WITH_SHA1
aDSA_WITH_SHA224
aOID_DSA_WITH_SHA224
aDSA_WITH_SHA256
aOID_DSA_WITH_SHA256
aECDSA_WITH_SHA1
aOID_ECDSA_WITH_SHA1
aECDSA_WITH_SHA224
aOID_ECDSA_WITH_SHA224
aECDSA_WITH_SHA256
aOID_ECDSA_WITH_SHA256
aECDSA_WITH_SHA384
aOID_ECDSA_WITH_SHA384
aECDSA_WITH_SHA512
aOID_ECDSA_WITH_SHA512
aRSA_WITH_MD5
aOID_RSA_WITH_MD5
aRSA_WITH_SHA1
aOID_RSA_WITH_SHA1
aRSA_WITH_SHA224
aOID_RSA_WITH_SHA224
aRSA_WITH_SHA256
aOID_RSA_WITH_SHA256
aRSA_WITH_SHA384
aOID_RSA_WITH_SHA384
aRSA_WITH_SHA512
aOID_RSA_WITH_SHA512
aRSASSA_PSS
aOID_RSASSA_PSS
aCOMMON_NAME
aOID_COMMON_NAME
aCOUNTRY_NAME
aOID_COUNTRY_NAME
aDOMAIN_COMPONENT
aOID_DOMAIN_COMPONENT
aDN_QUALIFIER
aOID_DN_QUALIFIER
aEMAIL_ADDRESS
aOID_EMAIL_ADDRESS
aGENERATION_QUALIFIER
aOID_GENERATION_QUALIFIER
aGIVEN_NAME
aOID_GIVEN_NAME
aLOCALITY_NAME
aOID_LOCALITY_NAME
aORGANIZATIONAL_UNIT_NAME
aOID_ORGANIZATIONAL_UNIT_NAME
aORGANIZATION_NAME
aOID_ORGANIZATION_NAME
aPSEUDONYM
aOID_PSEUDONYM
aSERIAL_NUMBER
aOID_SERIAL_NUMBER
aSTATE_OR_PROVINCE_NAME
aOID_STATE_OR_PROVINCE_NAME
aSURNAME
aOID_SURNAME
aTITLE
aOID_TITLE
aCLIENT_AUTH
aOID_CLIENT_AUTH
aCODE_SIGNING
aOID_CODE_SIGNING
aEMAIL_PROTECTION
aOID_EMAIL_PROTECTION
aOCSP_SIGNING
aOID_OCSP_SIGNING
aSERVER_AUTH
aOID_SERVER_AUTH
aTIME_STAMPING
aOID_TIME_STAMPING
aANY_POLICY
aOID_ANY_POLICY
aCPS_QUALIFIER
aOID_CPS_QUALIFIER
aCPS_USER_NOTICE
aOID_CPS_USER_NOTICE
aCERTIFICATE_ISSUER
aOID_CERTIFICATE_ISSUER
aCRL_REASON
aOID_CRL_REASON
aINVALIDITY_DATE
aOID_INVALIDITY_DATE
aCA_ISSUERS
aOID_CA_ISSUERS
aOCSP
aOID_OCSP
LZaOID_CA_ISSUERS
aOID_OCSP
aAccessDescription
aAdmission
aAdmissions
aAttribute
aAttributeNotFound
aAttributes
aAuthorityInformationAccess
aAuthorityKeyIdentifier
aBasicConstraints
aCRLDistributionPoints
aCRLNumber
aCRLReason
aCertificate
aCertificateBuilder
aCertificateIssuer
aCertificatePolicies
aCertificateRevocationList
aCertificateRevocationListBuilder
aCertificateSigningRequest
aCertificateSigningRequestBuilder
aDNSName
aDeltaCRLIndicator
aDirectoryName
aDistributionPoint
aDuplicateExtension
aExtendedKeyUsage
aExtension
aExtensionNotFound
aExtensionType
aExtensions
aFreshestCRL
aGeneralName
aGeneralNames
aIPAddress
aInhibitAnyPolicy
aInvalidVersion
aInvalidityDate
aIssuerAlternativeName
aIssuingDistributionPoint
aKeyUsage
aMSCertificateTemplate
aName
aNameAttribute
aNameConstraints
aNameOID
aNamingAuthority
aNoticeReference
aOCSPAcceptableResponses
aOCSPNoCheck
aOCSPNonce
aObjectIdentifier
aOtherName
aPolicyConstraints
aPolicyInformation
aPrecertPoison
aPrecertificateSignedCertificateTimestamps
aPrivateKeyUsagePeriod
aProfessionInfo
aPublicKeyAlgorithmOID
aRFC822Name
aReasonFlags
aRegisteredID
aRelativeDistinguishedName
aRevokedCertificate
aRevokedCertificateBuilder
aSignatureAlgorithmOID
aSignedCertificateTimestamps
aSubjectAlternativeName
aSubjectInformationAccess
aSubjectKeyIdentifier
aTLSFeature
aTLSFeatureType
aUniformResourceIdentifier
aUnrecognizedExtension
aUnsupportedGeneralNameType
aUserNotice
aVersion
certificate_transparency
load_der_x509_certificate
load_der_x509_crl
load_der_x509_csr
load_pem_x509_certificate
load_pem_x509_certificates
load_pem_x509_crl
load_pem_x509_csr
random_serial_number
verification
verification
a__all__
ucryptography\x509\__init__.py
u<module cryptography.x509>

.cryptography.x509.extensions
sa
aRSAPublicKey
public_bytes
serialization
aEncoding
aDER
aPublicFormat
aPKCS1
aEllipticCurvePublicKey
aX962
aUncompressedPoint
aSubjectPublicKeyInfo
asn1
parse_spki_for_data
hashlib
sha1
digest
len_method
u_make_sequence_methods.<locals>.len_method
iter_method
u_make_sequence_methods.<locals>.iter_method
getitem_method
u_make_sequence_methods.<locals>.getitem_method
field_name
a__class__
a__init__
oid
upublic_bytes is not implemented for extension type

a_extensions
aExtensionNotFound
uNo
u extension was found
aUnrecognizedExtension
uUnrecognizedExtension can't be used with get_extension_for_class because more than one instance of the class may be present.
value
u<Extensions(
u)>
ucrl_number must be an integer
a_crl_number
aCRLNumber
crl_number
u<CRLNumber(
rust_x509
encode_extension_value
uauthority_cert_issuer and authority_cert_serial_number must both be present or both None
uauthority_cert_issuer must be a list of GeneralName objects
uauthority_cert_serial_number must be an integer
a_key_identifier
authority_cert_issuer
a_authority_cert_issuer
a_authority_cert_serial_number
aGeneralName
u<genexpr>
uAuthorityKeyIdentifier.__init__.<locals>.<genexpr>
a_key_identifier_from_public_key
T akey_identifier
authority_cert_issuer
authority_cert_serial_number
u<AuthorityKeyIdentifier(key_identifier=
key_identifier
u, authority_cert_issuer=
u, authority_cert_serial_number=
authority_cert_serial_number
aAuthorityKeyIdentifier
a_digest
u<SubjectKeyIdentifier(digest=
aSubjectKeyIdentifier
constant_time
bytes_eq
uEvery item in the descriptions list must be an AccessDescription
a_descriptions
aAccessDescription
uAuthorityInformationAccess.__init__.<locals>.<genexpr>
u<AuthorityInformationAccess(
aAuthorityInformationAccess
uSubjectInformationAccess.__init__.<locals>.<genexpr>
u<SubjectInformationAccess(
aSubjectInformationAccess
aObjectIdentifier
uaccess_method must be an ObjectIdentifier
uaccess_location must be a GeneralName
a_access_method
a_access_location
u<AccessDescription(access_method=
access_method
u, access_location=
access_location
uca must be a boolean value
upath_length must be None when ca is False
l
upath_length must be a non-negative integer or None
a_ca
a_path_length
u<BasicConstraints(ca=
ca
u, path_length=
path_length
aBasicConstraints
aDeltaCRLIndicator
u<DeltaCRLIndicator(crl_number=
udistribution_points must be a list of DistributionPoint objects
a_distribution_points
aDistributionPoint
uCRLDistributionPoints.__init__.<locals>.<genexpr>
u<CRLDistributionPoints(
aCRLDistributionPoints
uFreshestCRL.__init__.<locals>.<genexpr>
u<FreshestCRL(
aFreshestCRL
uYou cannot provide both full_name and relative_name, at least one must be None.
uEither full_name, relative_name or crl_issuer must be provided.
ufull_name must be a list of GeneralName objects
aRelativeDistinguishedName
urelative_name must be a RelativeDistinguishedName
ucrl_issuer must be None or a list of general names
ureasons must be None or frozenset of ReasonFlags
aReasonFlags
unspecified
remove_from_crl
uunspecified and remove_from_crl are not valid reasons in a DistributionPoint
full_name
a_full_name
a_relative_name
a_reasons
crl_issuer
a_crl_issuer
uDistributionPoint.__init__.<locals>.<genexpr>
u<DistributionPoint(full_name={0.full_name}, relative_name={0.relative_name}, reasons={0.reasons}, crl_issuer={0.crl_issuer})>
relative_name
reasons
urequire_explicit_policy must be a non-negative integer or None
uinhibit_policy_mapping must be a non-negative integer or None
uAt least one of require_explicit_policy and inhibit_policy_mapping must not be None
a_require_explicit_policy
a_inhibit_policy_mapping
u<PolicyConstraints(require_explicit_policy={0.require_explicit_policy}, inhibit_policy_mapping={0.inhibit_policy_mapping})>
aPolicyConstraints
require_explicit_policy
inhibit_policy_mapping
uEvery item in the policies list must be a PolicyInformation
a_policies
aPolicyInformation
uCertificatePolicies.__init__.<locals>.<genexpr>
u<CertificatePolicies(
aCertificatePolicies
upolicy_identifier must be an ObjectIdentifier
a_policy_identifier
upolicy_qualifiers must be a list of strings and/or UserNotice objects or None
policy_qualifiers
a_policy_qualifiers
aUserNotice
uPolicyInformation.__init__.<locals>.<genexpr>
u<PolicyInformation(policy_identifier=
policy_identifier
u, policy_qualifiers=
aNoticeReference
unotice_reference must be None or a NoticeReference
a_notice_reference
a_explicit_text
u<UserNotice(notice_reference=
notice_reference
u, explicit_text=
explicit_text
a_organization
unotice_numbers must be a list of integers
a_notice_numbers
uNoticeReference.__init__.<locals>.<genexpr>
u<NoticeReference(organization=
organization
u, notice_numbers=
notice_numbers
uEvery item in the usages list must be an ObjectIdentifier
a_usages
uExtendedKeyUsage.__init__.<locals>.<genexpr>
u<ExtendedKeyUsage(
aExtendedKeyUsage
aOCSPNoCheck
aPrecertPoison
ufeatures must be a list of elements from the TLSFeatureType enum
a_features
aTLSFeatureType
uTLSFeature.__init__.<locals>.<genexpr>
u<TLSFeature(features=
aTLSFeature
uskip_certs must be an integer
uskip_certs must be a non-negative integer
a_skip_certs
u<InhibitAnyPolicy(skip_certs=
skip_certs
aInhibitAnyPolicy
uencipher_only and decipher_only can only be true when key_agreement is true
a_digital_signature
a_content_commitment
a_key_encipherment
a_data_encipherment
a_key_agreement
a_key_cert_sign
a_crl_sign
a_encipher_only
a_decipher_only
key_agreement
uencipher_only is undefined unless key_agreement is true
udecipher_only is undefined unless key_agreement is true
encipher_only
decipher_only
u<KeyUsage(digital_signature=
digital_signature
u, content_commitment=
content_commitment
u, key_encipherment=
key_encipherment
u, data_encipherment=
data_encipherment
u, key_agreement=
u, key_cert_sign=
key_cert_sign
u, crl_sign=
crl_sign
u, encipher_only=
u, decipher_only=
aKeyUsage
datetime
unot_before must be a datetime.datetime or None
unot_after must be a datetime.datetime or None
uAt least one of not_before and not_after must not be None
unot_before must be before not_after
a_not_before
a_not_after
u<PrivateKeyUsagePeriod(not_before=
not_before
u, not_after=
not_after
aPrivateKeyUsagePeriod
upermitted_subtrees must be a non-empty list or None
upermitted_subtrees must be a list of GeneralName objects or None
a_validate_tree
uexcluded_subtrees must be a non-empty list or None
uexcluded_subtrees must be a list of GeneralName objects or None
permitted_subtrees
excluded_subtrees
uAt least one of permitted_subtrees and excluded_subtrees must not be None
a_permitted_subtrees
a_excluded_subtrees
uNameConstraints.__init__.<locals>.<genexpr>
aNameConstraints
a_validate_ip_name
a_validate_dns_name
uIPAddress name constraints must be an IPv4Network or IPv6Network object
aIPAddress
ipaddress
aIPv4Network
aIPv6Network
uNameConstraints._validate_ip_name.<locals>.<genexpr>
uDNSName name constraints must not contain the '*' wildcard character
aDNSName
w*uNameConstraints._validate_dns_name.<locals>.<genexpr>
u<NameConstraints(permitted_subtrees=
u, excluded_subtrees=
uoid argument must be an ObjectIdentifier instance.
ucritical must be a boolean value
a_oid
a_critical
a_value
u<Extension(oid=
u, critical=
critical
u, value=
aExtension
uEvery item in the general_names list must be an object conforming to the GeneralName interface
a_general_names
uGeneralNames.__init__.<locals>.<genexpr>
aOtherName
type
uGeneralNames.get_values_for_type.<locals>.<genexpr>
u<GeneralNames(
aGeneralNames
get_values_for_type
u<SubjectAlternativeName(
aSubjectAlternativeName
u<IssuerAlternativeName(
aIssuerAlternativeName
u<CertificateIssuer(
aCertificateIssuer
ureason must be an element from ReasonFlags
a_reason
u<CRLReason(reason=
aCRLReason
reason
uinvalidity_date must be a datetime.datetime
a_invalidity_date
u<InvalidityDate(invalidity_date=
aInvalidityDate
invalidity_date
tzinfo
replace
timezone
utc
T atzinfo
astimezone
T atz
uEvery item in the signed_certificate_timestamps list must be a SignedCertificateTimestamp
a_signed_certificate_timestamps
aSignedCertificateTimestamp
uPrecertificateSignedCertificateTimestamps.__init__.<locals>.<genexpr>
u<PrecertificateSignedCertificateTimestamps(
aPrecertificateSignedCertificateTimestamps
uSignedCertificateTimestamps.__init__.<locals>.<genexpr>
u<SignedCertificateTimestamps(
aSignedCertificateTimestamps
unonce must be bytes
a_nonce
aOCSPNonce
nonce
u<OCSPNonce(nonce=
uAll responses must be ObjectIdentifiers
a_responses
uOCSPAcceptableResponses.__init__.<locals>.<genexpr>
aOCSPAcceptableResponses
u<OCSPAcceptableResponses(responses=
uonly_some_reasons must be None or frozenset of ReasonFlags
uunspecified and remove_from_crl are not valid reasons in an IssuingDistributionPoint
uonly_contains_user_certs, only_contains_ca_certs, indirect_crl and only_contains_attribute_certs must all be boolean.
uOnly one of the following can be set to True: only_contains_user_certs, only_contains_ca_certs, only_contains_attribute_certs
uCannot create empty extension: if only_contains_user_certs, only_contains_ca_certs, indirect_crl, and only_contains_attribute_certs are all False, then either full_name, relative_name, or only_some_reasons must have a value.
a_only_contains_user_certs
a_only_contains_ca_certs
a_indirect_crl
a_only_contains_attribute_certs
a_only_some_reasons
uIssuingDistributionPoint.__init__.<locals>.<genexpr>
u<IssuingDistributionPoint(full_name=
u, relative_name=
u, only_contains_user_certs=
only_contains_user_certs
u, only_contains_ca_certs=
only_contains_ca_certs
u, only_some_reasons=
only_some_reasons
u, indirect_crl=
indirect_crl
u, only_contains_attribute_certs=
only_contains_attribute_certs
aIssuingDistributionPoint
uoid must be an ObjectIdentifier
a_template_id
umajor_version and minor_version must be integers or None
a_major_version
a_minor_version
u<MSCertificateTemplate(template_id=
template_id
u, major_version=
major_version
u, minor_version=
minor_version
aMSCertificateTemplate
uid must be an ObjectIdentifier
uurl must be a str
utext must be a str
a_id
a_url
a_text
u<NamingAuthority(id=
id
u, url=
url
u, text=
text
aNamingAuthority
unaming_authority must be a NamingAuthority
uEvery item in the profession_items list must be a str
uEvery item in the profession_oids list must be an ObjectIdentifier
uregistration_number must be a str
uadd_profession_info must be bytes
a_naming_authority
a_profession_items
profession_oids
a_profession_oids
a_registration_number
a_add_profession_info
uProfessionInfo.__init__.<locals>.<genexpr>
u<ProfessionInfo(naming_authority=
naming_authority
u, profession_items=
profession_items
u, profession_oids=
u, registration_number=
registration_number
u, add_profession_info=
add_profession_info
aProfessionInfo
uadmission_authority must be a GeneralName
uEvery item in the profession_infos list must be a ProfessionInfo
a_admission_authority
a_profession_infos
uAdmission.__init__.<locals>.<genexpr>
u<Admission(admission_authority=
admission_authority
u, naming_authority=
u, profession_infos=
profession_infos
aAdmission
uauthority must be a GeneralName
uEvery item in the contents_of_admissions list must be an Admission
a_authority
a_admissions
uAdmissions.__init__.<locals>.<genexpr>
u<Admissions(authority=
u, admissions=
aAdmissions
authority
u<UnrecognizedExtension(oid=
a__doc__
a__file__
a__spec__
origin
has_location
a__cached__
annotations
abc
typing
ucollections.abc
T aIterable
aIterator
aIterable
aIterator
cryptography
T autils
utils
ucryptography.hazmat.bindings._rust
T aasn1
T ax509
x509
ucryptography.hazmat.primitives
T aconstant_time
serialization
ucryptography.hazmat.primitives.asymmetric.ec
T aEllipticCurvePublicKey
ucryptography.hazmat.primitives.asymmetric.rsa
T aRSAPublicKey
ucryptography.hazmat.primitives.asymmetric.types
T aCertificateIssuerPublicKeyTypes
aCertificatePublicKeyTypes
aCertificateIssuerPublicKeyTypes
aCertificatePublicKeyTypes
ucryptography.x509.certificate_transparency
T aSignedCertificateTimestamp
ucryptography.x509.general_name
T	aDirectoryName
aDNSName
aGeneralName
aIPAddress
aOtherName
aRegisteredID
aRFC822Name
aUniformResourceIdentifier
a_IPAddressTypes
aDirectoryName
aRegisteredID
aRFC822Name
aUniformResourceIdentifier
a_IPAddressTypes
ucryptography.x509.name
T aName
aRelativeDistinguishedName
aName
ucryptography.x509.oid
T aCRLEntryExtensionOID
aExtensionOID
aObjectIdentifier
aOCSPExtensionOID
aCRLEntryExtensionOID
aExtensionOID
aOCSPExtensionOID
aTypeVar
T aExtensionTypeVar
aExtensionType
tT abound
covariant
aExtensionTypeVar
a_make_sequence_methods
T EException
a__prepare__
aDuplicateExtension
a__getitem__
u%s.__prepare__() must return a mapping, not %s
a__name__
u<metaclass>
