# Reconstructed from integrated Nuitka blob
# Module: core

w.aresults
check_dir
np
executable
u-c
uimport numpy; numpy.
subprocess
check_output
linalg
fft
aCDLL
a_core
a_multiarray_tests
a__file__
test_not_exported
u._
u.tests
u.setup
aPUBLIC_MODULES
aPUBLIC_ALIASED_MODULES
aPRIVATE_BUT_PRESENT_MODULES
walk_packages
a__path__
T apath
prefix
onerror
utoo many values to unpack (expected 3)
is_unexpected
aSKIP_LIST
modnames
uFound unexpected modules:

find_unexpected_members
utest_all_modules_are_expected_2.<locals>.find_unexpected_members
T anumpy
unexpected_members
extend
uFound unexpected object(s) that look like modules: {}
import_module
a__all__
startswith
T w_amod_name
aModuleType
aSKIP_LIST_2
members
check_importable
utest_api_importable.<locals>.check_importable
module_names
uModules in the public API that cannot be imported: {}
module_name
T M Omemoryview
strip
T c
T u
u<string>
eval
uModules in the public API that were not found: {}
warnings
catch_warnings
T tT arecord
a__enter__
a__exit__
filterwarnings
aDeprecationWarning
T aalways
T acategory
aImportWarning
T nnnuModules that are not really public but looked public and can not be imported: {}
T EImportError
EAttributeError
get_path
T aplatlib
aEntryPoints
aEntryPoint
accelerate
uaccelerate.commands.accelerate_cli:main
console_scripts
T aname
value
group
uaccelerate-config
uaccelerate.commands.config:main
uaccelerate-estimate-memory
uaccelerate.commands.estimate:main
uaccelerate-launch
uaccelerate.commands.launch:main
uaccelerate-merge-weights
uaccelerate.commands.merge:main
anyio
uanyio.pytest_plugin
pytest11
bottle
ubottle:main
cffi_modules
ucffi.setuptools_ext:cffi_modules
udistutils.setup_keywords
normalizer
ucharset_normalizer.cli:cli_detect
clear_comtypes_cache
ucomtypes.clear_cache:main
udatasets-cli
udatasets.commands.datasets_cli:main
distro
udistro.distro:main
fastapi
ufastapi.cli:main
flask
uflask.cli:main
futurize
ulibfuturize.main:main
pasteurize
ulibpasteurize.main:main
httpx
uhttpx:main
hf
uhuggingface_hub.cli.hf:main
uhuggingface-cli
uhuggingface_hub.commands.huggingface_cli:main
utiny-agents
uhuggingface_hub.inference._mcp.cli:app
uhuggingface_hub.HfFileSystem
ufsspec.specs
jinja2
ujinja2.ext:babel_extract[i18n]
ubabel.extractors
jsonschema
ujsonschema.cli:main
keyring
ukeyring.cli:main
ukeyring.devpi_client
devpi_client
aKWallet
ukeyring.backends.kwallet
ukeyring.backends
aSecretService
ukeyring.backends.SecretService
aWindows
ukeyring.backends.Windows
chainer
ukeyring.backends.chainer
libsecret
ukeyring.backends.libsecret
macOS
ukeyring.backends.macOS
uinstall-wheel-from-presigned
ullama_stack.cli.scripts.run:install_wheel_from_presigned
llama
ullama_stack.cli.llama:main
ullama-stack-client
ullama_stack_client.lib.cli.llama_stack_client:main
umarkdown-it
umarkdown_it.cli.parse:main
mss
umss.__main__:main
nx_loopback
unetworkx.classes.tests.dispatch_interface:backend_interface
unetworkx.backends
bdist_nuitka
unuitka.distutils.DistutilCommands:bdist_nuitka
udistutils.commands
build_nuitka
unuitka.distutils.DistutilCommands:build
install_nuitka
unuitka.distutils.DistutilCommands:install
build_with_nuitka
unuitka.distutils.DistutilCommands:setupNuitkaDistutilsCommands
numpy
array_api
uhook-dirs
unumpy:_pyinstaller_hooks_dir
pyinstaller40
f2py
unumpy.f2py.f2py2e:main
unumpy-config
unumpy._configtool:main
openai
uopenai.cli:main
contextvars_context
uopentelemetry.context.contextvars_context:ContextVarsRuntimeContext
opentelemetry_context
api
uopentelemetry.environment_variables
opentelemetry_environment_variables
default_meter_provider
uopentelemetry.metrics:NoOpMeterProvider
opentelemetry_meter_provider
baggage
uopentelemetry.baggage.propagation:W3CBaggagePropagator
opentelemetry_propagator
tracecontext
uopentelemetry.trace.propagation.tracecontext:TraceContextTextMapPropagator
default_tracer_provider
uopentelemetry.trace:NoOpTracerProvider
opentelemetry_tracer_provider
otlp_proto_http
uopentelemetry.exporter.otlp.proto.http._log_exporter:OTLPLogExporter
opentelemetry_logs_exporter
uopentelemetry.exporter.otlp.proto.http.metric_exporter:OTLPMetricExporter
opentelemetry_metrics_exporter
uopentelemetry.exporter.otlp.proto.http.trace_exporter:OTLPSpanExporter
opentelemetry_traces_exporter
sdk
uopentelemetry.sdk.environment_variables
random
uopentelemetry.sdk.trace.id_generator:RandomIdGenerator
opentelemetry_id_generator
sdk_logger_provider
uopentelemetry.sdk._logs:LoggerProvider
opentelemetry_logger_provider
console
uopentelemetry.sdk._logs.export:ConsoleLogRecordExporter
sdk_meter_provider
uopentelemetry.sdk.metrics:MeterProvider
uopentelemetry.sdk.metrics.export:ConsoleMetricExporter
host
uopentelemetry.sdk.resources:_HostResourceDetector
opentelemetry_resource_detector
os
uopentelemetry.sdk.resources:OsResourceDetector
otel
uopentelemetry.sdk.resources:OTELResourceDetector
process
uopentelemetry.sdk.resources:ProcessResourceDetector
sdk_tracer_provider
uopentelemetry.sdk.trace:TracerProvider
uopentelemetry.sdk.trace.export:ConsoleSpanExporter
always_off
uopentelemetry.sdk.trace.sampling:_AlwaysOff
opentelemetry_traces_sampler
always_on
uopentelemetry.sdk.trace.sampling:_AlwaysOn
parentbased_always_off
uopentelemetry.sdk.trace.sampling:_ParentBasedAlwaysOff
parentbased_always_on
uopentelemetry.sdk.trace.sampling:_ParentBasedAlwaysOn
parentbased_traceidratio
uopentelemetry.sdk.trace.sampling:ParentBasedTraceIdRatio
traceidratio
uopentelemetry.sdk.trace.sampling:TraceIdRatioBased
eggcacher
udirect.directscripts.eggcacher:main
pfreeze
udirect.dist.pfreeze:main
apply_patch
upanda3d_tools:apply_patch
ubam-info
upanda3d_tools:bam_info
bam2egg
upanda3d_tools:bam2egg
build_patch
upanda3d_tools:build_patch
cginfo
upanda3d_tools:cginfo
check_adler
upanda3d_tools:check_adler
check_crc
upanda3d_tools:check_crc
check_md5
upanda3d_tools:check_md5
dae2egg
upanda3d_tools:dae2egg
udeploy-stub
upanda3d_tools:deploy_stub
udeploy-stubw
upanda3d_tools:deploy_stubw
udxf-points
upanda3d_tools:dxf_points
dxf2egg
upanda3d_tools:dxf2egg
uegg-crop
upanda3d_tools:egg_crop
uegg-list-textures
upanda3d_tools:egg_list_textures
uegg-make-tube
upanda3d_tools:egg_make_tube
uegg-mkfont
upanda3d_tools:egg_mkfont
uegg-optchar
upanda3d_tools:egg_optchar
uegg-palettize
upanda3d_tools:egg_palettize
uegg-qtess
upanda3d_tools:egg_qtess
uegg-rename
upanda3d_tools:egg_rename
uegg-retarget-anim
upanda3d_tools:egg_retarget_anim
uegg-texture-cards
upanda3d_tools:egg_texture_cards
uegg-topstrip
upanda3d_tools:egg_topstrip
uegg-trans
upanda3d_tools:egg_trans
egg2bam
upanda3d_tools:egg2bam
egg2c
upanda3d_tools:egg2c
egg2dxf
upanda3d_tools:egg2dxf
egg2flt
upanda3d_tools:egg2flt
egg2maya2008
upanda3d_tools:egg2maya2008
egg2maya2009
upanda3d_tools:egg2maya2009
egg2maya2011
upanda3d_tools:egg2maya2011
egg2maya2012
upanda3d_tools:egg2maya2012
egg2maya2013
upanda3d_tools:egg2maya2013
egg2maya2014
upanda3d_tools:egg2maya2014
egg2maya2015
upanda3d_tools:egg2maya2015
egg2maya2016
upanda3d_tools:egg2maya2016
egg2maya20165
upanda3d_tools:egg2maya20165
egg2maya2017
upanda3d_tools:egg2maya2017
egg2maya2018
upanda3d_tools:egg2maya2018
egg2maya2019
upanda3d_tools:egg2maya2019
egg2maya2020
upanda3d_tools:egg2maya2020
egg2maya2022
upanda3d_tools:egg2maya2022
egg2maya85
upanda3d_tools:egg2maya85
egg2obj
upanda3d_tools:egg2obj
egg2x
upanda3d_tools:egg2x
ffmpeg
upanda3d_tools:ffmpeg
ffplay
upanda3d_tools:ffplay
ffprobe
upanda3d_tools:ffprobe
uflt-info
upanda3d_tools:flt_info
uflt-trans
upanda3d_tools:flt_trans
flt2egg
upanda3d_tools:flt2egg
fltcopy
upanda3d_tools:fltcopy
uimage-info
upanda3d_tools:image_info
uimage-resize
upanda3d_tools:image_resize
uimage-trans
upanda3d_tools:image_trans
interrogate
upanda3d_tools:interrogate
interrogate_module
upanda3d_tools:interrogate_module
ulwo-scan
upanda3d_tools:lwo_scan
lwo2egg
upanda3d_tools:lwo2egg
umake-prc-key
upanda3d_tools:make_prc_key
maya2egg2008
upanda3d_tools:maya2egg2008
maya2egg2009
upanda3d_tools:maya2egg2009
maya2egg2011
upanda3d_tools:maya2egg2011
maya2egg2012
upanda3d_tools:maya2egg2012
maya2egg2013
upanda3d_tools:maya2egg2013
maya2egg2014
upanda3d_tools:maya2egg2014
maya2egg2015
upanda3d_tools:maya2egg2015
maya2egg2016
upanda3d_tools:maya2egg2016
maya2egg20165
upanda3d_tools:maya2egg20165
maya2egg2017
upanda3d_tools:maya2egg2017
maya2egg2018
upanda3d_tools:maya2egg2018
maya2egg2019
upanda3d_tools:maya2egg2019
maya2egg2020
upanda3d_tools:maya2egg2020
maya2egg2022
upanda3d_tools:maya2egg2022
maya2egg85
upanda3d_tools:maya2egg85
mayacopy2008
upanda3d_tools:mayacopy2008
mayacopy2009
upanda3d_tools:mayacopy2009
mayacopy2011
upanda3d_tools:mayacopy2011
mayacopy2012
upanda3d_tools:mayacopy2012
mayacopy2013
upanda3d_tools:mayacopy2013
mayacopy2014
upanda3d_tools:mayacopy2014
mayacopy2015
upanda3d_tools:mayacopy2015
mayacopy2016
upanda3d_tools:mayacopy2016
mayacopy20165
upanda3d_tools:mayacopy20165
mayacopy2017
upanda3d_tools:mayacopy2017
mayacopy2018
upanda3d_tools:mayacopy2018
mayacopy2019
upanda3d_tools:mayacopy2019
mayacopy2020
upanda3d_tools:mayacopy2020
mayacopy2022
upanda3d_tools:mayacopy2022
mayacopy85
upanda3d_tools:mayacopy85
multify
upanda3d_tools:multify
obj2egg
upanda3d_tools:obj2egg
p3dcparse
upanda3d_tools:p3dcparse
parse_file
upanda3d_tools:parse_file
pdecrypt
upanda3d_tools:pdecrypt
pencrypt
upanda3d_tools:pencrypt
upfm-bba
upanda3d_tools:pfm_bba
upfm-trans
upanda3d_tools:pfm_trans
pstats
upanda3d_tools:pstats
punzip
upanda3d_tools:punzip
pview
upanda3d_tools:pview
pzip
upanda3d_tools:pzip
show_ddb
upanda3d_tools:show_ddb
test_interrogate
upanda3d_tools:test_interrogate
utext-stats
upanda3d_tools:text_stats
uvrml-trans
upanda3d_tools:vrml_trans
vrml2egg
upanda3d_tools:vrml2egg
ux-trans
upanda3d_tools:x_trans
x2egg
upanda3d_tools:x2egg
build_apps
udirect.dist.commands:build_apps
bdist_apps
udirect.dist.commands:bdist_apps
udirect.dist._dist_hooks:finalize_distribution_options
usetuptools.finalize_distribution_options
gltf2bam
ugltf.cli:main
ugltf-viewer
ugltf.viewer:main
gui_scripts
glb
ugltf._loader:GltfLoader
upanda3d.loaders
gltf
hdr2env
usimplepbr.hdr2env:main
matplotlib
upandas:plotting._matplotlib
pandas_plotting_backends
pip
upip._internal.cli.main:main
pip3
playwright
uplaywright.__main__:main
uplaywright._impl.__pyinstaller:get_hook_dirs
pyaml
upyaml.cli:main
pycookie
upycookie.main:main
upygame.__pyinstaller:get_hook_dirs
pygmentize
upygments.cmdline:main
pylupdate5
uPyQt5.pylupdate_main:main
pyrcc5
uPyQt5.pyrcc_main:main
pyuic5
uPyQt5.uic.pyuic:main
pylupdate6
uPyQt6.lupdate.pylupdate:main
pyuic6
uPyQt6.uic.pyuic:main
upyside6-assistant
uPySide6.scripts.pyside_tool:assistant
upyside6-balsam
uPySide6.scripts.pyside_tool:balsam
upyside6-balsamui
uPySide6.scripts.pyside_tool:balsamui
upyside6-deploy
uPySide6.scripts.pyside_tool:deploy
upyside6-designer
uPySide6.scripts.pyside_tool:designer
upyside6-genpyi
uPySide6.scripts.pyside_tool:genpyi
upyside6-linguist
uPySide6.scripts.pyside_tool:linguist
upyside6-lrelease
uPySide6.scripts.pyside_tool:lrelease
upyside6-lupdate
uPySide6.scripts.pyside_tool:lupdate
upyside6-metaobjectdump
uPySide6.scripts.pyside_tool:metaobjectdump
upyside6-project
uPySide6.scripts.pyside_tool:project
upyside6-qml
uPySide6.scripts.pyside_tool:qml
upyside6-qmlcachegen
uPySide6.scripts.pyside_tool:qmlcachegen
upyside6-qmlformat
uPySide6.scripts.pyside_tool:qmlformat
upyside6-qmlimportscanner
uPySide6.scripts.pyside_tool:qmlimportscanner
upyside6-qmllint
uPySide6.scripts.pyside_tool:qmllint
upyside6-qmlls
uPySide6.scripts.pyside_tool:qmlls
upyside6-qmltyperegistrar
uPySide6.scripts.pyside_tool:qmltyperegistrar
upyside6-qsb
uPySide6.scripts.pyside_tool:qsb
upyside6-qtpy2cpp
uPySide6.scripts.pyside_tool:qtpy2cpp
upyside6-rcc
uPySide6.scripts.pyside_tool:rcc
upyside6-svgtoqml
uPySide6.scripts.pyside_tool:svgtoqml
upyside6-uic
uPySide6.scripts.pyside_tool:uic
pytesseract
upytesseract.pytesseract:main
dotenv
udotenv.__main__:cli
uwebview.__pyinstaller:get_hook_dirs
pywin32_postinstall
uwin32.scripts.pywin32_postinstall:main
pywin32_testall
uwin32.scripts.pywin32_testall:main
scapy
uscapy.main:interact
alias
usetuptools.command.alias:alias
bdist_egg
usetuptools.command.bdist_egg:bdist_egg
bdist_rpm
usetuptools.command.bdist_rpm:bdist_rpm
bdist_wheel
usetuptools.command.bdist_wheel:bdist_wheel
build
usetuptools.command.build:build
build_clib
usetuptools.command.build_clib:build_clib
build_ext
usetuptools.command.build_ext:build_ext
build_py
usetuptools.command.build_py:build_py
develop
usetuptools.command.develop:develop
dist_info
usetuptools.command.dist_info:dist_info
easy_install
usetuptools.command.easy_install:easy_install
editable_wheel
usetuptools.command.editable_wheel:editable_wheel
egg_info
usetuptools.command.egg_info:egg_info
install
usetuptools.command.install:install
install_egg_info
usetuptools.command.install_egg_info:install_egg_info
install_lib
usetuptools.command.install_lib:install_lib
install_scripts
usetuptools.command.install_scripts:install_scripts
rotate
usetuptools.command.rotate:rotate
saveopts
usetuptools.command.saveopts:saveopts
sdist
usetuptools.command.sdist:sdist
setopt
usetuptools.command.setopt:setopt
test
usetuptools.command.test:test
upload_docs
usetuptools.command.upload_docs:upload_docs
dependency_links
usetuptools.dist:assert_string_list
eager_resources
entry_points
usetuptools.dist:check_entry_points
exclude_package_data
usetuptools.dist:check_package_data
extras_require
usetuptools.dist:check_extras
include_package_data
usetuptools.dist:assert_bool
install_requires
usetuptools.dist:check_requirements
namespace_packages
usetuptools.dist:check_nsp
package_data
packages
usetuptools.dist:check_packages
python_requires
usetuptools.dist:check_specifier
setup_requires
test_loader
usetuptools.dist:check_importable
test_runner
test_suite
usetuptools.dist:check_test_suite
tests_require
use_2to3
usetuptools.dist:invalid_unless_false
zip_safe
uPKG-INFO
usetuptools.command.egg_info:write_pkg_info
uegg_info.writers
udependency_links.txt
usetuptools.command.egg_info:overwrite_arg
ueager_resources.txt
uentry_points.txt
usetuptools.command.egg_info:write_entries
unamespace_packages.txt
urequires.txt
usetuptools.command.egg_info:write_requirements
utop_level.txt
usetuptools.command.egg_info:write_toplevel_names
keywords
usetuptools.dist:Distribution._finalize_setup_keywords
parent_finalize
usetuptools.dist:_Distribution.finalize_options
uspark-parser-coverage
uspark_parser.bin.parser_coverage:run
sprc
uspeech_recognition.cli:main
isympy
uisympy:main
uconvert-caffe2-to-onnx
ucaffe2.python.onnx.bin.conversion:caffe2_to_onnx
uconvert-onnx-to-caffe2
ucaffe2.python.onnx.bin.conversion:onnx_to_caffe2
torchfrtrace
utools.flight_recorder.fr_trace:main
torchrun
utorch.distributed.run:main
default
utorch.distributed.elastic.multiprocessing:DefaultLogsSpecs
utorchrun.logs_specs
tqdm
utqdm.cli:main
transformers
utransformers.commands.transformers_cli:main
utransformers-cli
utransformers.commands.transformers_cli:main_cli
trio
utrio._core._run:_hypothesis_plugin_setup
hypothesis
uncompyle6
uuncompyle6.bin.uncompile:main_bin
uuncompyle6-tokenize
uuncompyle6.bin.pydisassemble:main
uvicorn
uuvicorn.main:main
websockets
uwebsockets.cli:main
wsdump
uwebsocket._wsdump:main
pydisasm
uxdis.bin.pydisasm:main
select
T aarray_api
T agroup
get
uNo entry points for 'array_api' found
u'numpy' not in array_api entry points
value
unumpy.array_api
load
unumpy entry point value '
u' does not point to our Array API implementation
name
u<genexpr>
utest_array_api_entry_point.<locals>.<genexpr>
a_remove_private_members
utest_main_namespace_all_dir_coherence.<locals>._remove_private_members
a_remove_exceptions
utest_main_namespace_all_dir_coherence.<locals>._remove_exceptions
a__dir__
difference
S abool
unumpy.core
l
T atests
strings
unumpy.
inspect
ismodule
T a__
unumpy.core.
aAny
aCallable
aDict
aList
aSet
aTuple
unumpy._core._multiarray_umath
T a_ArrayFunctionDispatcher
a_ArrayFunctionDispatcher
modules_queue
module
unumpy._core
T af2py
ma
testing
tests
visited_modules
add
isfunction
ufunc
visited_functions
T aabsolute
arccos
arccosh
arcsin
arcsinh
arctan
arctan2
arctanh
left_shift
right_shift
conjugate
invert
remainder
divide
concatenate
power
transpose
trimcoef
T unumpy.polynomial
T aadd
equal
not_equal
greater
greater_equal
less
less_equal
unumpy.strings
unumpy.char
duplicated_functions
functions_original_paths
Tachar
core
ctypeslib
f2py
ma
lapack_lite
mrecords
testing
tests
polynomial
typing
mtrand
bit_generator
recarray
record
unumpy.rec
T	aBitGenerator
aGenerator
aMT19937
aPCG64
aPCG64DXSM
aPhilox
aRandomState
aSFC64
aSeedSequence
incorrect_entries
aFunc
actual
expected
a__qualname__
modules
reduce
getattr
split
T w.T unumpy.random
T af2py
ma
tests
testing
typing
bit_generator
ctypeslib
lapack_lite
a_check___qualname__
a__doc__
a__spec__
origin
has_location
a__cached__
functools
sys
sysconfig
pkgutil
types
importlib
unumpy.testing
T aIS_WASM
aIS_WASM
pytest
ctypes
T natest_numpy_namespace
mark
skipif
D areason
ucan't start subprocess
parametrize
testing
test_import_lazy_import
test_dir_testing
test_numpy_linalg
test_numpy_fft
D areason
uctypes not available in this python
test_NPY_NO_EXPORT
T actypeslib
dtypes
exceptions
f2py
fft
lib
ulib.array_utils
ulib.format
ulib.introspect
ulib.mixins
ulib.npyio
ulib.recfunctions
ulib.scimath
ulib.stride_tricks
linalg
ma
uma.extras
uma.mrecords
polynomial
upolynomial.chebyshev
upolynomial.hermite
upolynomial.hermite_e
upolynomial.laguerre
upolynomial.legendre
upolynomial.polynomial
random
strings
testing
utesting.overrides
typing
utyping.mypy_plugin
version
unumpy.emath
T,acompat
ucompat.py3k
conftest
core
ucore.multiarray
ucore.numeric
ucore.umath
ucore.arrayprint
ucore.defchararray
ucore.einsumfunc
ucore.fromnumeric
ucore.function_base
ucore.getlimits
ucore.numerictypes
ucore.overrides
ucore.records
ucore.shape_base
uf2py.auxfuncs
uf2py.capi_maps
uf2py.cb_rules
uf2py.cfuncs
uf2py.common_rules
uf2py.crackfortran
uf2py.diagnose
uf2py.f2py2e
uf2py.f90mod_rules
uf2py.func2subr
uf2py.rules
uf2py.symbolic
uf2py.use_rules
ufft.helper
ulib.user_array
ulinalg.lapack_lite
ulinalg.linalg
uma.core
uma.testutils
uma.timer_comparison
matlib
matrixlib
umatrixlib.defmatrix
upolynomial.polyutils
urandom.mtrand
urandom.bit_generator
utesting.print_coercion_tables
T uignore:.*np.compat.*:DeprecationWarning
test_all_modules_are_expected
L unumpy.lib.math
unumpy.matlib.char
unumpy.matlib.rec
unumpy.matlib.emath
unumpy.matlib.exceptions
unumpy.matlib.math
unumpy.matlib.linalg
unumpy.matlib.fft
unumpy.matlib.random
unumpy.matlib.ctypeslib
unumpy.matlib.ma
test_all_modules_are_expected_2
test_api_importable
xfail
get_config_var
T aPy_DEBUG
T nl
w0D areason
uNumPy possibly built with `USE_DEBUG=True ./tools/travis-test.sh`, which does not expose the `array_api` entry point. See https://github.com/numpy/numpy/pull/19800
test_array_api_entry_point
test_main_namespace_all_dir_coherence
T uignore:numpy.core(\.\w+)? is deprecated:DeprecationWarning
test_core_shims_coherence
test_functions_single_location
test___module___attribute
test___qualname___attribute
unumpy\tests\test_public_api.py
T a.0
ep
u<module numpy.tests.test_public_api>
T aobj
qualname
name
module_name
module
actual_obj
T amember_set
T amodule
module_name
results
name
item
T amodule_name
T amod_name
members
module
objnames
objname
fullobjname
T aname
T acdll
wfT amodules_queue
visited_modules
visited_functions
incorrect_entries
module
member_name
member
T amodnames
w_amodname
ispkg
T afind_unexpected_members
unexpected_members
modname
T acheck_importable
module_names
module_name
wwT anumpy_in_sitepackages
eps
xp_eps
msg
ep
xp
T acore
member_name
member
submodule
submodule_name
submodule_member_name
submodule_member
core_submodule
T avisited_modules
visited_functions
functions_original_paths
duplicated_functions
aAny
aCallable
aDict
aList
aSet
aTuple
dispatched_function
modules_queue
module
member_name
member
T aname
exe
result
T a_remove_private_members
a_remove_exceptions
all_members
dir_members
T abad_results
T aallowlist
bad_results
.numpy.tests.test_reloading
m
@
numpy
l
unumpy._globals
a_NoValue
ex
aVisibleDeprecationWarning
aModuleDeprecationWarning
assert_warns
aUserWarning
a__enter__
a__exit__
reload
T nnnaassert_
assert_raises
a_globals
l apickle
aHIGHEST_PROTOCOL
l aassert_equal
np
u<no value>
loads
dumps
T aprotocol
textwrap
dedent
T u
import sys
from pytest import warns
import numpy as np
for k in list(sys.modules.keys()):
if "numpy" in k:
del sys.modules[k]
with warns(UserWarning):
import numpy as np
subprocess
run
executable
u-c
D acapture_output
tareturncode
uNon-zero return code:


stderr
decode
a__doc__
a__file__
a__spec__
origin
has_location
a__cached__
sys
pytest
unumpy.exceptions
exceptions
unumpy.testing
T aassert_raises
assert_warns
assert_
assert_equal
aIS_WASM
aIS_WASM
test_numpy_reloading
test_novalue
mark
skipif
D areason
ucan't start subprocess
test_full_reimport
unumpy\tests\test_reloading.py
u<module numpy.tests.test_reloading>
T acode
wpT anp
proto
T anp
numpy
a_NoValue
aVisibleDeprecationWarning
aModuleDeprecationWarning
.numpy.tests.test_scripts
8
dirname
executable
endswith
T aScripts
join
f2py
aScripts
subprocess
check_output
u-v
assert_equal
strip
np
a__version__
encode
T aascii
u-mnumpy.f2py
a__doc__
a__file__
a__spec__
origin
has_location
a__cached__
sys
os
pytest
l
uos.path
T ajoin
isfile
dirname
pathjoin
isfile
numpy
unumpy.testing
T aassert_equal
aIS_WASM
aIS_WASM
u..
usetup.py
is_inplace
find_f2py_commands
mark
skipif
D areason
uCannot test f2py command inplace
xfail
T uTest is unreliable
T areason
parametrize
f2py_cmd
test_f2py
D areason
uCannot start subprocess
test_pep338
unumpy\tests\test_scripts.py
u<module numpy.tests.test_scripts>
T aexe_dir
version
major
minor
T af2py_cmd
stdout
T astdout

.numpy.tests.test_warnings
[
V
ls
ast
aNodeVisitor
generic_visit
append
attr
id
a__class__
a__init__
a_FindFuncs__filename
aParseCall
visit
func
q asimplefilter
filterwarnings
args
l
value
ignore
uwarnings should have an appropriate stacklevel; found in {} on line {}
lineno
warn
q awarnings
utesting/tests/test_warnings.py
keywords
arg
stacklevel
aPath
numpy
a__file__
parent
rglob
T u*.py
base
testing
parents
u__init__.py
random
uconftest.py
tokenize
open
a__enter__
a__exit__
parse
read
aFindFuncs
T nnna__doc__
a__spec__
origin
has_location
a__cached__
pytest
pathlib
T aPath
a__prepare__
a__getitem__
u%s.__prepare__() must return a mapping, not %s
a__name__
u<metaclass>
