# Reconstructed from integrated Nuitka blob
# Module: ukeyboard._keyboard_tests

a__qualname__
tearDown
uTestKeyboard.tearDown
setUp
uTestKeyboard.setUp
uTestKeyboard.do
test_event_json
uTestKeyboard.test_event_json
test_is_modifier_name
uTestKeyboard.test_is_modifier_name
test_is_modifier_scan_code
uTestKeyboard.test_is_modifier_scan_code
test_key_to_scan_codes_brute
uTestKeyboard.test_key_to_scan_codes_brute
test_key_to_scan_code_from_scan_code
uTestKeyboard.test_key_to_scan_code_from_scan_code
test_key_to_scan_code_from_letter
uTestKeyboard.test_key_to_scan_code_from_letter
test_key_to_scan_code_from_normalized
uTestKeyboard.test_key_to_scan_code_from_normalized
test_key_to_scan_code_from_sided_modifier
uTestKeyboard.test_key_to_scan_code_from_sided_modifier
test_key_to_scan_code_underscores
uTestKeyboard.test_key_to_scan_code_underscores
test_key_to_scan_code_error_none
uTestKeyboard.test_key_to_scan_code_error_none
test_key_to_scan_code_error_empty
uTestKeyboard.test_key_to_scan_code_error_empty
test_key_to_scan_code_error_other
uTestKeyboard.test_key_to_scan_code_error_other
test_key_to_scan_code_list
uTestKeyboard.test_key_to_scan_code_list
test_key_to_scan_code_empty
uTestKeyboard.test_key_to_scan_code_empty
test_key_to_scan_code_duplicated
uTestKeyboard.test_key_to_scan_code_duplicated
test_parse_hotkey_simple
uTestKeyboard.test_parse_hotkey_simple
test_parse_hotkey_separators
uTestKeyboard.test_parse_hotkey_separators
test_parse_hotkey_keys
uTestKeyboard.test_parse_hotkey_keys
test_parse_hotkey_simple_steps
uTestKeyboard.test_parse_hotkey_simple_steps
test_parse_hotkey_steps
uTestKeyboard.test_parse_hotkey_steps
test_parse_hotkey_example
uTestKeyboard.test_parse_hotkey_example
test_parse_hotkey_list_scan_codes
uTestKeyboard.test_parse_hotkey_list_scan_codes
test_parse_hotkey_deep_list_scan_codes
uTestKeyboard.test_parse_hotkey_deep_list_scan_codes
test_parse_hotkey_list_names
uTestKeyboard.test_parse_hotkey_list_names
test_is_pressed_none
uTestKeyboard.test_is_pressed_none
test_is_pressed_true
uTestKeyboard.test_is_pressed_true
test_is_pressed_true_scan_code_true
uTestKeyboard.test_is_pressed_true_scan_code_true
test_is_pressed_true_scan_code_false
uTestKeyboard.test_is_pressed_true_scan_code_false
test_is_pressed_true_scan_code_invalid
uTestKeyboard.test_is_pressed_true_scan_code_invalid
test_is_pressed_false
uTestKeyboard.test_is_pressed_false
test_is_pressed_hotkey_true
uTestKeyboard.test_is_pressed_hotkey_true
test_is_pressed_hotkey_false
uTestKeyboard.test_is_pressed_hotkey_false
test_is_pressed_multi_step_fail
uTestKeyboard.test_is_pressed_multi_step_fail
test_send_single_press_release
uTestKeyboard.test_send_single_press_release
test_send_single_press
uTestKeyboard.test_send_single_press
test_send_single_release
uTestKeyboard.test_send_single_release
test_send_single_none
uTestKeyboard.test_send_single_none
test_press
uTestKeyboard.test_press
test_release
uTestKeyboard.test_release
test_press_and_release
uTestKeyboard.test_press_and_release
test_send_modifier_press_release
uTestKeyboard.test_send_modifier_press_release
test_send_modifiers_release
uTestKeyboard.test_send_modifiers_release
test_call_later
uTestKeyboard.test_call_later
test_hook_nonblocking
uTestKeyboard.test_hook_nonblocking
test_hook_blocking
uTestKeyboard.test_hook_blocking
test_on_press_nonblocking
uTestKeyboard.test_on_press_nonblocking
test_on_press_blocking
uTestKeyboard.test_on_press_blocking
test_on_release
uTestKeyboard.test_on_release
test_hook_key_invalid
uTestKeyboard.test_hook_key_invalid
test_hook_key_nonblocking
uTestKeyboard.test_hook_key_nonblocking
test_hook_key_blocking
uTestKeyboard.test_hook_key_blocking
test_on_press_key_nonblocking
uTestKeyboard.test_on_press_key_nonblocking
test_on_press_key_blocking
uTestKeyboard.test_on_press_key_blocking
test_on_release_key
uTestKeyboard.test_on_release_key
test_block_key
uTestKeyboard.test_block_key
test_block_key_ambiguous
uTestKeyboard.test_block_key_ambiguous
test_remap_key_simple
uTestKeyboard.test_remap_key_simple
test_remap_key_ambiguous
uTestKeyboard.test_remap_key_ambiguous
test_remap_key_multiple
uTestKeyboard.test_remap_key_multiple
test_stash_state
uTestKeyboard.test_stash_state
test_restore_state
uTestKeyboard.test_restore_state
test_restore_modifieres
uTestKeyboard.test_restore_modifieres
test_write_simple
uTestKeyboard.test_write_simple
test_write_multiple
uTestKeyboard.test_write_multiple
test_write_modifiers
uTestKeyboard.test_write_modifiers
test_write_stash_restore
uTestKeyboard.test_write_stash_restore
test_write_unicode_explicit
uTestKeyboard.test_write_unicode_explicit
test_write_unicode_fallback
uTestKeyboard.test_write_unicode_fallback
test_start_stop_recording
uTestKeyboard.test_start_stop_recording
test_stop_recording_error
uTestKeyboard.test_stop_recording_error
test_record
uTestKeyboard.test_record
test_play_nodelay
uTestKeyboard.test_play_nodelay
test_play_stash
uTestKeyboard.test_play_stash
test_play_delay
uTestKeyboard.test_play_delay
test_get_typed_strings_simple
uTestKeyboard.test_get_typed_strings_simple
test_get_typed_strings_backspace
uTestKeyboard.test_get_typed_strings_backspace
test_get_typed_strings_shift
uTestKeyboard.test_get_typed_strings_shift
test_get_typed_strings_all
uTestKeyboard.test_get_typed_strings_all
test_get_hotkey_name_simple
uTestKeyboard.test_get_hotkey_name_simple
test_get_hotkey_name_modifiers
uTestKeyboard.test_get_hotkey_name_modifiers
test_get_hotkey_name_normalize
uTestKeyboard.test_get_hotkey_name_normalize
test_get_hotkey_name_plus
uTestKeyboard.test_get_hotkey_name_plus
test_get_hotkey_name_duplicated
uTestKeyboard.test_get_hotkey_name_duplicated
test_get_hotkey_name_full
uTestKeyboard.test_get_hotkey_name_full
test_get_hotkey_name_multiple
uTestKeyboard.test_get_hotkey_name_multiple
test_get_hotkey_name_from_pressed
uTestKeyboard.test_get_hotkey_name_from_pressed
test_read_hotkey
uTestKeyboard.test_read_hotkey
test_read_event
uTestKeyboard.test_read_event
test_read_key
uTestKeyboard.test_read_key
test_wait_infinite
uTestKeyboard.test_wait_infinite
test_wait_until_success
uTestKeyboard.test_wait_until_success
test_wait_until_fail
uTestKeyboard.test_wait_until_fail
test_add_hotkey_single_step_suppress_allow
uTestKeyboard.test_add_hotkey_single_step_suppress_allow
test_add_hotkey_single_step_suppress_args_allow
uTestKeyboard.test_add_hotkey_single_step_suppress_args_allow
test_add_hotkey_single_step_suppress_single
uTestKeyboard.test_add_hotkey_single_step_suppress_single
test_add_hotkey_single_step_suppress_removed
uTestKeyboard.test_add_hotkey_single_step_suppress_removed
test_remove_hotkey_internal
uTestKeyboard.test_remove_hotkey_internal
test_remove_hotkey_internal_multistep_start
uTestKeyboard.test_remove_hotkey_internal_multistep_start
test_remove_hotkey_internal_multistep_end
uTestKeyboard.test_remove_hotkey_internal_multistep_end
test_add_hotkey_single_step_suppress_with_modifiers
uTestKeyboard.test_add_hotkey_single_step_suppress_with_modifiers
test_add_hotkey_single_step_suppress_with_modifiers_fail_unrelated_modifier
uTestKeyboard.test_add_hotkey_single_step_suppress_with_modifiers_fail_unrelated_modifier
test_add_hotkey_single_step_suppress_with_modifiers_fail_unrelated_key
uTestKeyboard.test_add_hotkey_single_step_suppress_with_modifiers_fail_unrelated_key
test_add_hotkey_single_step_suppress_with_modifiers_unrelated_key
uTestKeyboard.test_add_hotkey_single_step_suppress_with_modifiers_unrelated_key
test_add_hotkey_single_step_suppress_with_modifiers_release
uTestKeyboard.test_add_hotkey_single_step_suppress_with_modifiers_release
test_add_hotkey_single_step_suppress_with_modifiers_out_of_order
uTestKeyboard.test_add_hotkey_single_step_suppress_with_modifiers_out_of_order
test_add_hotkey_single_step_suppress_with_modifiers_repeated
uTestKeyboard.test_add_hotkey_single_step_suppress_with_modifiers_repeated
test_add_hotkey_single_step_suppress_with_modifier_superset_release
uTestKeyboard.test_add_hotkey_single_step_suppress_with_modifier_superset_release
test_add_hotkey_single_step_suppress_with_modifier_superset
uTestKeyboard.test_add_hotkey_single_step_suppress_with_modifier_superset
test_add_hotkey_single_step_timeout
uTestKeyboard.test_add_hotkey_single_step_timeout
test_add_hotkey_multi_step_first_timeout
uTestKeyboard.test_add_hotkey_multi_step_first_timeout
test_add_hotkey_multi_step_last_timeout
uTestKeyboard.test_add_hotkey_multi_step_last_timeout
test_add_hotkey_multi_step_success_timeout
uTestKeyboard.test_add_hotkey_multi_step_success_timeout
test_add_hotkey_multi_step_suffix_timeout
uTestKeyboard.test_add_hotkey_multi_step_suffix_timeout
test_add_hotkey_multi_step_allow
uTestKeyboard.test_add_hotkey_multi_step_allow
test_add_hotkey_single_step_nonsuppress
uTestKeyboard.test_add_hotkey_single_step_nonsuppress
test_add_hotkey_single_step_nonsuppress_repeated
uTestKeyboard.test_add_hotkey_single_step_nonsuppress_repeated
test_add_hotkey_single_step_nosuppress_with_modifiers_out_of_order
uTestKeyboard.test_add_hotkey_single_step_nosuppress_with_modifiers_out_of_order
test_add_hotkey_single_step_suppress_regression_1
uTestKeyboard.test_add_hotkey_single_step_suppress_regression_1
test_remap_hotkey_single
uTestKeyboard.test_remap_hotkey_single
test_remap_hotkey_complex_dst
uTestKeyboard.test_remap_hotkey_complex_dst
test_remap_hotkey_modifiers
uTestKeyboard.test_remap_hotkey_modifiers
test_remap_hotkey_modifiers_repeat
uTestKeyboard.test_remap_hotkey_modifiers_repeat
test_remap_hotkey_modifiers_state
uTestKeyboard.test_remap_hotkey_modifiers_state
test_remap_hotkey_release_incomplete
uTestKeyboard.test_remap_hotkey_release_incomplete
test_remap_hotkey_release_complete
uTestKeyboard.test_remap_hotkey_release_complete
test_parse_hotkey_combinations_scan_code
uTestKeyboard.test_parse_hotkey_combinations_scan_code
test_parse_hotkey_combinations_single
uTestKeyboard.test_parse_hotkey_combinations_single
test_parse_hotkey_combinations_single_modifier
uTestKeyboard.test_parse_hotkey_combinations_single_modifier
test_parse_hotkey_combinations_single_modifiers
uTestKeyboard.test_parse_hotkey_combinations_single_modifiers
test_parse_hotkey_combinations_multi
uTestKeyboard.test_parse_hotkey_combinations_multi
test_parse_hotkey_combinations_multi_modifier
uTestKeyboard.test_parse_hotkey_combinations_multi_modifier
test_parse_hotkey_combinations_list_list
uTestKeyboard.test_parse_hotkey_combinations_list_list
test_parse_hotkey_combinations_fail_empty
uTestKeyboard.test_parse_hotkey_combinations_fail_empty
test_add_hotkey_multistep_suppress_incomplete
uTestKeyboard.test_add_hotkey_multistep_suppress_incomplete
test_add_hotkey_multistep_suppress_modifier
uTestKeyboard.test_add_hotkey_multistep_suppress_modifier
test_add_hotkey_multistep_suppress_fail
uTestKeyboard.test_add_hotkey_multistep_suppress_fail
test_add_hotkey_multistep_suppress_three_steps
uTestKeyboard.test_add_hotkey_multistep_suppress_three_steps
test_add_hotkey_multistep_suppress_repeated_prefix
uTestKeyboard.test_add_hotkey_multistep_suppress_repeated_prefix
test_add_hotkey_multistep_suppress_repeated_key
uTestKeyboard.test_add_hotkey_multistep_suppress_repeated_key
test_add_hotkey_multi_step_suppress_regression_1
uTestKeyboard.test_add_hotkey_multi_step_suppress_regression_1
test_add_hotkey_multi_step_suppress_replays
uTestKeyboard.test_add_hotkey_multi_step_suppress_replays
test_add_word_listener_success
uTestKeyboard.test_add_word_listener_success
test_add_word_listener_no_trigger_fail
uTestKeyboard.test_add_word_listener_no_trigger_fail
test_add_word_listener_timeout_fail
uTestKeyboard.test_add_word_listener_timeout_fail
test_duplicated_word_listener
uTestKeyboard.test_duplicated_word_listener
test_add_word_listener_remove
uTestKeyboard.test_add_word_listener_remove
test_add_word_listener_suffix_success
uTestKeyboard.test_add_word_listener_suffix_success
test_add_word_listener_suffix_fail
uTestKeyboard.test_add_word_listener_suffix_fail
a__orig_bases__
ukeyboard\_keyboard_tests.py
T a.0
weT a.0
scan_code
modifiers
T acallback
T achar
T weT ascan_code
T aes
T aqueue
T waaself
arg
T aarg
self
T weaself
T aself
u<module keyboard._keyboard_tests>
T a__class__
T aevent
self
T aself
manual_events
expected
event
to_names
T aarg1
arg2
triggered
T atriggered
T aevent_type
name
scan_code
time
T aevent
T aself
queue
T aself
arg
T aself
queue
free
T aself
blocked
T aself
triggered
fn
T aself
event
json
T aself
events
T aself
count
hook
T aself
name
T aself
wiT aself
name
entries
expected
T aself
result
T aself
alt_codes
shift_codes
a_codes
b_codes
c_codes
T aself
last_time
events
T aself
queue
process
aThread
wtT aself
mapped
T aself
remove
T aself
process
aThread
wtT aself
last_time

.keyboard._mouse_event
+
a__doc__
a__file__
a__spec__
origin
has_location
a__cached__
collections
T anamedtuple
l
namedtuple
left
aLEFT
right
aRIGHT
middle
aMIDDLE
wheel
aWHEEL
wxwXax2
aX2
up
aUP
down
aDOWN
double
aDOUBLE
vertical
aVERTICAL
horizontal
aHORIZONTAL
aButtonEvent
event_type
button
time
aWheelEvent
delta
aMoveEvent
wyukeyboard\_mouse_event.py
u<module keyboard._mouse_event>

.keyboard._mouse_tests
append
T l
paposition
queue
u<lambda>
uFakeOsMouse.__init__.<locals>.<lambda>
init
listening
aDOWN
aUP
move
wheel
l
l aFakeOsMouse
mouse
a_os_mouse
a_listener
start_if_necessary
events
a_pressed_events
clear
unhook_all
wait_for_events_queue
join
:nnnaput
aButtonEvent
time
aDOUBLE
press
release
aWheelEvent
aMoveEvent
hook
unhook
assertEqual
assertFalse
is_pressed
assertTrue
aX2
flush_events
aLEFT
click
double_click
right_click
aRIGHT
get_position
T ldl  T l l FT lel  T ldl  tf{  G z ?T aduration
T ldl  T ldl Ff{  G z ?T l  l  T l
pFf{  G z ?atriggered
callback
uTestMouse.triggers.<locals>.callback
utoo many values to unpack (expected 2)
self
aWHEEL
remove_handler
triggers
on_button
wXT aWHEEL

aMIDDLE
T abuttons
T abuttons
types
on_click
on_double_click
on_right_click
on_middle_click
threading
T aThread
aLock
aThread
aLock
acquire
wtuTestMouse.test_wait.<locals>.t
T atarget
start
wait
lock
uTestMouse.test_record_play.<locals>.t
T l T ldl2arecorded
l a_replace
T nT atime
l T l nl T ldl2nl aplay
D aspeed_factor
l
T awheel
l T amove
T ldl2D ainclude_clicks
FD ainclude_moves
FD ainclude_wheel
Farecord
a__doc__
a__file__
a__spec__
origin
has_location
a__cached__
unittest
a_mouse_event
T aMoveEvent
aButtonEvent
aWheelEvent
aLEFT
aRIGHT
aMIDDLE
wXaX2
aUP
aDOWN
aDOUBLE
keyboard
T amouse
T Oobject
a__prepare__
a__getitem__
u%s.__prepare__() must return a mapping, not %s
a__name__
u<metaclass>
