# Reconstructed from integrated Nuitka blob
# Module: upsutil.tests.test_memleaks

a__qualname__
test_coverage
uTestProcessObjectLeaks.test_coverage
test_name
uTestProcessObjectLeaks.test_name
test_cmdline
uTestProcessObjectLeaks.test_cmdline
test_exe
uTestProcessObjectLeaks.test_exe
test_ppid
uTestProcessObjectLeaks.test_ppid
mark
skipif
D areason
uPOSIX only
test_uids
uTestProcessObjectLeaks.test_uids
test_gids
uTestProcessObjectLeaks.test_gids
test_status
uTestProcessObjectLeaks.test_status
test_nice
uTestProcessObjectLeaks.test_nice
test_nice_set
uTestProcessObjectLeaks.test_nice_set
D areason
unot supported
test_ionice
uTestProcessObjectLeaks.test_ionice
test_ionice_set
uTestProcessObjectLeaks.test_ionice_set
test_io_counters
uTestProcessObjectLeaks.test_io_counters
D areason
uworthless on POSIX
test_username
uTestProcessObjectLeaks.test_username
test_create_time
uTestProcessObjectLeaks.test_create_time
T aonly_if
test_num_threads
uTestProcessObjectLeaks.test_num_threads
D areason
uWINDOWS only
test_num_handles
uTestProcessObjectLeaks.test_num_handles
test_num_fds
uTestProcessObjectLeaks.test_num_fds
test_num_ctx_switches
uTestProcessObjectLeaks.test_num_ctx_switches
test_threads
uTestProcessObjectLeaks.test_threads
test_cpu_times
uTestProcessObjectLeaks.test_cpu_times
test_cpu_num
uTestProcessObjectLeaks.test_cpu_num
test_memory_info
uTestProcessObjectLeaks.test_memory_info
test_memory_full_info
uTestProcessObjectLeaks.test_memory_full_info
test_terminal
uTestProcessObjectLeaks.test_terminal
test_resume
uTestProcessObjectLeaks.test_resume
test_cwd
uTestProcessObjectLeaks.test_cwd
test_cpu_affinity
uTestProcessObjectLeaks.test_cpu_affinity
test_cpu_affinity_set
uTestProcessObjectLeaks.test_cpu_affinity_set
test_open_files
uTestProcessObjectLeaks.test_open_files
test_memory_maps
uTestProcessObjectLeaks.test_memory_maps
D areason
uLINUX only
test_rlimit
uTestProcessObjectLeaks.test_rlimit
test_rlimit_set
uTestProcessObjectLeaks.test_rlimit_set
D areason
uworthless on WINDOWS
test_net_connections
uTestProcessObjectLeaks.test_net_connections
test_environ
uTestProcessObjectLeaks.test_environ
test_proc_info
uTestProcessObjectLeaks.test_proc_info
a__orig_bases__
aTestTerminatedProcessLeaks
classmethod
uTestTerminatedProcessLeaks.setUpClass
uTestTerminatedProcessLeaks.tearDownClass
uTestTerminatedProcessLeaks.call
test_kill
uTestTerminatedProcessLeaks.test_kill
test_terminate
uTestTerminatedProcessLeaks.test_terminate
test_suspend
uTestTerminatedProcessLeaks.test_suspend
uTestTerminatedProcessLeaks.test_resume
test_wait
uTestTerminatedProcessLeaks.test_wait
uTestTerminatedProcessLeaks.test_proc_info
aTestProcessDualImplementation
test_cmdline_peb_true
uTestProcessDualImplementation.test_cmdline_peb_true
test_cmdline_peb_false
uTestProcessDualImplementation.test_cmdline_peb_false
aTestModuleFunctionsLeaks
uTestModuleFunctionsLeaks.test_coverage
test_cpu_count
uTestModuleFunctionsLeaks.test_cpu_count
test_cpu_count_cores
uTestModuleFunctionsLeaks.test_cpu_count_cores
uTestModuleFunctionsLeaks.test_cpu_times
test_per_cpu_times
uTestModuleFunctionsLeaks.test_per_cpu_times
test_cpu_stats
uTestModuleFunctionsLeaks.test_cpu_stats
D areason
uskipped due to #1892
test_cpu_freq
uTestModuleFunctionsLeaks.test_cpu_freq
test_getloadavg
uTestModuleFunctionsLeaks.test_getloadavg
test_virtual_memory
uTestModuleFunctionsLeaks.test_virtual_memory
D areason
uworthless on SUNOS (uses a subprocess)
test_swap_memory
uTestModuleFunctionsLeaks.test_swap_memory
test_pid_exists
uTestModuleFunctionsLeaks.test_pid_exists
test_disk_usage
uTestModuleFunctionsLeaks.test_disk_usage
test_disk_partitions
uTestModuleFunctionsLeaks.test_disk_partitions
path
exists
T u/proc/diskstats
D areason
u/proc/diskstats not available on this Linux version
test_disk_io_counters
uTestModuleFunctionsLeaks.test_disk_io_counters
test_pids
uTestModuleFunctionsLeaks.test_pids
test_net_io_counters
uTestModuleFunctionsLeaks.test_net_io_counters
getuid
D areason
uneed root access
uTestModuleFunctionsLeaks.test_net_connections
test_net_if_addrs
uTestModuleFunctionsLeaks.test_net_if_addrs
test_net_if_stats
uTestModuleFunctionsLeaks.test_net_if_stats
test_sensors_battery
uTestModuleFunctionsLeaks.test_sensors_battery
test_sensors_temperatures
uTestModuleFunctionsLeaks.test_sensors_temperatures
test_sensors_fans
uTestModuleFunctionsLeaks.test_sensors_fans
test_boot_time
uTestModuleFunctionsLeaks.test_boot_time
test_users
uTestModuleFunctionsLeaks.test_users
test_set_debug
uTestModuleFunctionsLeaks.test_set_debug
test_win_service_iter
uTestModuleFunctionsLeaks.test_win_service_iter
test_win_service_get
uTestModuleFunctionsLeaks.test_win_service_get
test_win_service_get_config
uTestModuleFunctionsLeaks.test_win_service_get_config
test_win_service_get_status
uTestModuleFunctionsLeaks.test_win_service_get_status
test_win_service_get_description
uTestModuleFunctionsLeaks.test_win_service_get_description
upsutil\tests\test_memleaks.py
T aname
T aself
T aself
affinity
T aaffinity
self
T aself
value
T aself
kind
T akind
self
T aself
niceness
T aniceness
self
T aself
limit
T alimit
self
u<module psutil.tests.test_memleaks>
T a__class__
T aself
fun
T afun
wrapper
T adecorator
T acls
a__class__
T aself
ns
T aself
times
T aself
value
fun
T aself
tolerance
T aself
call
T aself
name
T aself
args
kwargs
before
fun
T afun

.psutil.tests.test_misc
f
w apytest
raises
T EOverflowError
a__enter__
a__exit__
psutil
a_psplatform
cext
check_pid_range
l l  T nnnaNoSuchProcess
aProcess
spawn_subproc
pid
terminate
wait
patch
object
name
aZombieProcess
getpid
T aside_effect
aAccessDenied
test_process__repr__
T Ostr
T afunc
T l
pa_ident
P adebug
aPermissionError
aProcessLookupError
test
tests
startswith
T w_a__all__
a__doc__
deprecated
lower
fail

u not in psutil.__all__
w1afoo
check
uTestMisc.test_serialization.<locals>.check
as_dict
process_namespace
aiter
getters
D aclear_cache
tutoo many values to unpack (expected 2)
self
subTest
T aproc
name
aError
ret
system_namespace
P awin_service_iter
win_service_get
T aname
pickle
loads
dumps
T l #aname
msg
T apid
name
msg
T l #aname
l*amsg
T apid
name
ppid
msg
T l{aname
msg
aTimeoutExpired
T l!l #aname
T aseconds
pid
name
json
a_get_ident
T l D aside_effect
EValueError
T EValueError
T upsutil._psplatform.cext.version
u0.0.0
T areturn_value
T EImportError
reload_module
calls
;l
l l aobj
T l l T abar
cache_clear
memoize
uTestMemoizeDecorator.test_function.<locals>.foo
run_against
D aexpected_retval
l abaseclass
append
