# Reconstructed from integrated Nuitka blob
# Module: ullvmlite.binding.executionengine

a__qualname__
uExecutionEngine.__init__
get_function_address
uExecutionEngine.get_function_address
get_global_value_address
uExecutionEngine.get_global_value_address
add_global_mapping
uExecutionEngine.add_global_mapping
add_module
uExecutionEngine.add_module
finalize_object
uExecutionEngine.finalize_object
run_static_constructors
uExecutionEngine.run_static_constructors
run_static_destructors
uExecutionEngine.run_static_destructors
remove_module
uExecutionEngine.remove_module
property
target_data
uExecutionEngine.target_data
enable_jit_events
uExecutionEngine.enable_jit_events
uExecutionEngine._find_module_ptr
add_object_file
uExecutionEngine.add_object_file
T nnaset_object_cache
uExecutionEngine.set_object_cache
a_raw_object_cache_notify
uExecutionEngine._raw_object_cache_notify
a_raw_object_cache_getbuffer
uExecutionEngine._raw_object_cache_getbuffer
a_dispose
uExecutionEngine._dispose
a__orig_bases__
u_ObjectCacheRef.__init__
u_ObjectCacheRef._dispose
aLLVMModuleRef
aLLVMTargetMachineRef
argtypes
aLLVMExecutionEngineRef
restype
aLLVMValueRef
aLLVMTargetDataRef
aLLVMObjectFileRef
a_ObjectCacheData
a_fields_
a_ObjectCacheNotifyFunc
a_ObjectCacheGetBufferFunc
aLLVMObjectCacheRef
ullvmlite\binding\executionengine.py
u<module llvmlite.binding.executionengine>
T a__class__
T aself
ptr
module
T aself
obj
ptr
T aself
mod
T aself
T aself
module_ptr
ptr
module
T aself
data
module_ptr
module
buf
T aself
data
module_ptr
buf_ptr
buf_len
buf
module
T aself
gv
addr
T aself
module
T aself
obj_file
T aerrno
T amodule
target_machine
use_lmm
outerr
engine
T aself
ret
T aself
name
T aself
module
outerr
T aself
notify_func
getbuffer_func
T aself
ptr

.llvmlite.binding.ffi
aStructure
ullvmlite.binding.ffi
aPOINTER
threading
aRLock
a_lock
a_cblist
append
remove
acquire
utoo many values to unpack (expected 2)
release
a_context
a__enter__
a__exit__
a_lib_handle
a_fntab
a_LLVMLock
a_suppress_cleanup_errors
a_importlib_resources_path
ullvmlite.binding
get_library_name
aCDLL
aLLVMPY_GetVersionInfo
T nnnT EOSError
EAttributeError
uCould not find/load shared object file
a_load_lib
a_lib
a_lib_fn_wrapper
a_name
a_handle
a_cfn
argtypes
restype
as_file
files
lib
register
unregister
cast
c_char_p
T ainit
T na_ptr
byref
a_as_parameter_
a_owned
aLLVMPY_DisposeString
close
u<dead OutputString>
value
a_decode_string
aOutputString
from_return
bytes
uNULL pointer
a_capi
a_closed
a_dispose
detach
u%s instance already closed
addressof
l
c_void_p
a__doc__
a__file__
a__spec__
origin
has_location
a__cached__
sys
ctypes
a_impres
ullvmlite.binding.common
T a_decode_string
a_is_shutting_down
a_is_shutting_down
ullvmlite.utils
T aget_library_name
a_make_opaque_ref
T aLLVMContext
aLLVMContextRef
T aLLVMModule
aLLVMModuleRef
T aLLVMValue
aLLVMValueRef
T aLLVMType
aLLVMTypeRef
T aLLVMExecutionEngine
aLLVMExecutionEngineRef
T aLLVMPassManagerBuilder
aLLVMPassManagerBuilderRef
T aLLVMPassManager
aLLVMPassManagerRef
T aLLVMTargetData
aLLVMTargetDataRef
T aLLVMTargetLibraryInfo
aLLVMTargetLibraryInfoRef
T aLLVMTarget
aLLVMTargetRef
T aLLVMTargetMachine
aLLVMTargetMachineRef
T aLLVMMemoryBuffer
aLLVMMemoryBufferRef
T aLLVMAttributeListIterator
aLLVMAttributeListIterator
T aLLVMElementIterator
aLLVMElementIterator
T aLLVMAttributeSetIterator
aLLVMAttributeSetIterator
T aLLVMGlobalsIterator
aLLVMGlobalsIterator
T aLLVMFunctionsIterator
aLLVMFunctionsIterator
T aLLVMBlocksIterator
aLLVMBlocksIterator
T aLLVMArgumentsIterator
aLLVMArgumentsIterator
T aLLVMInstructionsIterator
aLLVMInstructionsIterator
T aLLVMOperandsIterator
aLLVMOperandsIterator
T aLLVMIncomingBlocksIterator
aLLVMIncomingBlocksIterator
T aLLVMTypesIterator
aLLVMTypesIterator
T aLLVMObjectCache
aLLVMObjectCacheRef
T aLLVMObjectFile
aLLVMObjectFileRef
T aLLVMSectionIterator
aLLVMSectionIteratorRef
T aLLVMOrcLLJITRef
aLLVMOrcLLJITRef
T aLLVMOrcDylibTrackerRef
aLLVMOrcDylibTrackerRef
T aLLVMTimePassesHandler
aLLVMTimePassesHandlerRef
T aLLVMPipeLineTuningOptions
aLLVMPipelineTuningOptionsRef
T aLLVMModulePassManager
aLLVMModulePassManagerRef
T aLLVMFunctionPassManager
aLLVMFunctionPassManagerRef
T aLLVMPassBuilder
