# Reconstructed from integrated Nuitka blob
# Module: uaiohttp.streams

ueof stream indication.
a__qualname__
a__orig_bases__
T aread_func
a__slots__
return
uAsyncStreamIterator.__init__
D areturn
uAsyncStreamIterator[_T]
a__aiter__
uAsyncStreamIterator.__aiter__
T a_stream
D astream
return
aStreamReader
nuChunkTupleAsyncStreamIterator.__init__
D areturn
aChunkTupleAsyncStreamIterator
uChunkTupleAsyncStreamIterator.__aiter__
T Obytes
Obool
aAsyncStreamReaderMixin
uAsyncStreamReaderMixin.__aiter__
iter_chunked
uAsyncStreamReaderMixin.iter_chunked
iter_any
uAsyncStreamReaderMixin.iter_any
iter_chunks
uAsyncStreamReaderMixin.iter_chunks
aStreamReader
uAn enhancement of asyncio.StreamReader.
Supports asynchronous iteration by line, chunk or as available::
sync for line in reader:
...
sync for chunk in reader.iter_chunked(1024):
...
sync for slice in reader.iter_any():
...
T a_protocol
a_low_water
a_high_water
a_loop
a_size
a_cursor
a_http_chunk_splits
a_buffer
a_buffer_offset
a_eof
a_waiter
a_eof_waiter
a_exception
a_timer
a_eof_callbacks
a_eof_counter
total_bytes
D atimer
loop
nnaprotocol
limit
int
timer
loop
aAbstractEventLoop
uStreamReader.__init__
str
a__repr__
uStreamReader.__repr__
get_read_buffer_limits
uStreamReader.get_read_buffer_limits
aBaseException
uStreamReader.exception
exc
exc_cause
uStreamReader.set_exception
callback
T L
naon_eof
uStreamReader.on_eof
D areturn
nafeed_eof
uStreamReader.feed_eof
bool
is_eof
uStreamReader.is_eof
at_eof
uStreamReader.at_eof
data
bytes
unread_data
uStreamReader.unread_data
size
uStreamReader.feed_data
begin_http_chunk_receiving
uStreamReader.begin_http_chunk_receiving
end_http_chunk_receiving
uStreamReader.end_http_chunk_receiving
T d
read_nowait
uStreamReader.read_nowait
uStreamReader._read_nowait_chunk
uStreamReader._read_nowait
aEmptyStreamReader
T a_read_eof_chunk
uEmptyStreamReader.__init__
uEmptyStreamReader.__repr__
uEmptyStreamReader.exception
uEmptyStreamReader.set_exception
uEmptyStreamReader.on_eof
uEmptyStreamReader.feed_eof
uEmptyStreamReader.is_eof
uEmptyStreamReader.at_eof
uEmptyStreamReader.feed_data
uEmptyStreamReader.read_nowait
aEMPTY_PAYLOAD
aDataQueue
uDataQueue is a general-purpose blocking queue with one reader.
uDataQueue.__init__
a__len__
uDataQueue.__len__
uDataQueue.is_eof
uDataQueue.at_eof
uDataQueue.exception
uDataQueue.set_exception
uDataQueue.feed_data
uDataQueue.feed_eof
uDataQueue.__aiter__
aFlowControlDataQueue
uFlowControlDataQueue resumes and pauses an underlying stream.
It is a destination for parsed data.
This class is deprecated and will be removed in version 4.0.
uFlowControlDataQueue.__init__
uFlowControlDataQueue.feed_data
uaiohttp\streams.py
T aself
wnT wnaself
u<module aiohttp.streams>
T a__class__
T aself
T aself
rv
T aself
read_func
T aself
stream
T aself
loop
T aself
protocol
limit
loop
a__class__
T aself
protocol
limit
timer
loop
T aself
info
T aself
wnachunks
chunk
T aself
wnafirst_buffer
offset
data
data_len
chunk_splits
T aself
func_name
waiter
T aself
pos
waiter
T aself
data
size
waiter
T aself
data
wnT aself
data
size
a__class__
T aself
data
size
data_len
waiter
T aself
waiter
T aself
waiter
cb
T aself
callback
T aself
data
w_T aself
data
size
T aself
wnablocks
block
T aself
pos
T aself
wnablocks
block
partial
T	aself
separator
seplen
chunk
chunk_size
not_enough
offset
ichar
data
T aself
exc
exc_cause
waiter
T aself
exc
exc_cause
T aself
data

a__spec__
.aiohttp.tcp_helpers
)
get_extra_info
T asocket
setsockopt
socket
aSOL_SOCKET
aSO_KEEPALIVE
family
aAF_INET
aAF_INET6
suppress
T EOSError
a__enter__
a__exit__
aIPPROTO_TCP
aTCP_NODELAY
T nnnuHelper methods to tune a TCP connection
a__doc__
a__file__
origin
has_location
a__cached__
asyncio
contextlib
T asuppress
aOptional
T atcp_keepalive
tcp_nodelay
a__all__
transport
aTransport
return
tcp_keepalive
value
tcp_nodelay
uaiohttp\tcp_helpers.py
u<module aiohttp.tcp_helpers>
T atransport
T atransport
sock
T atransport
value
sock

a__spec__
.aiohttp.tracing
aSignal
a_on_request_start
a_on_request_chunk_sent
a_on_response_chunk_received
a_on_request_end
a_on_request_exception
a_on_request_redirect
a_on_connection_queued_start
a_on_connection_queued_end
a_on_connection_create_start
a_on_connection_create_end
a_on_connection_reuseconn
a_on_dns_resolvehost_start
a_on_dns_resolvehost_end
a_on_dns_cache_hit
a_on_dns_cache_miss
a_on_request_headers_sent
a_trace_config_ctx_factory
T atrace_request_ctx
uReturn a new trace_config_ctx instance
freeze
a_trace_config
a_trace_config_ctx
a_session
self
on_request_start
send
aTraceRequestStartParams
method
url
headers
send_request_start
uTrace.send_request_start
on_request_chunk_sent
aTraceRequestChunkSentParams
chunk
send_request_chunk_sent
uTrace.send_request_chunk_sent
on_response_chunk_received
aTraceResponseChunkReceivedParams
send_response_chunk_received
uTrace.send_response_chunk_received
on_request_end
aTraceRequestEndParams
response
send_request_end
uTrace.send_request_end
on_request_exception
aTraceRequestExceptionParams
exception
send_request_exception
uTrace.send_request_exception
aTraceRequestRedirectParams
send_request_redirect
uTrace.send_request_redirect
on_connection_queued_start
aTraceConnectionQueuedStartParams
send_connection_queued_start
uTrace.send_connection_queued_start
on_connection_queued_end
aTraceConnectionQueuedEndParams
send_connection_queued_end
uTrace.send_connection_queued_end
on_connection_create_start
aTraceConnectionCreateStartParams
send_connection_create_start
uTrace.send_connection_create_start
on_connection_create_end
aTraceConnectionCreateEndParams
send_connection_create_end
uTrace.send_connection_create_end
on_connection_reuseconn
aTraceConnectionReuseconnParams
send_connection_reuseconn
uTrace.send_connection_reuseconn
on_dns_resolvehost_start
aTraceDnsResolveHostStartParams
host
send_dns_resolvehost_start
uTrace.send_dns_resolvehost_start
on_dns_resolvehost_end
aTraceDnsResolveHostEndParams
send_dns_resolvehost_end
uTrace.send_dns_resolvehost_end
on_dns_cache_hit
aTraceDnsCacheHitParams
send_dns_cache_hit
uTrace.send_dns_cache_hit
on_dns_cache_miss
aTraceDnsCacheMissParams
send_dns_cache_miss
uTrace.send_dns_cache_miss
aTraceRequestHeadersSentParams
send_request_headers
uTrace.send_request_headers
a__doc__
a__file__
origin
has_location
a__cached__
aSimpleNamespace
aTYPE_CHECKING
aAwaitable
aMapping
aOptional
aProtocol
aType
aTypeVar
attr
aiosignal
T aSignal
multidict
T aCIMultiDict
aCIMultiDict
yarl
T aURL
aURL
client_reqrep
T aClientResponse
aClientResponse
T aTraceConfig
aTraceRequestStartParams
aTraceRequestEndParams
aTraceRequestExceptionParams
aTraceConnectionQueuedStartParams
aTraceConnectionQueuedEndParams
aTraceConnectionCreateStartParams
aTraceConnectionCreateEndParams
aTraceConnectionReuseconnParams
aTraceDnsResolveHostStartParams
aTraceDnsResolveHostEndParams
aTraceDnsCacheHitParams
aTraceDnsCacheMissParams
aTraceRequestRedirectParams
aTraceRequestChunkSentParams
aTraceResponseChunkReceivedParams
aTraceRequestHeadersSentParams
a__all__
