# Reconstructed from integrated Nuitka blob
# Module: ubip_utils.addr.bch_addr_converter


Bitcoin Cash address converter class.
It allows to convert a Bitcoin Cash address by changing its HRP and net version.
aBchAddrConverter
a__qualname__
T naaddress
hrp
net_ver
return
aConvert
uBchAddrConverter.Convert
ubip_utils\addr\bch_addr_converter.py
u<module bip_utils.addr.bch_addr_converter>
T a__class__
T aaddress
hrp
net_ver
curr_net_ver
data

a__spec__
.bip_utils.addr
a__doc__
a__file__
path
dirname
join
environ
get
T aNUITKA_PACKAGE_bip_utils
u\not_existing
addr
T aNUITKA_PACKAGE_bip_utils_addr
u\not_existing
a__path__
origin
has_location
submodule_search_locations
a__cached__
ubip_utils.addr.ada_byron_addr
T aAdaByronAddrDecoder
aAdaByronAddrTypes
aAdaByronIcarusAddr
aAdaByronIcarusAddrEncoder
aAdaByronLegacyAddr
aAdaByronLegacyAddrEncoder
aAdaByronAddrDecoder
aAdaByronAddrTypes
aAdaByronIcarusAddr
aAdaByronIcarusAddrEncoder
aAdaByronLegacyAddr
aAdaByronLegacyAddrEncoder
ubip_utils.addr.ada_shelley_addr
T
aAdaShelleyAddr
aAdaShelleyAddrDecoder
aAdaShelleyAddrEncoder
aAdaShelleyAddrNetworkTags
aAdaShelleyRewardAddr
aAdaShelleyRewardAddrDecoder
aAdaShelleyRewardAddrEncoder
aAdaShelleyStakingAddr
aAdaShelleyStakingAddrDecoder
aAdaShelleyStakingAddrEncoder
aAdaShelleyAddr
aAdaShelleyAddrDecoder
aAdaShelleyAddrEncoder
aAdaShelleyAddrNetworkTags
aAdaShelleyRewardAddr
aAdaShelleyRewardAddrDecoder
aAdaShelleyRewardAddrEncoder
aAdaShelleyStakingAddr
aAdaShelleyStakingAddrDecoder
aAdaShelleyStakingAddrEncoder
ubip_utils.addr.algo_addr
T aAlgoAddr
aAlgoAddrDecoder
aAlgoAddrEncoder
aAlgoAddr
aAlgoAddrDecoder
aAlgoAddrEncoder
ubip_utils.addr.aptos_addr
T aAptosAddr
aAptosAddrDecoder
aAptosAddrEncoder
aAptosAddr
aAptosAddrDecoder
aAptosAddrEncoder
ubip_utils.addr.atom_addr
T aAtomAddr
aAtomAddrDecoder
aAtomAddrEncoder
aAtomAddr
aAtomAddrDecoder
aAtomAddrEncoder
ubip_utils.addr.avax_addr
T aAvaxPChainAddr
aAvaxPChainAddrDecoder
aAvaxPChainAddrEncoder
aAvaxXChainAddr
aAvaxXChainAddrDecoder
aAvaxXChainAddrEncoder
aAvaxPChainAddr
aAvaxPChainAddrDecoder
aAvaxPChainAddrEncoder
aAvaxXChainAddr
aAvaxXChainAddrDecoder
aAvaxXChainAddrEncoder
ubip_utils.addr.bch_addr_converter
T aBchAddrConverter
aBchAddrConverter
ubip_utils.addr.egld_addr
T aEgldAddr
aEgldAddrDecoder
aEgldAddrEncoder
aEgldAddr
aEgldAddrDecoder
aEgldAddrEncoder
ubip_utils.addr.eos_addr
T aEosAddr
aEosAddrDecoder
aEosAddrEncoder
aEosAddr
aEosAddrDecoder
aEosAddrEncoder
ubip_utils.addr.ergo_addr
T aErgoNetworkTypes
aErgoP2PKHAddr
aErgoP2PKHAddrDecoder
aErgoP2PKHAddrEncoder
aErgoNetworkTypes
aErgoP2PKHAddr
aErgoP2PKHAddrDecoder
aErgoP2PKHAddrEncoder
ubip_utils.addr.eth_addr
T aEthAddr
aEthAddrDecoder
aEthAddrEncoder
aEthAddr
aEthAddrDecoder
aEthAddrEncoder
ubip_utils.addr.fil_addr
T aFilSecp256k1Addr
aFilSecp256k1AddrDecoder
aFilSecp256k1AddrEncoder
aFilSecp256k1Addr
aFilSecp256k1AddrDecoder
aFilSecp256k1AddrEncoder
ubip_utils.addr.iaddr_encoder
T aIAddrEncoder
aIAddrEncoder
ubip_utils.addr.icx_addr
T aIcxAddr
aIcxAddrDecoder
aIcxAddrEncoder
aIcxAddr
aIcxAddrDecoder
aIcxAddrEncoder
ubip_utils.addr.inj_addr
T aInjAddr
aInjAddrDecoder
aInjAddrEncoder
aInjAddr
aInjAddrDecoder
aInjAddrEncoder
ubip_utils.addr.nano_addr
T aNanoAddr
aNanoAddrDecoder
aNanoAddrEncoder
aNanoAddr
aNanoAddrDecoder
aNanoAddrEncoder
ubip_utils.addr.near_addr
T aNearAddr
aNearAddrDecoder
aNearAddrEncoder
aNearAddr
aNearAddrDecoder
aNearAddrEncoder
ubip_utils.addr.neo_addr
T aNeoAddr
aNeoAddrDecoder
aNeoAddrEncoder
aNeoAddr
aNeoAddrDecoder
aNeoAddrEncoder
ubip_utils.addr.okex_addr
T aOkexAddr
aOkexAddrDecoder
aOkexAddrEncoder
aOkexAddr
aOkexAddrDecoder
aOkexAddrEncoder
ubip_utils.addr.one_addr
T aOneAddr
aOneAddrDecoder
aOneAddrEncoder
aOneAddr
aOneAddrDecoder
aOneAddrEncoder
ubip_utils.addr.P2PKH_addr
T aBchP2PKHAddr
aBchP2PKHAddrDecoder
aBchP2PKHAddrEncoder
aP2PKHAddr
aP2PKHAddrDecoder
aP2PKHAddrEncoder
aP2PKHPubKeyModes
aBchP2PKHAddr
aBchP2PKHAddrDecoder
aBchP2PKHAddrEncoder
aP2PKHAddr
aP2PKHAddrDecoder
aP2PKHAddrEncoder
aP2PKHPubKeyModes
ubip_utils.addr.P2SH_addr
T aBchP2SHAddr
aBchP2SHAddrDecoder
aBchP2SHAddrEncoder
aP2SHAddr
aP2SHAddrDecoder
aP2SHAddrEncoder
aBchP2SHAddr
aBchP2SHAddrDecoder
aBchP2SHAddrEncoder
aP2SHAddr
aP2SHAddrDecoder
aP2SHAddrEncoder
ubip_utils.addr.P2TR_addr
T aP2TRAddr
aP2TRAddrDecoder
aP2TRAddrEncoder
aP2TRAddr
aP2TRAddrDecoder
aP2TRAddrEncoder
ubip_utils.addr.P2WPKH_addr
T aP2WPKHAddr
aP2WPKHAddrDecoder
aP2WPKHAddrEncoder
aP2WPKHAddr
aP2WPKHAddrDecoder
aP2WPKHAddrEncoder
ubip_utils.addr.sol_addr
T aSolAddr
aSolAddrDecoder
aSolAddrEncoder
aSolAddr
aSolAddrDecoder
aSolAddrEncoder
ubip_utils.addr.substrate_addr
T aSubstrateEd25519Addr
aSubstrateEd25519AddrDecoder
aSubstrateEd25519AddrEncoder
aSubstrateSr25519Addr
aSubstrateSr25519AddrDecoder
aSubstrateSr25519AddrEncoder
aSubstrateEd25519Addr
aSubstrateEd25519AddrDecoder
aSubstrateEd25519AddrEncoder
aSubstrateSr25519Addr
aSubstrateSr25519AddrDecoder
aSubstrateSr25519AddrEncoder
ubip_utils.addr.sui_addr
T aSuiAddr
aSuiAddrDecoder
aSuiAddrEncoder
aSuiAddr
aSuiAddrDecoder
aSuiAddrEncoder
ubip_utils.addr.trx_addr
T aTrxAddr
aTrxAddrDecoder
aTrxAddrEncoder
aTrxAddr
aTrxAddrDecoder
aTrxAddrEncoder
ubip_utils.addr.xlm_addr
T aXlmAddr
aXlmAddrDecoder
aXlmAddrEncoder
aXlmAddrTypes
aXlmAddr
aXlmAddrDecoder
aXlmAddrEncoder
aXlmAddrTypes
ubip_utils.addr.xmr_addr
T aXmrAddr
aXmrAddrDecoder
aXmrAddrEncoder
aXmrIntegratedAddr
aXmrIntegratedAddrDecoder
aXmrIntegratedAddrEncoder
aXmrAddr
aXmrAddrDecoder
aXmrAddrEncoder
aXmrIntegratedAddr
aXmrIntegratedAddrDecoder
aXmrIntegratedAddrEncoder
ubip_utils.addr.xrp_addr
T aXrpAddr
aXrpAddrDecoder
aXrpAddrEncoder
aXrpAddr
aXrpAddrDecoder
aXrpAddrEncoder
ubip_utils.addr.xtz_addr
T aXtzAddr
aXtzAddrDecoder
aXtzAddrEncoder
aXtzAddrPrefixes
aXtzAddr
aXtzAddrDecoder
aXtzAddrEncoder
aXtzAddrPrefixes
ubip_utils.addr.zil_addr
T aZilAddr
aZilAddrDecoder
aZilAddrEncoder
aZilAddr
aZilAddrDecoder
aZilAddrEncoder
ubip_utils\addr\__init__.py
u<module bip_utils.addr>

a__spec__
.bip_utils.addr.egld_addr
9
O
aBech32Decoder
aDecode
aCoinsConf
aElrond
aParamByKey
T aaddr_hrp
aBech32ChecksumError
uInvalid bech32 checksum
aAddrDecUtils
aValidateLength
aEd25519PublicKey
aCompressedLength
aValidatePubKey

Decode an Elrond address to bytes.
Args:
ddr (str): Address string
**kwargs  : Not used
Returns:
bytes: Public key bytes
Raises:
ValueError: If the address encoding is not valid
aAddrKeyValidator
aValidateAndGetEd25519Key
aBech32Encoder
aEncode
aRawCompressed
aToBytes
:l nnu
Encode a public key to Elrond address.
Args:
pub_key (bytes or IPublicKey): Public key bytes or object
**kwargs                     : Not used
Returns:
str: Address string
Raises:
ValueError: If the public key is not valid
TypeError: If the public key is not ed25519
uModule for Elrond address encoding/decoding.
a__doc__
a__file__
origin
has_location
a__cached__
aAny
aUnion
ubip_utils.addr.addr_dec_utils
T aAddrDecUtils
ubip_utils.addr.addr_key_validator
T aAddrKeyValidator
ubip_utils.addr.iaddr_decoder
T aIAddrDecoder
aIAddrDecoder
ubip_utils.addr.iaddr_encoder
T aIAddrEncoder
aIAddrEncoder
ubip_utils.bech32
T aBech32ChecksumError
aBech32Decoder
aBech32Encoder
ubip_utils.coin_conf
T aCoinsConf
ubip_utils.ecc
T aEd25519PublicKey
aIPublicKey
aIPublicKey
a__prepare__
aEgldAddrDecoder
a__getitem__
u%s.__prepare__() must return a mapping, not %s
a__name__
u<metaclass>
