# Reconstructed from integrated Nuitka blob
# Module: ubip_utils.coin_conf.coins_conf

uClass container for coins configuration.
aCoinsConf
a__qualname__
T aAcala
aACA
D aaddr_ss58_format
l
T acoin_name
params
aAcala
T uAkash Network
aAKT
addr_hrp
aAKASH_NETWORK
aAkashNetwork
T aAlgorand
aALGO
aAlgorand
T aAptos
aAPTOS
D aaddr_prefix
u0x
aAptos
T aArbitrum
aARB
aArbitrum
T uAvax C-Chain
aAVAX
aAvaxCChain
T uAvax P-Chain
aAVAX
D aaddr_hrp
addr_prefix
avax
uP-
aAvaxPChain
T uAvax X-Chain
aAVAX
D aaddr_hrp
addr_prefix
avax
uX-
aAvaxXChain
T aAxelar
aAXL
aAXELAR
aAxelar
T uBand Protocol
aBAND
aBAND_PROTOCOL
aBandProtocol
T aBifrost
aBNC
D aaddr_ss58_format
l aBifrost
T uBinance Chain
aBNB
aBINANCE_CHAIN
aBinanceChain
T uBinance Smart Chain
aBNB
aBinanceSmartChain
T aBitcoin
aBTC
p2pkh_net_ver
p2sh_net_ver
p2wpkh_hrp
p2wpkh_wit_ver
p2tr_hrp
p2tr_wit_ver
wif_net_ver
aBitcoinMainNet
T uBitcoin TestNet
aBTC
aBitcoinTestNet
T uBitcoin RegTest
aBTC
aBitcoinRegTest
T uBitcoin Cash
aBCH
p2pkh_std_hrp
bitcoincash
p2pkh_std_net_ver
p2pkh_legacy_net_ver
p2sh_std_hrp
p2sh_std_net_ver
d ap2sh_legacy_net_ver
aBitcoinCashMainNet
T uBitcoin Cash TestNet
aBCH
bchtest
aBitcoinCashTestNet
T uBitcoin Cash SLP
aSLP
simpleledger
aBitcoinCashSlpMainNet
T uBitcoin Cash SLP TestNet
aSLP
slptest
aBitcoinCashSlpTestNet
T aBitcoinSV
aBSV
aBitcoinSvMainNet
T uBitcoinSV TestNet
aBSV
aBitcoinSvTestNet
T aCardano
aADA
D aaddr_hrp
staking_addr_hrp
addr
stake
aCardanoMainNet
T uCardano TestNet
aADA
D aaddr_hrp
staking_addr_hrp
addr_test
stake_test
aCardanoTestNet
T aCelo
aCELO
aCelo
T aCertik
aCTK
aCERTIK
aCertik
T aChainX
aPCX
D aaddr_ss58_format
l,aChainX
T aChihuahua
aHUAHUA
aCHIHUAHUA
aChihuahua
T aCosmos
aATOM
aCOSMOS
aCosmos
T aDash
aDASH
D ap2pkh_net_ver
p2sh_net_ver
wif_net_ver
dLd d aDashMainNet
T uDash TestNet
aDASH
d d aDashTestNet
T aDogecoin
aDOGE
D ap2pkh_net_ver
p2sh_net_ver
wif_net_ver
d d d aDogecoinMainNet
T uDogecoin TestNet
aDOGE
dqd aDogecoinTestNet
T aeCash
aXEC
ecash
aEcashMainNet
T ueCash TestNet
aXEC
ectest
aEcashTestNet
T aEdgeware
aEDG
D aaddr_ss58_format
l aEdgeware
T aMultiversX
aEGLD
aELROND
aElrond
T aEOS
aEOS
D aaddr_prefix
aEOS
aEos
T aErgo
aERGO
aErgoMainNet
T uErgo TestNet
aERGO
aErgoTestNet
T aEthereum
aETH
aEthereum
T uEthereum Classic
aETC
aEthereumClassic
T uFantom Opera
aFTM
aFantomOpera
T uFetch.ai
aFET
aFETCH_AI
aFetchAi
T aFilecoin
aFIL
D aaddr_prefix
wfaFilecoin
T uGeneric Substrate

D aaddr_ss58_format
l*aGenericSubstrate
T uHarmony One
aONE
aHARMONY_ONE
aHarmonyOne
T uHuobi Token
aHT
aHuobiChain
T aIcon
aICX
D aaddr_prefix
hx
aIcon
T aInjective
aINJ
aINJECTIVE
aInjective
T uIRIS Network
aIRIS
aIRIS_NETWORK
aIrisNet
T aKarura
aKAR
D aaddr_ss58_format
l aKarura
T aKava
aKAVA
aKAVA
aKava
T aKusama
aKSM
D aaddr_ss58_format
l aKusama
T aLitecoin
aLTC
d0ap2pkh_depr_net_ver
d2ap2sh_depr_net_ver
aLITECOIN_MAINNET
d aLitecoinMainNet
T uLitecoin TestNet
aLTC
d:aLITECOIN_TESTNET
aLitecoinTestNet
T aMetis
aMETIS
aMetis
T aMonero
aXMR
D aaddr_net_ver
addr_int_net_ver
subaddr_net_ver
d d d*aMoneroMainNet
T uMonero StageNet
aXMR
D aaddr_net_ver
addr_int_net_ver
subaddr_net_ver
d d d$aMoneroStageNet
T uMonero TestNet
aXMR
D aaddr_net_ver
addr_int_net_ver
subaddr_net_ver
d5d6d?aMoneroTestNet
T aMoonbeam
aGLMR
D aaddr_ss58_format
l
aMoonbeam
T aMoonriver
aMOVR
D aaddr_ss58_format
l
aMoonriver
T aNano
aNANO
D aaddr_prefix
nano_
aNano
T uNear Protocol
aNEAR
aNearProtocol
T aNEO
aNEO
D aaddr_ver
d aNeo
T aNineChroniclesGold
aNCG
aNineChroniclesGold
T aOKExChain
aOKT
aOKEX_CHAIN
aOkexChain
T aOntology
aONT
aOntology
T aOptimism
aOP
aOptimism
T aOsmosis
aOSMO
aOSMOSIS
aOsmosis
T uPhala Network
aPHA
D aaddr_ss58_format
l aPhala
T uPi Network
aPI
aPiNetwork
T uPlasm Network
aPLM
D aaddr_ss58_format
l aPlasm
T aPolkadot
aDOT
D aaddr_ss58_format
l
aPolkadot
T aPolygon
aMATIC
aPolygon
T aRipple
aXRP
aRipple
T uSecret Network
aSCRT
aSECRET_NETWORK
aSecretNetwork
T aSolana
aSOL
aSolana
T aSora
aXOR
D aaddr_ss58_format
lEaSora
T aStafi
aFIS
aSTAFI
addr_ss58_format
l aStafi
T aStellar
aXLM
aStellar
T aSui
aSUI
aSui
T aTerra
aLUNA
aTERRA
aTerra
T aTezos
aXTZ
aTezos
T uTheta Network
aTHETA
aTheta
T aTron
aTRX
D aaddr_prefix
dAaTron
T aVeChain
aVET
aVeChain
T aVerge
aXVG
D ap2pkh_net_ver
wif_net_ver
d d aVerge
T aZcash
aZEC
c
c
aZcashMainNet
T uZcash TestNet
aZEC
c %
c
aZcashTestNet
T aZilliqa
aZIL
aZILLIQA
aZilliqa
ubip_utils\coin_conf\coins_conf.py
u<module bip_utils.coin_conf.coins_conf>
T a__class__

a__spec__
.bip_utils.coin_conf
a__doc__
a__file__
path
dirname
join
environ
get
T aNUITKA_PACKAGE_bip_utils
u\not_existing
coin_conf
T aNUITKA_PACKAGE_bip_utils_coin_conf
u\not_existing
a__path__
origin
has_location
submodule_search_locations
a__cached__
ubip_utils.coin_conf.coin_conf
T aCoinConf
aCoinConf
ubip_utils.coin_conf.coins_conf
T aCoinsConf
aCoinsConf
ubip_utils\coin_conf\__init__.py
u<module bip_utils.coin_conf>

a__spec__
.bip_utils
7
a__doc__
a__file__
path
dirname
environ
get
T aNUITKA_PACKAGE_bip_utils
u\not_existing
a__path__
origin
has_location
submodule_search_locations
a__cached__
ubip_utils._version
T a__version__
a__version__
ubip_utils.addr
T{aAdaByronAddrDecoder
aAdaByronAddrTypes
aAdaByronIcarusAddr
aAdaByronIcarusAddrEncoder
aAdaByronLegacyAddr
aAdaByronLegacyAddrEncoder
aAdaShelleyAddr
aAdaShelleyAddrDecoder
aAdaShelleyAddrEncoder
aAdaShelleyAddrNetworkTags
aAdaShelleyRewardAddr
aAdaShelleyRewardAddrDecoder
aAdaShelleyRewardAddrEncoder
aAdaShelleyStakingAddr
aAdaShelleyStakingAddrDecoder
aAdaShelleyStakingAddrEncoder
aAlgoAddr
aAlgoAddrDecoder
aAlgoAddrEncoder
aAptosAddr
aAptosAddrDecoder
aAptosAddrEncoder
aAtomAddr
aAtomAddrDecoder
aAtomAddrEncoder
aAvaxPChainAddr
aAvaxPChainAddrDecoder
aAvaxPChainAddrEncoder
aAvaxXChainAddr
aAvaxXChainAddrDecoder
aAvaxXChainAddrEncoder
aBchAddrConverter
aBchP2PKHAddr
aBchP2PKHAddrDecoder
aBchP2PKHAddrEncoder
aBchP2SHAddr
aBchP2SHAddrDecoder
aBchP2SHAddrEncoder
aEgldAddr
aEgldAddrDecoder
aEgldAddrEncoder
aEosAddr
aEosAddrDecoder
aEosAddrEncoder
aErgoNetworkTypes
aErgoP2PKHAddr
aErgoP2PKHAddrDecoder
aErgoP2PKHAddrEncoder
aEthAddr
aEthAddrDecoder
aEthAddrEncoder
aFilSecp256k1Addr
aFilSecp256k1AddrDecoder
aFilSecp256k1AddrEncoder
aIcxAddr
aIcxAddrDecoder
aIcxAddrEncoder
aInjAddr
aInjAddrDecoder
aInjAddrEncoder
aNanoAddr
aNanoAddrDecoder
aNanoAddrEncoder
aNearAddr
aNearAddrDecoder
aNearAddrEncoder
aNeoAddr
aNeoAddrDecoder
aNeoAddrEncoder
aOkexAddr
aOkexAddrDecoder
aOkexAddrEncoder
aOneAddr
aOneAddrDecoder
aOneAddrEncoder
aP2PKHAddr
aP2PKHAddrDecoder
aP2PKHAddrEncoder
aP2PKHPubKeyModes
aP2SHAddr
aP2SHAddrDecoder
aP2SHAddrEncoder
aP2TRAddr
aP2TRAddrDecoder
aP2TRAddrEncoder
aP2WPKHAddr
aP2WPKHAddrDecoder
aP2WPKHAddrEncoder
aSolAddr
aSolAddrDecoder
aSolAddrEncoder
aSubstrateEd25519Addr
aSubstrateEd25519AddrDecoder
aSubstrateEd25519AddrEncoder
aSubstrateSr25519Addr
aSubstrateSr25519AddrDecoder
aSubstrateSr25519AddrEncoder
aSuiAddr
aSuiAddrDecoder
aSuiAddrEncoder
aTrxAddr
aTrxAddrDecoder
aTrxAddrEncoder
aXlmAddr
aXlmAddrDecoder
aXlmAddrEncoder
aXlmAddrTypes
aXmrAddr
aXmrAddrDecoder
aXmrAddrEncoder
aXmrIntegratedAddr
aXmrIntegratedAddrDecoder
aXmrIntegratedAddrEncoder
aXrpAddr
aXrpAddrDecoder
aXrpAddrEncoder
aXtzAddr
aXtzAddrDecoder
aXtzAddrEncoder
aXtzAddrPrefixes
aZilAddr
aZilAddrDecoder
aZilAddrEncoder
aAdaByronAddrDecoder
aAdaByronAddrTypes
aAdaByronIcarusAddr
aAdaByronIcarusAddrEncoder
aAdaByronLegacyAddr
aAdaByronLegacyAddrEncoder
aAdaShelleyAddr
aAdaShelleyAddrDecoder
aAdaShelleyAddrEncoder
aAdaShelleyAddrNetworkTags
aAdaShelleyRewardAddr
aAdaShelleyRewardAddrDecoder
aAdaShelleyRewardAddrEncoder
aAdaShelleyStakingAddr
aAdaShelleyStakingAddrDecoder
aAdaShelleyStakingAddrEncoder
aAlgoAddr
aAlgoAddrDecoder
aAlgoAddrEncoder
aAptosAddr
aAptosAddrDecoder
aAptosAddrEncoder
aAtomAddr
aAtomAddrDecoder
aAtomAddrEncoder
aAvaxPChainAddr
aAvaxPChainAddrDecoder
aAvaxPChainAddrEncoder
aAvaxXChainAddr
aAvaxXChainAddrDecoder
aAvaxXChainAddrEncoder
aBchAddrConverter
aBchP2PKHAddr
aBchP2PKHAddrDecoder
aBchP2PKHAddrEncoder
aBchP2SHAddr
aBchP2SHAddrDecoder
aBchP2SHAddrEncoder
aEgldAddr
aEgldAddrDecoder
aEgldAddrEncoder
aEosAddr
aEosAddrDecoder
aEosAddrEncoder
aErgoNetworkTypes
aErgoP2PKHAddr
aErgoP2PKHAddrDecoder
aErgoP2PKHAddrEncoder
aEthAddr
aEthAddrDecoder
aEthAddrEncoder
aFilSecp256k1Addr
aFilSecp256k1AddrDecoder
aFilSecp256k1AddrEncoder
aIcxAddr
aIcxAddrDecoder
aIcxAddrEncoder
aInjAddr
aInjAddrDecoder
aInjAddrEncoder
aNanoAddr
aNanoAddrDecoder
aNanoAddrEncoder
aNearAddr
aNearAddrDecoder
aNearAddrEncoder
aNeoAddr
aNeoAddrDecoder
aNeoAddrEncoder
aOkexAddr
aOkexAddrDecoder
aOkexAddrEncoder
aOneAddr
aOneAddrDecoder
aOneAddrEncoder
aP2PKHAddr
aP2PKHAddrDecoder
aP2PKHAddrEncoder
aP2PKHPubKeyModes
aP2SHAddr
aP2SHAddrDecoder
aP2SHAddrEncoder
aP2TRAddr
aP2TRAddrDecoder
aP2TRAddrEncoder
aP2WPKHAddr
aP2WPKHAddrDecoder
aP2WPKHAddrEncoder
aSolAddr
aSolAddrDecoder
aSolAddrEncoder
aSubstrateEd25519Addr
aSubstrateEd25519AddrDecoder
aSubstrateEd25519AddrEncoder
aSubstrateSr25519Addr
aSubstrateSr25519AddrDecoder
aSubstrateSr25519AddrEncoder
aSuiAddr
aSuiAddrDecoder
aSuiAddrEncoder
aTrxAddr
aTrxAddrDecoder
aTrxAddrEncoder
aXlmAddr
aXlmAddrDecoder
aXlmAddrEncoder
aXlmAddrTypes
aXmrAddr
aXmrAddrDecoder
aXmrAddrEncoder
aXmrIntegratedAddr
aXmrIntegratedAddrDecoder
aXmrIntegratedAddrEncoder
aXrpAddr
aXrpAddrDecoder
aXrpAddrEncoder
aXtzAddr
aXtzAddrDecoder
aXtzAddrEncoder
aXtzAddrPrefixes
aZilAddr
aZilAddrDecoder
aZilAddrEncoder
ubip_utils.algorand.mnemonic
T
aAlgorandEntropyBitLen
aAlgorandEntropyGenerator
aAlgorandLanguages
aAlgorandMnemonic
aAlgorandMnemonicDecoder
aAlgorandMnemonicEncoder
aAlgorandMnemonicGenerator
aAlgorandMnemonicValidator
aAlgorandSeedGenerator
aAlgorandWordsNum
aAlgorandEntropyBitLen
aAlgorandEntropyGenerator
aAlgorandLanguages
aAlgorandMnemonic
aAlgorandMnemonicDecoder
aAlgorandMnemonicEncoder
aAlgorandMnemonicGenerator
aAlgorandMnemonicValidator
aAlgorandSeedGenerator
aAlgorandWordsNum
ubip_utils.base58
T aBase58Alphabets
aBase58ChecksumError
aBase58Decoder
aBase58Encoder
aBase58XmrDecoder
aBase58XmrEncoder
aBase58Alphabets
aBase58ChecksumError
aBase58Decoder
aBase58Encoder
aBase58XmrDecoder
aBase58XmrEncoder
ubip_utils.bech32
T aBchBech32Decoder
aBchBech32Encoder
aBech32ChecksumError
aBech32Decoder
aBech32Encoder
aSegwitBech32Decoder
aSegwitBech32Encoder
aBchBech32Decoder
aBchBech32Encoder
aBech32ChecksumError
aBech32Decoder
aBech32Encoder
aSegwitBech32Decoder
aSegwitBech32Encoder
ubip_utils.bip.bip32
T aBip32ChainCode
aBip32Depth
aBip32DeserializedKey
aBip32Ed25519Blake2bSlip
aBip32Ed25519Kholaw
aBip32Ed25519Slip
aBip32FingerPrint
aBip32KeyData
aBip32KeyDeserializer
aBip32KeyError
aBip32KeyIndex
aBip32KeyNetVersions
aBip32KholawEd25519
aBip32Nist256p1
aBip32Path
aBip32PathError
aBip32PathParser
aBip32PrivateKey
aBip32PrivateKeySerializer
aBip32PublicKey
aBip32PublicKeySerializer
aBip32Secp256k1
aBip32Slip10Ed25519
aBip32Slip10Ed25519Blake2b
aBip32Slip10Nist256p1
aBip32Slip10Secp256k1
aBip32Utils
aBip32ChainCode
aBip32Depth
aBip32DeserializedKey
aBip32Ed25519Blake2bSlip
aBip32Ed25519Kholaw
aBip32Ed25519Slip
aBip32FingerPrint
aBip32KeyData
aBip32KeyDeserializer
aBip32KeyError
aBip32KeyIndex
aBip32KeyNetVersions
aBip32KholawEd25519
aBip32Nist256p1
aBip32Path
aBip32PathError
aBip32PathParser
aBip32PrivateKey
aBip32PrivateKeySerializer
aBip32PublicKey
aBip32PublicKeySerializer
aBip32Secp256k1
aBip32Slip10Ed25519
aBip32Slip10Ed25519Blake2b
aBip32Slip10Nist256p1
aBip32Slip10Secp256k1
aBip32Utils
ubip_utils.bip.bip38
T aBip38Decrypter
aBip38EcKeysGenerator
aBip38Encrypter
aBip38PubKeyModes
aBip38Decrypter
aBip38EcKeysGenerator
aBip38Encrypter
aBip38PubKeyModes
ubip_utils.bip.bip39
T
aBip39EntropyBitLen
aBip39EntropyGenerator
aBip39Languages
aBip39Mnemonic
aBip39MnemonicDecoder
aBip39MnemonicEncoder
aBip39MnemonicGenerator
aBip39MnemonicValidator
aBip39SeedGenerator
aBip39WordsNum
aBip39EntropyBitLen
aBip39EntropyGenerator
aBip39Languages
aBip39Mnemonic
aBip39MnemonicDecoder
aBip39MnemonicEncoder
aBip39MnemonicGenerator
aBip39MnemonicValidator
aBip39SeedGenerator
aBip39WordsNum
ubip_utils.bip.bip44
T aBip44
aBip44
ubip_utils.bip.bip44_base
T aBip44Changes
aBip44DepthError
aBip44Levels
aBip44PrivateKey
aBip44PublicKey
aBip44Changes
aBip44DepthError
aBip44Levels
aBip44PrivateKey
aBip44PublicKey
ubip_utils.bip.bip49
T aBip49
aBip49
ubip_utils.bip.bip84
T aBip84
aBip84
ubip_utils.bip.bip86
T aBip86
aBip86
ubip_utils.bip.conf.bip44
T aBip44Coins
aBip44Conf
aBip44ConfGetter
aBip44Coins
aBip44Conf
aBip44ConfGetter
ubip_utils.bip.conf.bip49
T aBip49Coins
aBip49Conf
aBip49ConfGetter
aBip49Coins
aBip49Conf
aBip49ConfGetter
ubip_utils.bip.conf.bip84
T aBip84Coins
aBip84Conf
aBip84ConfGetter
aBip84Coins
aBip84Conf
aBip84ConfGetter
ubip_utils.bip.conf.bip86
T aBip86Coins
aBip86Conf
aBip86ConfGetter
aBip86Coins
aBip86Conf
aBip86ConfGetter
ubip_utils.brainwallet
T aBrainwallet
aBrainwalletAlgos
aBrainwalletCoins
aIBrainwalletAlgo
aBrainwallet
aBrainwalletAlgos
aBrainwalletCoins
aIBrainwalletAlgo
ubip_utils.cardano.bip32
T aCardanoByronLegacyBip32
aCardanoIcarusBip32
aCardanoByronLegacyBip32
aCardanoIcarusBip32
ubip_utils.cardano.byron
T aCardanoByronLegacy
aCardanoByronLegacy
ubip_utils.cardano.cip1852
T aCip1852
aCip1852
ubip_utils.cardano.cip1852.conf
T aCip1852Coins
aCip1852Conf
aCip1852ConfGetter
aCip1852Coins
aCip1852Conf
aCip1852ConfGetter
ubip_utils.cardano.mnemonic
T aCardanoByronLegacySeedGenerator
aCardanoIcarusSeedGenerator
aCardanoByronLegacySeedGenerator
aCardanoIcarusSeedGenerator
ubip_utils.cardano.shelley
T aCardanoShelley
aCardanoShelleyPrivateKeys
aCardanoShelleyPublicKeys
aCardanoShelley
aCardanoShelleyPrivateKeys
aCardanoShelleyPublicKeys
ubip_utils.coin_conf
T aCoinsConf
aCoinsConf
ubip_utils.ecc
T!aEd25519
aEd25519Blake2b
aEd25519Blake2bPoint
aEd25519Blake2bPrivateKey
aEd25519Blake2bPublicKey
aEd25519Kholaw
aEd25519KholawPoint
aEd25519KholawPrivateKey
aEd25519KholawPublicKey
aEd25519Monero
aEd25519MoneroPoint
aEd25519MoneroPrivateKey
aEd25519MoneroPublicKey
aEd25519Point
aEd25519PrivateKey
aEd25519PublicKey
aEllipticCurveGetter
aEllipticCurveTypes
aIPoint
aIPrivateKey
aIPublicKey
aNist256p1
aNist256p1Point
aNist256p1PrivateKey
aNist256p1PublicKey
aSecp256k1
aSecp256k1Point
aSecp256k1PrivateKey
aSecp256k1PublicKey
aSr25519
aSr25519Point
aSr25519PrivateKey
aSr25519PublicKey
aEd25519
aEd25519Blake2b
aEd25519Blake2bPoint
aEd25519Blake2bPrivateKey
aEd25519Blake2bPublicKey
aEd25519Kholaw
aEd25519KholawPoint
aEd25519KholawPrivateKey
aEd25519KholawPublicKey
aEd25519Monero
aEd25519MoneroPoint
aEd25519MoneroPrivateKey
aEd25519MoneroPublicKey
aEd25519Point
aEd25519PrivateKey
aEd25519PublicKey
aEllipticCurveGetter
aEllipticCurveTypes
aIPoint
aIPrivateKey
aIPublicKey
aNist256p1
aNist256p1Point
aNist256p1PrivateKey
aNist256p1PublicKey
aSecp256k1
aSecp256k1Point
aSecp256k1PrivateKey
aSecp256k1PublicKey
aSr25519
aSr25519Point
aSr25519PrivateKey
aSr25519PublicKey
ubip_utils.electrum
T aElectrumV1
aElectrumV2Segwit
aElectrumV2Standard
aElectrumV1
aElectrumV2Segwit
aElectrumV2Standard
ubip_utils.electrum.mnemonic_v1
T
aElectrumV1EntropyBitLen
aElectrumV1EntropyGenerator
aElectrumV1Languages
aElectrumV1Mnemonic
aElectrumV1MnemonicDecoder
aElectrumV1MnemonicEncoder
aElectrumV1MnemonicGenerator
aElectrumV1MnemonicValidator
aElectrumV1SeedGenerator
aElectrumV1WordsNum
aElectrumV1EntropyBitLen
aElectrumV1EntropyGenerator
aElectrumV1Languages
aElectrumV1Mnemonic
aElectrumV1MnemonicDecoder
aElectrumV1MnemonicEncoder
aElectrumV1MnemonicGenerator
aElectrumV1MnemonicValidator
aElectrumV1SeedGenerator
aElectrumV1WordsNum
ubip_utils.electrum.mnemonic_v2
T aElectrumV2EntropyBitLen
aElectrumV2EntropyGenerator
aElectrumV2Languages
aElectrumV2Mnemonic
aElectrumV2MnemonicDecoder
aElectrumV2MnemonicEncoder
aElectrumV2MnemonicGenerator
aElectrumV2MnemonicTypes
aElectrumV2MnemonicValidator
aElectrumV2SeedGenerator
aElectrumV2WordsNum
aElectrumV2EntropyBitLen
aElectrumV2EntropyGenerator
aElectrumV2Languages
aElectrumV2Mnemonic
aElectrumV2MnemonicDecoder
aElectrumV2MnemonicEncoder
aElectrumV2MnemonicGenerator
aElectrumV2MnemonicTypes
aElectrumV2MnemonicValidator
aElectrumV2SeedGenerator
aElectrumV2WordsNum
ubip_utils.monero
T aMonero
aMoneroKeyError
aMoneroPrivateKey
aMoneroPublicKey
aMoneroSubaddress
aMonero
aMoneroKeyError
aMoneroPrivateKey
aMoneroPublicKey
aMoneroSubaddress
ubip_utils.monero.conf
T aMoneroCoins
aMoneroConf
aMoneroCoins
aMoneroConf
ubip_utils.monero.mnemonic
T aMoneroEntropyBitLen
aMoneroEntropyGenerator
aMoneroLanguages
aMoneroMnemonic
aMoneroMnemonicDecoder
aMoneroMnemonicEncoder
aMoneroMnemonicGenerator
aMoneroMnemonicNoChecksumEncoder
aMoneroMnemonicValidator
aMoneroMnemonicWithChecksumEncoder
aMoneroSeedGenerator
aMoneroWordsNum
aMoneroEntropyBitLen
aMoneroEntropyGenerator
aMoneroLanguages
aMoneroMnemonic
aMoneroMnemonicDecoder
aMoneroMnemonicEncoder
aMoneroMnemonicGenerator
aMoneroMnemonicNoChecksumEncoder
aMoneroMnemonicValidator
aMoneroMnemonicWithChecksumEncoder
aMoneroSeedGenerator
aMoneroWordsNum
ubip_utils.slip.slip32
T aSlip32DeserializedKey
aSlip32KeyDeserializer
aSlip32PrivateKeySerializer
aSlip32PublicKeySerializer
aSlip32DeserializedKey
aSlip32KeyDeserializer
aSlip32PrivateKeySerializer
aSlip32PublicKeySerializer
ubip_utils.solana
T aSplToken
aSplToken
ubip_utils.ss58
T aSS58ChecksumError
aSS58Decoder
aSS58Encoder
aSS58ChecksumError
aSS58Decoder
aSS58Encoder
ubip_utils.substrate
T aSubstrate
aSubstrateKeyError
aSubstratePath
aSubstratePathElem
aSubstratePathError
aSubstratePathParser
aSubstratePrivateKey
aSubstratePublicKey
aSubstrate
aSubstrateKeyError
aSubstratePath
aSubstratePathElem
aSubstratePathError
aSubstratePathParser
aSubstratePrivateKey
aSubstratePublicKey
ubip_utils.substrate.conf
T aSubstrateCoins
aSubstrateConf
aSubstrateCoins
aSubstrateConf
ubip_utils.substrate.mnemonic
T aSubstrateBip39SeedGenerator
aSubstrateBip39SeedGenerator
ubip_utils.substrate.scale
T aSubstrateScaleBytesEncoder
aSubstrateScaleCUintEncoder
aSubstrateScaleU8Encoder
aSubstrateScaleU16Encoder
aSubstrateScaleU32Encoder
aSubstrateScaleU64Encoder
aSubstrateScaleU128Encoder
aSubstrateScaleU256Encoder
aSubstrateScaleBytesEncoder
aSubstrateScaleCUintEncoder
aSubstrateScaleU8Encoder
aSubstrateScaleU16Encoder
aSubstrateScaleU32Encoder
aSubstrateScaleU64Encoder
aSubstrateScaleU128Encoder
aSubstrateScaleU256Encoder
ubip_utils.utils.crypto
T aAesEcbDecrypter
aAesEcbEncrypter
aBlake2b
aBlake2b160
aBlake2b224
aBlake2b256
aChaCha20Poly1305
aCrc32
aDoubleSha256
aHash160
aHmacSha256
aHmacSha512
aKekkak256
aPbkdf2HmacSha512
aRipemd160
aScrypt
aSha3_256
aSha256
aSha512
aSha512_256
aXModemCrc
aAesEcbDecrypter
aAesEcbEncrypter
aBlake2b
aBlake2b160
aBlake2b224
aBlake2b256
aChaCha20Poly1305
aCrc32
aDoubleSha256
aHash160
aHmacSha256
aHmacSha512
aKekkak256
aPbkdf2HmacSha512
aRipemd160
aScrypt
aSha3_256
aSha256
aSha512
aSha512_256
aXModemCrc
ubip_utils.utils.misc
T aAlgoUtils
aBitUtils
aBytesUtils
aDataBytes
aIntegerUtils
aStringUtils
aAlgoUtils
aBitUtils
aBytesUtils
aDataBytes
aIntegerUtils
aStringUtils
ubip_utils.utils.mnemonic
T aMnemonicChecksumError
aMnemonicChecksumError
ubip_utils.wif
T aWifDecoder
aWifEncoder
aWifPubKeyModes
aWifDecoder
aWifEncoder
aWifPubKeyModes
ubip_utils\__init__.py
u<module bip_utils>

a__spec__
.bip_utils.ecc.common
r
a__doc__
a__file__
path
dirname
join
environ
get
T aNUITKA_PACKAGE_bip_utils
u\not_existing
uecc\common
T aNUITKA_PACKAGE_bip_utils_ecc
u\not_existing
common
T aNUITKA_PACKAGE_bip_utils_ecc_common
u\not_existing
a__path__
origin
has_location
submodule_search_locations
a__cached__
ubip_utils\ecc\common\__init__.py
u<module bip_utils.ecc.common>

a__spec__
.bip_utils.ecc.common.dummy_point
g
aBytesUtils
aToInteger
aDummyPointConst
aPOINT_COORD_BYTE_LEN

Construct class from point bytes.
Args:
point_bytes (bytes): Point bytes
Returns:
IPoint: IPoint object

Construct class from point coordinates.
Args:
x (int): X coordinate of the point
y (int): Y coordinate of the point
Returns:
IPoint: IPoint object
uInvalid point object type
m_x
m_y

Construct class from point object.
Args:
point_obj (class): Point object
Raises:
TypeError: If point object is not of the correct type

Get the coordinate length.
Returns:
int: Coordinate key length

Get point X coordinate.
Returns:
int: Point X coordinate

Get point Y coordinate.
Returns:
int: Point Y coordinate
aIntegerUtils
aToBytes
T abytes_num
aDataBytes

Return the point raw bytes.
Returns:
DataBytes object: DataBytes object
aRaw

Return the encoded point raw bytes.
Returns:
DataBytes object: DataBytes object

Return the decoded point raw bytes.
Returns:
DataBytes object: DataBytes object
wXwYu
Add point to another point.
Args:
point (IPoint object): IPoint object
Returns:
IPoint object: IPoint object
a__add__

Multiply point by a scalar.
Args:
scalar (int): scalar
Returns:
IPoint object: IPoint object
a__mul__
uModule with helper class for representing a dummy point.
a__doc__
a__file__
origin
has_location
a__cached__
abc
T aABC
aABC
aAny
ubip_utils.ecc.common.ipoint
T aIPoint
aIPoint
ubip_utils.utils.misc
T aBytesUtils
aDataBytes
aIntegerUtils
