# Reconstructed from integrated Nuitka blob
# Module: ubip_utils.bip.conf.bip44.bip44_conf_getter

uClass container for BIP44 configuration getter constants.
a__qualname__
a__annotations__
aAKASH_NETWORK
aAkashNetwork
aALGORAND
aAlgorand
aAPTOS
aAptos
aARBITRUM
aArbitrum
aAVAX_C_CHAIN
aAvaxCChain
aAVAX_P_CHAIN
aAvaxPChain
aAVAX_X_CHAIN
aAvaxXChain
aAXELAR
aAxelar
aBAND_PROTOCOL
aBandProtocol
aBINANCE_CHAIN
aBinanceChain
aBINANCE_SMART_CHAIN
aBinanceSmartChain
aBITCOIN
aBitcoinMainNet
aBITCOIN_REGTEST
aBitcoinRegTest
aBITCOIN_TESTNET
aBitcoinTestNet
aBITCOIN_CASH
aBitcoinCashMainNet
aBITCOIN_CASH_TESTNET
aBitcoinCashTestNet
aBITCOIN_CASH_SLP
aBitcoinCashSlpMainNet
aBITCOIN_CASH_SLP_TESTNET
aBitcoinCashSlpTestNet
aBITCOIN_SV
aBitcoinSvMainNet
aBITCOIN_SV_TESTNET
aBitcoinSvTestNet
aCARDANO_BYRON_ICARUS
aCardanoByronIcarus
aCARDANO_BYRON_LEDGER
aCardanoByronLedger
aCELO
aCelo
aCERTIK
aCertik
aCHIHUAHUA
aChihuahua
aCOSMOS
aCosmos
aDASH
aDashMainNet
aDASH_TESTNET
aDashTestNet
aDOGECOIN
aDogecoinMainNet
aDOGECOIN_TESTNET
aDogecoinTestNet
aECASH
aEcashMainNet
aECASH_TESTNET
aEcashTestNet
aELROND
aElrond
aEOS
aEos
aERGO
aErgoMainNet
aERGO_TESTNET
aErgoTestNet
aETHEREUM
aEthereum
aETHEREUM_CLASSIC
aEthereumClassic
aFANTOM_OPERA
aFantomOpera
aFETCH_AI
aFetchAi
aFETCH_AI_ETH
aFetchAiEth
aFILECOIN
aFilecoin
aHARMONY_ONE_ATOM
aHarmonyOneAtom
aHARMONY_ONE_ETH
aHarmonyOneEth
aHARMONY_ONE_METAMASK
aHarmonyOneMetamask
aHUOBI_CHAIN
aHuobiChain
aICON
aIcon
aINJECTIVE
aInjective
aIRIS_NET
aIrisNet
aKAVA
aKava
aKUSAMA_ED25519_SLIP
aKusamaEd25519Slip
aLITECOIN
aLitecoinMainNet
aLITECOIN_TESTNET
aLitecoinTestNet
aMETIS
aMetis
aMONERO_ED25519_SLIP
aMoneroEd25519Slip
aMONERO_SECP256K1
aMoneroSecp256k1
aMULTIVERSX
aNANO
aNano
aNEAR_PROTOCOL
aNearProtocol
aNEO
aNeo
aNINE_CHRONICLES_GOLD
aNineChroniclesGold
aOKEX_CHAIN_ATOM
aOkexChainAtom
aOKEX_CHAIN_ATOM_OLD
aOkexChainAtomOld
aOKEX_CHAIN_ETH
aOkexChainEth
aONTOLOGY
aOntology
aOPTIMISM
aOptimism
aOSMOSIS
aOsmosis
aPI_NETWORK
aPiNetwork
aPOLKADOT_ED25519_SLIP
aPolkadotEd25519Slip
aPOLYGON
aPolygon
aRIPPLE
aRipple
aSECRET_NETWORK_OLD
aSecretNetworkOld
aSECRET_NETWORK_NEW
aSecretNetworkNew
aSOLANA
aSolana
aSTAFI
aStafi
aSTELLAR
aStellar
aSUI
aSui
aTERRA
aTerra
aTEZOS
aTezos
aTHETA
aTheta
aTRON
aTron
aVECHAIN
aVeChain
aVERGE
aVerge
aZCASH
aZcashMainNet
aZCASH_TESTNET
aZcashTestNet
aZILLIQA
aZilliqa

BIP44 configuration getter class.
It allows to get the BIP44 configuration of a specific coin.
aBip44ConfGetter
coin_type
return
aGetConfig
uBip44ConfGetter.GetConfig
ubip_utils\bip\conf\bip44\bip44_conf_getter.py
u<module bip_utils.bip.conf.bip44.bip44_conf_getter>
T a__class__
T acoin_type

a__spec__
.bip_utils.bip.conf.bip44
a__doc__
a__file__
path
dirname
join
environ
get
T aNUITKA_PACKAGE_bip_utils
u\not_existing
ubip\conf\bip44
T aNUITKA_PACKAGE_bip_utils_bip
u\not_existing
uconf\bip44
T aNUITKA_PACKAGE_bip_utils_bip_conf
u\not_existing
bip44
T aNUITKA_PACKAGE_bip_utils_bip_conf_bip44
u\not_existing
a__path__
origin
has_location
submodule_search_locations
a__cached__
ubip_utils.bip.conf.bip44.bip44_coins
T aBip44Coins
aBip44Coins
ubip_utils.bip.conf.bip44.bip44_conf
T aBip44Conf
aBip44Conf
ubip_utils.bip.conf.bip44.bip44_conf_getter
T aBip44ConfGetter
aBip44ConfGetter
ubip_utils\bip\conf\bip44\__init__.py
u<module bip_utils.bip.conf.bip44>

a__spec__
.bip_utils.bip.conf.bip49.bip49_coins
0
uModule for BIP49 coins enum.
a__doc__
a__file__
origin
has_location
a__cached__
enum
T aauto
unique
auto
unique
ubip_utils.bip.conf.common.bip_coins
T aBipCoins
aBipCoins
a__prepare__
aBip49Coins
a__getitem__
u%s.__prepare__() must return a mapping, not %s
a__name__
u<metaclass>
