# Reconstructed from integrated Nuitka blob
# Module: unacl.public


The public key counterpart to an Curve25519 :class:`nacl.public.PrivateKey`
for encrypting messages.
:param public_key: [:class:`bytes`] Encoded Curve25519 public key
:param encoder: A class that is able to decode the `public_key`
:cvar SIZE: The size that the public key is required to be
a__qualname__
a__annotations__
crypto_box_PUBLICKEYBYTES
int
bytes
encoder
a__init__
uPublicKey.__init__
return
a__bytes__
uPublicKey.__bytes__
a__hash__
uPublicKey.__hash__
other
object
bool
a__eq__
uPublicKey.__eq__
a__ne__
uPublicKey.__ne__
a__orig_bases__

Private key for decrypting messages using the Curve25519 algorithm.
.. warning:: This **must** be protected and remain secret. Anyone who
knows the value of your :class:`~nacl.public.PrivateKey` can decrypt
ny message encrypted by the corresponding
:class:`~nacl.public.PublicKey`
:param private_key: The private key used to decrypt messages
:param encoder: The encoder class used to decode the given keys
:cvar SIZE: The size that the private key is required to be
:cvar SEED_SIZE: The size that the seed used to generate the
private key is required to be
crypto_box_SECRETKEYBYTES
crypto_box_SEEDBYTES
private_key
uPrivateKey.__init__
classmethod
seed
from_seed
uPrivateKey.from_seed
uPrivateKey.__bytes__
uPrivateKey.__hash__
uPrivateKey.__eq__
uPrivateKey.__ne__
D areturn
aPrivateKey
generate
uPrivateKey.generate
T a_Box
aBox
T abound
a_Box
aBox

The Box class boxes and unboxes messages between a pair of keys
The ciphertexts generated by :class:`~nacl.public.Box` include a 16
byte authenticator which is checked as part of the decryption. An invalid
uthenticator will cause the decrypt function to raise an exception. The
uthenticator is not a signature. Once you've decrypted the message you've
demonstrated the ability to create arbitrary valid message, so messages you
send are repudiable. For non-repudiable messages, sign them after
encryption.
:param private_key: :class:`~nacl.public.PrivateKey` used to encrypt and
decrypt messages
:param public_key: :class:`~nacl.public.PublicKey` used to encrypt and
decrypt messages
:cvar NONCE_SIZE: The size that the nonce is required to be.
crypto_box_NONCEBYTES
uBox.__init__
uBox.__bytes__
cls
encoded
uBox.decode
plaintext
nonce
encrypt
uBox.encrypt
ciphertext
decrypt
uBox.decrypt
shared_key
uBox.shared_key
a_Key
aSealedBox

The SealedBox class boxes and unboxes messages addressed to
a specified key-pair by using ephemeral sender's keypairs,
whose private part will be discarded just after encrypting
a single plaintext message.
The ciphertexts generated by :class:`~nacl.public.SecretBox` include
the public part of the ephemeral key before the :class:`~nacl.public.Box`
ciphertext.
:param recipient_key: a :class:`~nacl.public.PublicKey` used to encrypt
messages and derive nonces, or a :class:`~nacl.public.PrivateKey` used
to decrypt messages.
.. versionadded:: 1.2
recipient_key
uSealedBox.__init__
uSealedBox.__bytes__
uSealedBox.encrypt
self
uSealedBox[PrivateKey]
uSealedBox.decrypt
unacl\public.py
u<module nacl.public>
T a__class__
T aself
T aself
other
T aself
private_key
public_key
T aself
private_key
encoder
raw_public_key
T aself
public_key
encoder
T aself
recipient_key
T acls
encoded
encoder
box
T aself
ciphertext
nonce
encoder
plaintext
T aself
ciphertext
encoder
plaintext
T aself
plaintext
nonce
encoder
ciphertext
encoded_nonce
encoded_ciphertext
T aself
plaintext
encoder
ciphertext
encoded_ciphertext
T acls
seed
encoder
raw_pk
raw_sk
T acls

a__spec__
.nacl.signing
g
a_signature
a_message

The signature contained within the :class:`SignedMessage`.

The message contained within the :class:`SignedMessage`.
decode
exc
aTypeError
T uVerifyKey must be created from 32 bytes
nacl
bindings
crypto_sign_PUBLICKEYBYTES
aValueError
uThe key must be exactly %s bytes long
a_key
sodium_memcmp
uVerification signature must be created from %d bytes
crypto_sign_BYTES
uThe signature must be exactly %d bytes long
crypto_sign_open

Verifies the signature of a signed message, returning the message
if it has not been tampered with else raising
:class:`~nacl.signing.BadSignatureError`.
:param smessage: [:class:`bytes`] Either the original messaged or a
signature and message concated together.
:param signature: [:class:`bytes`] If an unsigned message is given for
smessage then the detached signature must be provided.
:param encoder: A class that is able to decode the secret message and
signature.
:rtype: :class:`bytes`
crypto_sign_ed25519_pk_to_curve25519
a_Curve25519_PublicKey

Converts a :class:`~nacl.signing.VerifyKey` to a
:class:`~nacl.public.PublicKey`
:rtype: :class:`~nacl.public.PublicKey`
T uSigningKey must be created from a 32 byte seed
crypto_sign_SEEDBYTES
uThe seed must be exactly %d bytes long
crypto_sign_seed_keypair
a_seed
a_signing_key
aVerifyKey
verify_key
random
encoding
aRawEncoder
T aencoder

Generates a random :class:`~nacl.signing.SigningKey` object.
:rtype: :class:`~nacl.signing.SigningKey`
crypto_sign
encode
aSignedMessage
a_from_parts

Sign a message using this key.
:param message: [:class:`bytes`] The data to be signed.
:param encoder: A class that is used to encode the signed message.
:rtype: :class:`~nacl.signing.SignedMessage`
crypto_sign_ed25519_sk_to_curve25519
a_Curve25519_PrivateKey

Converts a :class:`~nacl.signing.SigningKey` to a
:class:`~nacl.public.PrivateKey`
:rtype: :class:`~nacl.public.PrivateKey`
a__doc__
a__file__
origin
has_location
a__cached__
aOptional
unacl.bindings
T aencoding
T aexceptions
exceptions
unacl.public
T aPrivateKey
aPublicKey
aPrivateKey
aPublicKey
unacl.utils
T aStringFixer
random
aStringFixer
T Obytes
a__prepare__
a__getitem__
u%s.__prepare__() must return a mapping, not %s
a__name__
u<metaclass>
