# Reconstructed from integrated Nuitka blob
# Module: upydantic.aliases

uUsage docs: https://docs.pydantic.dev/2.10/concepts/alias#aliaspath-and-aliaschoices
A data class used by `validation_alias` as a convenience to create aliases.
Attributes:
path: A list of string or integer aliases.
a__qualname__
a__annotations__
ulist[int | str]
D afirst_arg
args
return
str
ustr | int
aNone
a__init__
uAliasPath.__init__
D areturn
ulist[str | int]
uAliasPath.convert_to_aliases
D wdareturn
dict
aAny
search_dict_for_path
uAliasPath.search_dict_for_path
uUsage docs: https://docs.pydantic.dev/2.10/concepts/alias#aliaspath-and-aliaschoices
A data class used by `validation_alias` as a convenience to create aliases.
Attributes:
choices: A list containing a string or `AliasPath`.
ulist[str | AliasPath]
D afirst_choice
choices
return
ustr | AliasPath
ustr | AliasPath
aNone
uAliasChoices.__init__
D areturn
ulist[list[str | int]]
uAliasChoices.convert_to_aliases
uUsage docs: https://docs.pydantic.dev/2.10/concepts/alias#using-an-aliasgenerator
A data class used by `alias_generator` as a convenience to create various aliases.
Attributes:
lias: A callable that takes a field name and returns an alias for it.
validation_alias: A callable that takes a field name and returns a validation alias for it.
serialization_alias: A callable that takes a field name and returns a serialization alias for it.
aAliasGenerator
uCallable[[str], str] | None
uCallable[[str], str | AliasPath | AliasChoices] | None
D aalias_kind
allowed_types
field_name
return
uLiteral['alias', 'validation_alias', 'serialization_alias']
utuple[type[str] | type[AliasPath] | type[AliasChoices], ...]
str
ustr | AliasPath | AliasChoices | None
uAliasGenerator._generate_alias
D afield_name
return
str
utuple[str | None, str | AliasPath | AliasChoices | None, str | None]
generate_aliases
uAliasGenerator.generate_aliases
upydantic\aliases.py
u<module pydantic.aliases>
T a__class__
T aself
first_choice
choices
T aself
first_arg
args
T aself
alias_kind
allowed_types
field_name
alias
alias_generator
T aself
aliases
wcT aself
T aself
field_name
alias
validation_alias
serialization_alias
T aself
wdwvwka__spec__
.pydantic.annotated_handlers
<
uCall the inner handler and get the JsonSchemaValue it returns.
This will call the next JSON schema modifying function up until it calls
into `pydantic.json_schema.GenerateJsonSchema`, which will raise a
`pydantic.errors.PydanticInvalidForJsonSchema` error if it cannot generate
a JSON schema.
Args:
core_schema: A `pydantic_core.core_schema.CoreSchema`.
Returns:
JsonSchemaValue: The JSON schema generated by the inner JSON schema modify
functions.
uGet the real schema for a `{"$ref": ...}` schema.
If the schema given is not a `$ref` schema, it will be returned as is.
This means you don't have to check before calling this function.
Args:
maybe_ref_json_schema: A JsonSchemaValue which may be a `$ref` schema.
Raises:
LookupError: If the ref is not found.
Returns:
JsonSchemaValue: A JsonSchemaValue that has no `$ref`.
uCall the inner handler and get the CoreSchema it returns.
This will call the next CoreSchema modifying function up until it calls
into Pydantic's internal schema generation machinery, which will raise a
`pydantic.errors.PydanticSchemaGenerationError` error if it cannot generate
a CoreSchema for the given source type.
Args:
source_type: The input type.
Returns:
CoreSchema: The `pydantic-core` CoreSchema generated.
uGenerate a schema unrelated to the current context.
Use this function if e.g. you are handling schema generation for a sequence
nd want to generate a schema for its items.
Otherwise, you may end up doing something like applying a `min_length` constraint
that was intended for the sequence itself to its items!
Args:
source_type: The input type.
Returns:
CoreSchema: The `pydantic-core` CoreSchema generated.
uGet the real schema for a `definition-ref` schema.
If the schema given is not a `definition-ref` schema, it will be returned as is.
This means you don't have to check before calling this function.
Args:
maybe_ref_schema: A `CoreSchema`, `ref`-based or not.
Raises:
LookupError: If the `ref` is not found.
Returns:
A concrete `CoreSchema`.
uGet the name of the closest field to this validator.
uInternal method used during type resolution for serializer annotations.
uType annotations to use with `__get_pydantic_core_schema__` and `__get_pydantic_json_schema__`.
a__doc__
a__file__
origin
has_location
a__cached__
annotations
a_annotations
aTYPE_CHECKING
aAny
aUnion
upydantic_core.core_schema
core_schema
T aGetJsonSchemaHandler
aGetCoreSchemaHandler
a__all__
