# Reconstructed from integrated Nuitka blob
# Module: waanval

uMethod generated by attrs for class
a__doc__

Add __module__ and __qualname__ to a *method* if possible.
uDon't mix `cmp` with `eq' and `order`.
u`order` can only be True if `eq` is True too.

Validate the combination of *cmp*, *eq*, and *order*. Derive the effective
values of eq and order.  If *eq* is None, set it to *default_eq*.

Decide whether a key function is used.
decide_callable_or_boolean
u_determine_attrib_eq_order.<locals>.decide_callable_or_boolean
a_has_own_attribute

Check whether we should implement a set of methods for *cls*.
*flag* is the argument passed into @attr.s like 'init', *auto_detect* the
same as passed into @attr.s and *dunders* is a tuple of attribute names
whose presence signal that the user has implemented it themselves.
Return *default* if no reason for either for or against is found.
warnings
warn
aDeprecationWarning
T uThe `repr_ns` argument is deprecated and will be removed in or after August 2025.
D astacklevel
l a_determine_attrs_eq_order
wrap
uattrs.<locals>.wrap

A class decorator that adds :term:`dunder methods` according to the
specified attributes using `attr.ib` or the *these* argument.
Consider using `attrs.define` / `attrs.frozen` in new code (``attr.s`` will
*never* go away, though).
Args:
repr_ns (str):
When using nested classes, there was no way in Python 2 to
utomatically detect that.  This argument allows to set a custom
name for a more meaningful ``repr`` output.  This argument is
pointless in Python 3 and is therefore deprecated.
.. caution::
Refer to `attrs.define` for the rest of the parameters, but note that they
can have different defaults.
Notably, leaving *on_setattr* as `None` will **not** add any hooks.
.. versionadded:: 16.0.0 *slots*
.. versionadded:: 16.1.0 *frozen*
.. versionadded:: 16.3.0 *str*
.. versionadded:: 16.3.0 Support for ``__attrs_post_init__``.
.. versionchanged:: 17.1.0
*hash* supports `None` as value which is also the default now.
.. versionadded:: 17.3.0 *auto_attribs*
.. versionchanged:: 18.1.0
If *these* is passed, no attributes are deleted from the class body.
.. versionchanged:: 18.1.0 If *these* is ordered, the order is retained.
.. versionadded:: 18.2.0 *weakref_slot*
.. deprecated:: 18.2.0
``__lt__``, ``__le__``, ``__gt__``, and ``__ge__`` now raise a
`DeprecationWarning` if the classes compared are subclasses of
each other. ``__eq`` and ``__ne__`` never tried to compared subclasses
to each other.
.. versionchanged:: 19.2.0
``__lt__``, ``__le__``, ``__gt__``, and ``__ge__`` now do not consider
subclasses comparable anymore.
.. versionadded:: 18.2.0 *kw_only*
.. versionadded:: 18.2.0 *cache_hash*
.. versionadded:: 19.1.0 *auto_exc*
.. deprecated:: 19.2.0 *cmp* Removal on or after 2021-06-01.
.. versionadded:: 19.2.0 *eq* and *order*
.. versionadded:: 20.1.0 *auto_detect*
.. versionadded:: 20.1.0 *collect_by_mro*
.. versionadded:: 20.1.0 *getstate_setstate*
.. versionadded:: 20.1.0 *on_setattr*
.. versionadded:: 20.3.0 *field_transformer*
.. versionchanged:: 21.1.0
``init=False`` injects ``__attrs_init__``
.. versionchanged:: 21.1.0 Support for ``__attrs_pre_init__``
.. versionchanged:: 21.1.0 *cmp* undeprecated
.. versionadded:: 21.3.0 *match_args*
.. versionadded:: 22.2.0
*unsafe_hash* as an alias for *hash* (for :pep:`681` compliance).
.. deprecated:: 24.1.0 *repr_ns*
.. versionchanged:: 24.1.0
Instances are not compared as tuples of attributes anymore, but using a
big ``and`` condition. This is faster and has more correct behavior for
uncomparable values like `math.nan`.
.. versionadded:: 24.1.0
If a class has an *inherited* classmethod called
``__attrs_init_subclass__``, it is executed after the class is created.
.. deprecated:: 24.1.0 *hash* is deprecated in favor of *unsafe_hash*.
frozen
a_has_frozen_base_class
auto_exc
auto_detect
uCan't freeze a class with a custom __setattr__.
a_ClassBuilder
these
slots
weakref_slot
a_determine_whether_to_implement
getstate_setstate
T a__getstate__
a__setstate__
auto_attribs
cache_hash
collect_by_mro
field_transformer
repr
add_repr
repr_ns
str
add_str
eq_
T a__eq__
a__ne__
add_eq
order_
T a__lt__
a__le__
a__gt__
a__ge__
add_order
add_setattr
hash
uInvalid value for cache_hash.  To use hash caching, hashing must be either explicitly or implicitly enabled.
add_hash
make_unhashable
T a__init__
add_init
add_attrs_init
uInvalid value for cache_hash.  To use hash caching, init must be True.
aPY_3_13_PLUS
add_replace
match_args
add_match_args
build_class

Check whether *cls* has a frozen ancestor by looking at its
__setattr__.
u<attrs generated
w u
Create a "filename" suitable for a function being generated.
uhash((
udef __hash__(self):
udef __hash__(self, *, _cache_wrapper=__import__('attr._make')._make._CacheHashWrapper):
u_cache_wrapper(
w)u
Generate the code for actually computing the hash code.
Below this will either be returned directly or used to compute
a value which is then cached, depending on the value of cache_hash
append_hash_computation_lines
u_make_hash.<locals>.append_hash_computation_lines

uif self.
u is None:
uobject.__setattr__(self, '
u',

u                )
uself.
u =
ureturn self.
T ureturn

method_lines
eq
u_make_hash.<locals>.<genexpr>
extend
hash_func
type_hash
w,aeq_key
w_a_key
indent
u(self.
u),
u        self.
closing_braces
D afrozen
cache_hash
Fpu
Add a hash method to *cls*.

Check equality and either forward a NotImplemented or
return the result negated.
u_make_ne.<locals>.__ne__

Create __ne__ method.
udef __eq__(self, other):
u    if other.__class__ is not self.__class__:
u        return NotImplemented
u    return  (
u) ==
u(other.
u == other.
u and
u    )
u    return True

Create __eq__ method for *cls* with *attrs*.
order

Save us some typing.
attrs_to_tuple
u_make_order.<locals>.attrs_to_tuple

Automatically created by attrs.
u_make_order.<locals>.__lt__
u_make_order.<locals>.__le__
u_make_order.<locals>.__gt__
u_make_order.<locals>.__ge__

Create ordering methods for *cls* with *attrs*.
obj
order_key
u_make_order.<locals>.attrs_to_tuple.<locals>.<genexpr>

Add equality methods to *cls* with *attrs*.
a_repr
a_compat
aAttributeError
ugetattr(self, "
u", NOTHING)
u%s={%s!r}
u%s={%s_repr(%s)}
attribute_fragments
u{self.__class__.__qualname__.rsplit(">.", 1)[-1]}
u.{self.__class__.__name__}
udef __repr__(self):
u  try:
u    already_repring = _compat.repr_context.already_repring
u  except AttributeError:
u    already_repring = {id(self),}
u    _compat.repr_context.already_repring = already_repring
u  else:
u    if id(self) in already_repring:
u      return '...'
u    else:
u      already_repring.add(id(self))
u    return f'
w(u)'
u  finally:
u    already_repring.remove(id(self))
T aglobs
u_make_repr.<locals>.<genexpr>

Add a repr method to *cls*.
get_generic_base
uPassed object must be a class.
u is not an attrs-decorated class.
aNotAnAttrsClassError

Return the tuple of *attrs* attributes for a class.
The tuple also allows accessing the fields by their names (see below for
examples).
Args:
cls (type): Class to introspect.
Raises:
TypeError: If *cls* is not a class.
ttrs.exceptions.NotAnAttrsClassError:
If *cls* is not an *attrs* class.
Returns:
tuple (with name accessors) of `attrs.Attribute`
.. versionchanged:: 16.2.0 Returned tuple allows accessing the fields
by name.
.. versionchanged:: 23.1.0 Add support for generic classes.

Return an ordered dictionary of *attrs* attributes for a class, whose keys
re the attribute names.
Args:
cls (type): Class to introspect.
Raises:
TypeError: If *cls* is not a class.
ttrs.exceptions.NotAnAttrsClassError:
If *cls* is not an *attrs* class.
Returns:
dict[str, attrs.Attribute]: Dict of attribute name to definition
.. versionadded:: 18.1.0
a_config
a_run_validators
inst

Validate all attributes on *inst* that have a validator.
Leaves all exceptions through.
Args:
inst: Instance of a class with *attrs* attributes.

Check if the attribute name comes from a slot class.
uFrozen classes can't use on_setattr.
filtered_attrs
attr_dict
a_attrs_to_init_script
needs_cached_setattr
modules
a__annotations__
u_setattr('

Use the cached object.setattr to set *attr_name* to *value_var*.
a_fmt_converter_call

Use the cached object.setattr to set *attr_name* to *value_var*, but run
its converter first.
a_setattr

Unless *attr_name* has an on_setattr hook, use normal assignment. Otherwise
relegate to _setattr.
a_setattr_with_converter

Unless *attr_name* has an on_setattr hook, use normal assignment after
conversion. Otherwise relegate to _setattr_with_converter.
D aattr_name
value_var
has_on_setattr
return
str
pabool
str
fmt_setter
u_determine_setters.<locals>.fmt_setter
D aattr_name
value_var
has_on_setattr
converter
return
str
pabool
aConverter
str
fmt_setter_with_converter
u_determine_setters.<locals>.fmt_setter_with_converter
T u_inst_dict = self.__dict__
a_assign
a_assign_with_converter

Determine the correct setter functions based on whether a class is frozen
nd/or slotted.
a_is_slot_attr
u_inst_dict['
u'] =
uself.__attrs_pre_init__()
u_setattr = _cached_setattr_get(self)
a_determine_setters
D areturn
naattrs_to_validate
takes_self
aConverter
a_INIT_FACTORY_PAT
names_for_globals
a_get_global_name
factory
init_factory_name
uattr_dict['
u'].default
u=attr_dict['
kw_only_args
args
u=NOTHING
uif
u is not NOTHING:
T uelse:
arg_name
type
annotations
a_first_param_type
uif _config._run_validators is True:
a__attr_validator_
a__attr_
u(self,
u, self.
uself.__attrs_post_init__()
u', None)
u'] = None
u = None
uBaseException.__init__(self,
u*,
w=uself.__attrs_pre_init__(
udef
u):

pass

Return a script of an initializer for *attrs*, a dict of globals, and
nnotations for the initializer.
The globals are required by the generated script.
u_attrs_to_init_script.<locals>.<genexpr>
split
T w=alstrip
T w_u
The default __init__ parameter name for a field.
This performs private-name adjustment via leading-unscore stripping,
nd is the default value of Attribute.alias if not provided.
metadata
aMappingProxyType
a_EMPTY_METADATA_SINGLETON
uType annotation and type argument cannot both be present
T aname
validator
default
type
inherited
ca
a_validator
a_default
cmp
copy
a_setattrs

Copy *self* and apply *changes*.
This works similarly to `attrs.evolve` but that function does not work
with :class:`attrs.Attribute`.
It is mainly meant to be used for `transform-fields`.
.. versionadded:: 20.3.0

Play nice with pickle.
uAttribute.__getstate__.<locals>.<genexpr>
bound_setattr
T aname
alias
default
validator
repr
cmp
hash
init
kw_only
eq
eq_key
order
order_key
inherited
on_setattr
u_CountingAttr.<genexpr>
cls_counter
meth

Decorator that adds *meth* to the list of validators.
Returns *meth* unchanged.
.. versionadded:: 17.1.0
aDefaultAlreadySetError
D atakes_self
tu
Decorator that allows to set the default for an attribute.
Returns *meth* unchanged.
Raises:
DefaultAlreadySetError: If default has been set before.
.. versionadded:: 17.1.0
uFactory.__getstate__.<locals>.<genexpr>
takes_field
a_AnnotationExtractor
get_first_param_type
uConverter.__init__.<locals>.<lambda>
a__call__
get_return_type
return
a__attr_converter_

Return the name that a converter for an attribute name *attr_name*
would have.
u, self, attr_dict['
u'])
u, self)
u, attr_dict['

Return a string that calls the converter for an attribute name
*attr_name* and the value in variable named *value_var* according to
`self.takes_self` and `self.takes_field`.

Return a dict containing only converter and takes_self -- the rest gets
computed when loading.

Load instance from state.
uattrs argument must be a dict or a list.
pop
T a__attrs_pre_init__
nT a__attrs_post_init__
nT a__init__
nanew_class
umake_class.<locals>.<lambda>
T EAttributeError
EValueError
a_getframe
T l af_globals
T a__name__
a__main__
T aeq
T aorder

A quick way to create a new class called *name* with *attrs*.
.. note::
``make_class()`` is a thin wrapper around `attr.s`, not `attrs.define`
which means that it doesn't come with some of the improved defaults.
For example, if you want the same ``on_setattr`` behavior as in
`attrs.define`, you have to pass the hooks yourself: ``make_class(...,
on_setattr=setters.pipe(setters.convert, setters.validate)``
Args:
name (str): The name for the new class.
ttrs (list | dict):
A list of names or a dictionary of mappings of names to `attr.ib`\
s / `attrs.field`\ s.
The order is deduced from the order of the names or attributes
inside *attrs*.  Otherwise the order of the definition of the
ttributes is used.
bases (tuple[type, ...]): Classes that the new class will subclass.
class_body (dict):
An optional dictionary of class attributes for the new class.
ttributes_arguments: Passed unmodified to `attr.s`.
Returns:
type: A new class with *attrs*.
.. versionadded:: 17.1.0 *bases*
.. versionchanged:: 18.1.0 If *attrs* is ordered, the order is retained.
.. versionchanged:: 23.2.0 *class_body*
body
a_validators
attr
value
vals
a_AndValidator

A validator that composes multiple validators into one.
When called on a value, it runs all wrapped validators.
Args:
validators (~collections.abc.Iterable[typing.Callable]):
Arbitrary number of validators.
.. versionadded:: 17.1.0
pipe_converter
upipe.<locals>.pipe_converter
aTypeVar
T wAaval
aPY_3_11_PLUS
D atakes_self
takes_field
tpu
A converter that composes multiple converters into one.
When called on a value, it runs all wrapped converters, returning the
*last* value.
Type annotations will be inferred from the wrapped converters', if they
have any.
converters (~collections.abc.Iterable[typing.Callable]):
Arbitrary number of converters.
.. versionadded:: 20.1.0
upipe.<locals>.<genexpr>
converters
field
a__file__
origin
has_location
a__cached__
enum
functools
sys
types
typing
operator
T aitemgetter
T a_compat
a_config
setters
T aPY_3_10_PLUS
aPY_3_11_PLUS
aPY_3_13_PLUS
a_AnnotationExtractor
a_get_annotations
get_generic_base
exceptions
T aDefaultAlreadySetError
aFrozenInstanceError
aNotAnAttrsClassError
aUnannotatedAttributeError
u__attr_factory_%s
T utyping.ClassVar
ut.ClassVar
aClassVar
utyping_extensions.ClassVar
a_attrs_cached_hash
aEnum
a__prepare__
a_Nothing
a__getitem__
u%s.__prepare__() must return a mapping, not %s
u<metaclass>
uattr._make

Sentinel to indicate the lack of a value when `None` is ambiguous.
If extending attrs, you can use ``typing.Literal[NOTHING]`` to show
that a value may be ``NOTHING``.
.. versionchanged:: 21.1.0 ``bool(NOTHING)`` is now False.
.. versionchanged:: 22.2.0 ``NOTHING`` is now an ``enum.Enum`` variant.
auto
u_Nothing.__repr__
a__bool__
u_Nothing.__bool__
a__orig_bases__
T Oint
a_CacheHashWrapper

An integer subclass that pickles / copies as None
This is used for non-slots classes with ``cache_hash=True``, to avoid
serializing a potentially (even likely) invalid hash value. Since `None`
is the default value for uncalculated hashes, whenever this is copied,
the copy's value for the hash should automatically reset.
See GH #613 for more details.
T na__reduce__
u_CacheHashWrapper.__reduce__
T nu
base_attrs_map

Iteratively build *one* class.
T a_attr_names
a_attrs
a_base_attr_map
a_base_names
a_cache_hash
a_cls
a_cls_dict
a_delete_attribs
a_frozen
a_has_custom_setattr
a_has_post_init
a_has_pre_init
a_is_exc
a_on_setattr
a_pre_init_has_args
a_slots
a_weakref_slot
a_wrote_own_setattr
u_ClassBuilder.__init__
u_ClassBuilder.__repr__
u_ClassBuilder.build_class
u_ClassBuilder._patch_original_class
u_ClassBuilder._create_slots_class
u_ClassBuilder.add_repr
u_ClassBuilder.add_str
u_ClassBuilder._make_getstate_setstate
u_ClassBuilder.make_unhashable
u_ClassBuilder.add_hash
u_ClassBuilder.add_init
u_ClassBuilder.add_replace
u_ClassBuilder.add_match_args
u_ClassBuilder.add_attrs_init
u_ClassBuilder.add_eq
u_ClassBuilder.add_order
u_ClassBuilder.add_setattr
u_ClassBuilder._add_method_dunders
T nnnnnnnFptFppppnnFpnnntna_add_hash
a_add_eq
T nna_add_repr
fields_dict
D aattr_name
value
has_on_setattr
return
str
pabool
str
D afrozen
slots
base_attr_map
bool
pudict[str, type]
Daattrs
is_frozen
is_slotted
call_pre_init
pre_init_has_args
call_post_init
does_cache_hash
base_attr_map
is_exc
needs_cached_setattr
has_cls_on_setattr
method_name
return
ulist[Attribute]
bool
pppppudict[str, type]
bool
ppastr
utuple[str, dict, dict]
D aname
return
str
pu
*Read-only* representation of an attribute.
.. warning::
You should never instantiate this class yourself.
The class has *all* arguments of `attr.ib` (except for ``factory`` which is
only syntactic sugar for ``default=Factory(...)`` plus the following:
- ``name`` (`str`): The name of the attribute.
- ``alias`` (`str`): The __init__ parameter name of the attribute, after
ny explicit overrides and default private-attribute-name handling.
- ``inherited`` (`bool`): Whether or not that attribute has been inherited
from a base class.
- ``eq_key`` and ``order_key`` (`typing.Callable` or `None`): The
callables that are used for comparing and ordering objects by this
ttribute, respectively. These are set by passing a callable to
`attr.ib`'s ``eq``, ``order``, or ``cmp`` arguments. See also
:ref:`comparison customization <custom-comparison>`.
Instances of this class are frequently used for introspection purposes
like:
- `fields` returns a tuple of them.
- Validators get them passed as the first argument.
- The :ref:`field transformer <transform-fields>` hook receives a list of
them.
- The ``alias`` property exposes the __init__ parameter name of the field,
with any overrides and default private-attribute handling applied.
.. versionadded:: 20.1.0 *inherited*
.. versionadded:: 20.1.0 *on_setattr*
.. versionchanged:: 20.2.0 *inherited* is not taken into account for
equality checks and hashing anymore.
.. versionadded:: 21.1.0 *eq_key* and *order_key*
.. versionadded:: 22.2.0 *alias*
For the full version history of the fields, see `attr.ib`.
T aname
default
validator
repr
eq
eq_key
order
order_key
hash
init
metadata
type
converter
kw_only
inherited
on_setattr
alias
T
nnnFnnnnnnuAttribute.__init__
uAttribute.__setattr__
uAttribute.from_counting_attr
uAttribute.evolve
uAttribute.__getstate__
uAttribute.__setstate__
uAttribute._setattrs
T aname
default
validator
repr
cmp
eq
order
hash
init
inherited
alias
a_a
T aattrs

Intermediate representation of attributes that uses a counter to preserve
the order in which the attributes have been defined.
*Internal* data structure of the attrs library.  Running into is most
likely the result of a bug like a forgotten `@attr.s` decorator.
T a_default
a_validator
alias
converter
counter
eq
eq_key
hash
init
kw_only
metadata
on_setattr
order
order_key
repr
type
T	acounter
a_default
repr
eq
order
hash
init
on_setattr
alias
T ametadata
metadata
nntnFtFtnFnFnu_CountingAttr.__init__
u_CountingAttr.validator
u_CountingAttr.default

Stores a factory callable.
If passed as the default value to `attrs.field`, the factory is used to
generate a new value.
Args:
factory (typing.Callable):
A callable that takes either none or exactly one mandatory
positional argument depending on *takes_self*.
takes_self (bool):
Pass the partially initialized instance that is being initialized
s a positional argument.
.. versionadded:: 17.1.0  *takes_self*
T afactory
takes_self
T FuFactory.__init__
uFactory.__getstate__
uFactory.__setstate__
T
name
default
validator
repr
cmp
eq
order
hash
init
inherited
a_f

Stores a converter callable.
Allows for the wrapped converter to take additional arguments. The
rguments are passed in the order they are documented.
Args:
converter (Callable): A callable that converts the passed value.
takes_self (bool):
Pass the partially initialized instance that is being initialized
s a positional argument. (default: `False`)
takes_field (bool):
Pass the field definition (an :class:`Attribute`) into the
converter as a positional argument. (default: `False`)
.. versionadded:: 24.1.0
T a__call__
a_first_param_type
a_global_name
converter
takes_field
takes_self
D atakes_self
takes_field
FpuConverter.__init__
D aattr_name
return
str
puConverter._get_global_name
D aattr_name
value_var
return
str
ppuConverter._fmt_converter_call
uConverter.__getstate__
uConverter.__setstate__
T aconverter
takes_self
takes_field
T T Oobject
namake_class
T tpT aslots
unsafe_hash

Compose many validators to a single one.
u_AndValidator.__call__
uattr\_make.py
T a.0
name
self
T a.0
waT a.0
an
T a.0
field
T a.0
meth
self
T a.0
name
T a.0
kwa
T a.0
waaobj
T a.0
value
key
T a.0
name
attr
T a.0
wcT avalue
w_a__
self
T aself
T avalue
a__
field
self
T avalue
instance
a__
self
T avalue
instance
field
self
T aself
changes
T weT wnacd
T acd
T ans
body
T abody
u<module attr._make>
T a__class__
T aself
inst
attr
value
wvT aself
other
attrs_to_tuple
T aattrs_to_tuple
T aself
name
default
validator
repr
cmp
hash
init
inherited
metadata
type
converter
kw_only
eq
eq_key
order
order_key
on_setattr
alias
bound_setattr
T aself
converter
takes_self
takes_field
ex
rt
T aself
factory
takes_self
T aself
cls
these
slots
frozen
weakref_slot
getstate_setstate
auto_attribs
kw_only
cache_hash
is_exc
collect_by_mro
on_setattr
has_custom_setattr
field_transformer
attrs
base_attrs
base_map
pre_init_func
pre_init_signature
has_validator
has_converter
waT aself
default
validator
repr
cmp
hash
init
converter
metadata
type
kw_only
eq
eq_key
order
order_key
on_setattr
alias
T aself
other
result
T aself
a_none_constructor
a_args
T aself
name
value
T aself
name
val
waahook
nval
sa_attrs
T asa_attrs
T aself
state
T aself
state
name
value
T acls
attrs
T aself
method
T acls
ns
attrs
T aattr_name
value
has_on_setattr
T aattr_name
value_var
has_on_setattr
converter
T$aattrs
is_frozen
is_slotted
call_pre_init
pre_init_has_args
call_post_init
does_cache_hash
base_attr_map
is_exc
needs_cached_setattr
has_cls_on_setattr
method_name
lines
extra_lines
fmt_setter
fmt_setter_with_converter
args
kw_only_args
attrs_to_validate
names_for_globals
annotations
waaattr_name
has_on_setattr
arg_name
has_factory
maybe_self
converter
init_factory_name
arg
val_name
init_hash_cache
vals
pre_init_args
pre_init_kw_only_args
aNL
T acls
taken_attr_names
base_attrs
base_attr_map
base_cls
waafiltered
seen
T acls
taken_attr_names
base_attrs
base_attr_map
base_cls
waT ascript
globs
locs
filename
bytecode
T aself
cd
base_cls
existing_slots
weakref_inherited
base_names
names
cached_properties
additional_closure_functions_to_update
class_annotations
name
func
annotation
original_getattr
slot_names
reused_slots
cls
item
closure_cells
cell
match
T aname
T	acmp
eq
order
default_eq
msg
decide_callable_or_boolean
cmp_key
eq_key
order_key
T acmp
eq
order
default_eq
msg
T afrozen
slots
base_attr_map
fmt_setter
fmt_setter_with_converter
T acls
flag
auto_detect
dunders
default
dunder
T aself
attr_name
value_var
T aself
name
T acls
func_name
T aattr_name
T acls
T acls
attrib_name
T aannot
T aa_name
base_attr_map
cls
T acls_name
attr_names
attr_class_name
attr_class_template
wiaattr_name
globs
T acached_properties
original_getattr
cls
lines
unique_filename
glob
T acls
attrs
unique_filename
lines
globs
waacmp_name
script
T aself
state_attr_names
slots_getstate
hash_caching_enabled
slots_setstate
T acls
attrs
frozen
cache_hash
tab
unique_filename
type_hash
globs
hash_def
hash_func
closing_braces
method_lines
append_hash_computation_lines
script
T acls
attrs
pre_init
pre_init_has_args
post_init
frozen
slots
cache_hash
base_attr_map
is_exc
cls_on_setattr
attrs_init
has_cls_on_setattr
msg
needs_cached_setattr
filtered_attrs
attr_dict
waaunique_filename
script
globs
annotations
init
T
name
script
filename
globs
locals
locs
count
base_filename
linecache_tuple
old_val
T a__ne__
T acls
attrs
attrs_to_tuple
a__lt__
a__le__
a__gt__
a__ge__
T aattrs
ns
cls
unique_filename
attr_names_with_reprs
globs
attribute_fragments
name
wrwiaaccessor
fragment
repr_fragment
cls_name_fragment
lines
T aself
cls
base_names
name
value
T aattr_name
value_var
has_on_setattr
T aself
name_values_pairs
bound_setattr
name
value
T acls
these
auto_attribs
kw_only
collect_by_mro
field_transformer
cd
anns
ca_list
ca_names
annot_names
attr_name
type
waaunannotated
own_attrs
base_attrs
base_attr_map
attrs
had_default
msg
attr_names
aAttrsClass
T aself
cd
T aself
ns
T aself
sa_attrs
waaon_setattr
msg
a__setattr__
T aself
repr
msg
a__str__
T avalidators
vals
validator
T
prefix
indent
waacmp_name
method_lines
hash_func
type_hash
attrs
globs
closing_braces
T aattrs
closing_braces
globs
hash_func
method_lines
type_hash
T adefault
validator
repr
cmp
hash
init
metadata
type
converter
factory
kw_only
eq
order
on_setattr
alias
eq_key
order_key
msg
T amaybe_cls
these
repr_ns
repr
cmp
hash
init
slots
frozen
weakref_slot
str
auto_attribs
kw_only
cache_hash
auto_exc
eq
order
auto_detect
collect_by_mro
getstate_setstate
on_setattr
field_transformer
match_args
unsafe_hash
warnings
eq_
order_
wrap
T aobj
attrs
T aself
cls
T avalue
key
T aself
meth
T aself
changes
new
T	aargs
changes
inst
msg
cls
attrs
waaattr_name
init_name
T acls
generic_base
msg
attrs
T acls
msg
attrs
T aattr_name
value_var
has_on_setattr
base_attr_map
T abase_attr_map
T aattr_name
value_var
has_on_setattr
converter
base_attr_map
T acls
name
ca
type
msg
inst_dict
T aname
attrs
bases
class_body
attributes_arguments
cls_dict
msg
pre_init
post_init
user_init
body
type_
cmp
cls
T aconverters
return_instance
pipe_converter
wAwtalast
rt
T aval
wcaconverters
T aconverters
T aval
inst
field
wcaconverters
T aself
state_attr_names
T astate_attr_names
T aself
state
a_ClassBuilder__bound_setattr
name
value
state_attr_names
hash_caching_enabled
T ahash_caching_enabled
state_attr_names
T ainst
wawvT acls
hash
is_frozen
is_exc
has_own_setattr
msg
builder
eq
frozen
auto_exc
auto_detect
these
slots
weakref_slot
getstate_setstate
auto_attribs
kw_only
cache_hash
collect_by_mro
on_setattr
field_transformer
repr
repr_ns
str
eq_
order_
init
match_args
T aauto_attribs
auto_detect
auto_exc
cache_hash
collect_by_mro
eq_
field_transformer
frozen
getstate_setstate
hash
init
kw_only
match_args
on_setattr
order_
repr
repr_ns
slots
str
these
weakref_slot
a__spec__
.attr._next_gen
Y
Y
do_it
udefine.<locals>.do_it

Making this a wrapper ensures this code runs during class creation.
We also ensure that frozen-ness of classes is inherited.
wrap
udefine.<locals>.wrap

A class decorator that adds :term:`dunder methods` according to
:term:`fields <field>` specified using :doc:`type annotations <types>`,
`field()` calls, or the *these* argument.
Since *attrs* patches or replaces an existing class, you cannot use
`object.__init_subclass__` with *attrs* classes, because it runs too early.
As a replacement, you can define ``__attrs_init_subclass__`` on your class.
It will be called by *attrs* classes that subclass it after they're
created. See also :ref:`init-subclass`.
Args:
slots (bool):
Create a :term:`slotted class <slotted classes>` that's more
memory-efficient. Slotted classes are generally superior to the
default dict classes, but have some gotchas you should know about,
so we encourage you to read the :term:`glossary entry <slotted
classes>`.
uto_detect (bool):
Instead of setting the *init*, *repr*, *eq*, and *hash* arguments
explicitly, assume they are set to True **unless any** of the
involved methods for one of the arguments is implemented in the
*current* class (meaning, it is *not* inherited from some base
class).
So, for example by implementing ``__eq__`` on a class yourself,
*attrs* will deduce ``eq=False`` and will create *neither*
``__eq__`` *nor* ``__ne__`` (but Python classes come with a
sensible ``__ne__`` by default, so it *should* be enough to only
implement ``__eq__`` in most cases).
Passing True or False` to *init*, *repr*, *eq*, or *hash*
overrides whatever *auto_detect* would determine.
uto_exc (bool):
If the class subclasses `BaseException` (which implicitly includes
ny subclass of any exception), the following happens to behave
like a well-behaved Python exception class:
- the values for *eq*, *order*, and *hash* are ignored and the
instances compare and hash by the instance's ids [#]_ ,
- all attributes that are either passed into ``__init__`` or have a
default value are additionally available as a tuple in the
``args`` attribute,
- the value of *str* is ignored leaving ``__str__`` to base
classes.
.. [#]
Note that *attrs* will *not* remove existing implementations of
``__hash__`` or the equality methods. It just won't add own
ones.
on_setattr (~typing.Callable | list[~typing.Callable] | None | ~typing.Literal[attrs.setters.NO_OP]):
A callable that is run whenever the user attempts to set an
ttribute (either by assignment like ``i.x = 42`` or by using
`setattr` like ``setattr(i, "x", 42)``). It receives the same
rguments as validators: the instance, the attribute that is being
modified, and the new value.
If no exception is raised, the attribute is set to the return value
of the callable.
If a list of callables is passed, they're automatically wrapped in
n `attrs.setters.pipe`.
If left None, the default behavior is to run converters and
validators whenever an attribute is set.
init (bool):
Create a ``__init__`` method that initializes the *attrs*
ttributes. Leading underscores are stripped for the argument name,
unless an alias is set on the attribute.
.. seealso::
`init` shows advanced ways to customize the generated
``__init__`` method, including executing code before and after.
repr(bool):
Create a ``__repr__`` method with a human readable representation
of *attrs* attributes.
str (bool):
Create a ``__str__`` method that is identical to ``__repr__``. This
is usually not necessary except for `Exception`\ s.
eq (bool | None):
If True or None (default), add ``__eq__`` and ``__ne__`` methods
that check two instances for equality.
.. seealso::
`comparison` describes how to customize the comparison behavior
going as far comparing NumPy arrays.
order (bool | None):
If True, add ``__lt__``, ``__le__``, ``__gt__``, and ``__ge__``
methods that behave like *eq* above and allow instances to be
ordered.
They compare the instances as if they were tuples of their *attrs*
ttributes if and only if the types of both classes are
*identical*.
If `None` mirror value of *eq*.
.. seealso:: `comparison`
unsafe_hash (bool | None):
If None (default), the ``__hash__`` method is generated according
how *eq* and *frozen* are set.
1. If *both* are True, *attrs* will generate a ``__hash__`` for
you.
2. If *eq* is True and *frozen* is False, ``__hash__`` will be set
to None, marking it unhashable (which it is).
3. If *eq* is False, ``__hash__`` will be left untouched meaning
the ``__hash__`` method of the base class will be used. If the
base class is `object`, this means it will fall back to id-based
hashing.
Although not recommended, you can decide for yourself and force
*attrs* to create one (for example, if the class is immutable even
though you didn't freeze it programmatically) by passing True or
not.  Both of these cases are rather special and should be used
carefully.
.. seealso::
- Our documentation on `hashing`,
- Python's documentation on `object.__hash__`,
- and the `GitHub issue that led to the default \ behavior
<https://github.com/python-attrs/attrs/issues/136>`_ for more
details.
hash (bool | None):
Deprecated alias for *unsafe_hash*. *unsafe_hash* takes precedence.
cache_hash (bool):
Ensure that the object's hash code is computed only once and stored
on the object.  If this is set to True, hashing must be either
explicitly or implicitly enabled for this class.  If the hash code
is cached, avoid any reassignments of fields involved in hash code
computation or mutations of the objects those fields point to after
object creation.  If such changes occur, the behavior of the
object's hash code is undefined.
frozen (bool):
Make instances immutable after initialization.  If someone attempts
to modify a frozen instance, `attrs.exceptions.FrozenInstanceError`
is raised.
.. note::
1. This is achieved by installing a custom ``__setattr__``
method on your class, so you can't implement your own.
2. True immutability is impossible in Python.
3. This *does* have a minor a runtime performance `impact
<how-frozen>` when initializing new instances.  In other
words: ``__init__`` is slightly slower with ``frozen=True``.
4. If a class is frozen, you cannot modify ``self`` in
``__attrs_post_init__`` or a self-written ``__init__``. You
can circumvent that limitation by using
``object.__setattr__(self, "attribute_name", value)``.
5. Subclasses of a frozen class are frozen too.
kw_only (bool):
Make all attributes keyword-only in the generated ``__init__`` (if
*init* is False, this parameter is ignored).
weakref_slot (bool):
Make instances weak-referenceable.  This has no effect unless
*slots* is True.
field_transformer (~typing.Callable | None):
A function that is called with the original class object and all
fields right before *attrs* finalizes the class.  You can use this,
for example, to automatically add converters or validators to
fields based on their types.
.. seealso:: `transform-fields`
match_args (bool):
If True (default), set ``__match_args__`` on the class to support
:pep:`634` (*Structural Pattern Matching*). It is a tuple of all
non-keyword-only ``__init__`` parameter names on Python 3.10 and
later. Ignored on older Python versions.
collect_by_mro (bool):
If True, *attrs* collects attributes from base classes correctly
ccording to the `method resolution order
<https://docs.python.org/3/howto/mro.html>`_. If False, *attrs*
will mimic the (wrong) behavior of `dataclasses` and :pep:`681`.
See also `issue #428
<https://github.com/python-attrs/attrs/issues/428>`_.
getstate_setstate (bool | None):
.. note::
This is usually only interesting for slotted classes and you
should probably just set *auto_detect* to True.
If True, ``__getstate__`` and ``__setstate__`` are generated and
ttached to the class. This is necessary for slotted classes to be
pickleable. If left None, it's True by default for slotted classes
nd False for dict classes.
If *auto_detect* is True, and *getstate_setstate* is left None, and
**either** ``__getstate__`` or ``__setstate__`` is detected
directly on the class (meaning: not inherited), it is set to False
(this is usually what you want).
uto_attribs (bool | None):
If True, look at type annotations to determine which attributes to
use, like `dataclasses`. If False, it will only look for explicit
:func:`field` class attributes, like classic *attrs*.
If left None, it will guess:
1. If any attributes are annotated and no unannotated
`attrs.field`\ s are found, it assumes *auto_attribs=True*.
2. Otherwise it assumes *auto_attribs=False* and tries to collect
`attrs.field`\ s.
If *attrs* decides to look at type annotations, **all** fields
**must** be annotated. If *attrs* encounters a field that is set to
a :func:`field` / `attr.ib` but lacks a type annotation, an
`attrs.exceptions.UnannotatedAttributeError` is raised.  Use
``field_name: typing.Any = field(...)`` if you don't want to set a
type.
.. warning::
For features that use the attribute name to create decorators
(for example, :ref:`validators <validators>`), you still *must*
ssign :func:`field` / `attr.ib` to them. Otherwise Python will
either not find the name or try to use the default value to
call, for example, ``validator`` on it.
Attributes annotated as `typing.ClassVar`, and attributes that are
neither annotated nor set to an `field()` are **ignored**.
these (dict[str, object]):
A dictionary of name to the (private) return value of `field()`
mappings. This is useful to avoid the definition of your attributes
within the class body because you can't (for example, if you want
to add ``__repr__`` methods to Django models) or don't want to.
If *these* is not `None`, *attrs* will *not* search the class body
for attributes and will *not* remove any attributes from it.
The order is deduced from the order of the attributes inside
*these*.
Arguably, this is a rather obscure feature.
.. versionadded:: 20.1.0
.. versionchanged:: 21.3.0 Converters are also run ``on_setattr``.
.. versionadded:: 22.2.0
*unsafe_hash* as an alias for *hash* (for :pep:`681` compliance).
.. versionchanged:: 24.1.0
Instances are not compared as tuples of attributes anymore, but using a
big ``and`` condition. This is faster and has more correct behavior for
uncomparable values like `math.nan`.
.. versionadded:: 24.1.0
If a class has an *inherited* classmethod called
``__attrs_init_subclass__``, it is executed after the class is created.
.. deprecated:: 24.1.0 *hash* is deprecated in favor of *unsafe_hash*.
.. versionadded:: 24.3.0
Unless already present, a ``__replace__`` method is automatically
created for `copy.replace` (Python 3.13+ only).
.. note::
The main differences to the classic `attr.s` are:
- Automatically detect whether or not *auto_attribs* should be `True`
(c.f. *auto_attribs* parameter).
- Converters and validators run when attributes are set by default --
if *frozen* is `False`.
- *slots=True*
Usually, this has only upsides and few visible effects in everyday
programming. But it *can* lead to some surprising behaviors, so
please make sure to read :term:`slotted classes`.
- *auto_exc=True*
- *auto_detect=True*
- *order=False*
- Some options that were only relevant on Python 2 or were kept around
for backwards-compatibility have been removed.
attrs
these
repr
hash
unsafe_hash
init
slots
frozen
weakref_slot
str
kw_only
cache_hash
auto_exc
eq
order
auto_detect
getstate_setstate
on_setattr
field_transformer
match_args
T amaybe_cls
these
repr
hash
unsafe_hash
init
slots
frozen
weakref_slot
str
auto_attribs
kw_only
cache_hash
auto_exc
eq
order
auto_detect
collect_by_mro
getstate_setstate
on_setattr
field_transformer
match_args
setters
aNO_OP
a_DEFAULT_ON_SETATTR
a__bases__
a__setattr__
a_frozen_setattrs
uFrozen classes can't use on_setattr (frozen-ness was inherited).
auto_attribs
aUnannotatedAttributeError
attrib
T adefault
validator
repr
hash
init
metadata
type
converter
factory
kw_only
eq
order
on_setattr
alias

Create a new :term:`field` / :term:`attribute` on a class.
..  warning::
Does **nothing** unless the class is also decorated with
`attrs.define` (or similar)!
Args:
default:
A value that is used if an *attrs*-generated ``__init__`` is used
nd no value is passed while instantiating or the attribute is
excluded using ``init=False``.
If the value is an instance of `attrs.Factory`, its callable will
be used to construct a new value (useful for mutable data types
like lists or dicts).
If a default is not set (or set manually to `attrs.NOTHING`), a
value *must* be supplied when instantiating; otherwise a
`TypeError` will be raised.
.. seealso:: `defaults`
factory (~typing.Callable):
Syntactic sugar for ``default=attr.Factory(factory)``.
validator (~typing.Callable | list[~typing.Callable]):
Callable that is called by *attrs*-generated ``__init__`` methods
fter the instance has been initialized.  They receive the
initialized instance, the :func:`~attrs.Attribute`, and the passed
value.
The return value is *not* inspected so the validator has to throw
n exception itself.
If a `list` is passed, its items are treated as validators and must
ll pass.
Validators can be globally disabled and re-enabled using
`attrs.validators.get_disabled` / `attrs.validators.set_disabled`.
The validator can also be set using decorator notation as shown
below.
.. seealso:: :ref:`validators`
repr (bool | ~typing.Callable):
Include this attribute in the generated ``__repr__`` method. If
True, include the attribute; if False, omit it. By default, the
built-in ``repr()`` function is used. To override how the attribute
value is formatted, pass a ``callable`` that takes a single value
nd returns a string. Note that the resulting string is used as-is,
which means it will be used directly *instead* of calling
``repr()`` (the default).
eq (bool | ~typing.Callable):
If True (default), include this attribute in the generated
``__eq__`` and ``__ne__`` methods that check two instances for
equality. To override how the attribute value is compared, pass a
callable that takes a single value and returns the value to be
compared.
.. seealso:: `comparison`
order (bool | ~typing.Callable):
If True (default), include this attributes in the generated
``__lt__``, ``__le__``, ``__gt__`` and ``__ge__`` methods. To
override how the attribute value is ordered, pass a callable that
takes a single value and returns the value to be ordered.
.. seealso:: `comparison`
hash (bool | None):
Include this attribute in the generated ``__hash__`` method.  If
None (default), mirror *eq*'s value.  This is the correct behavior
ccording the Python spec.  Setting this value to anything else
than None is *discouraged*.
.. seealso:: `hashing`
init (bool):
Include this attribute in the generated ``__init__`` method.
It is possible to set this to False and set a default value. In
that case this attributed is unconditionally initialized with the
specified default value or factory.
.. seealso:: `init`
converter (typing.Callable | Converter):
A callable that is called by *attrs*-generated ``__init__`` methods
to convert attribute's value to the desired format.
If a vanilla callable is passed, it is given the passed-in value as
the only positional argument. It is possible to receive additional
rguments by wrapping the callable in a `Converter`.
Either way, the returned value will be used as the new value of the
ttribute.  The value is converted before being passed to the
validator, if any.
.. seealso:: :ref:`converters`
metadata (dict | None):
An arbitrary mapping, to be used by third-party code.
.. seealso:: `extending-metadata`.
type (type):
The type of the attribute. Nowadays, the preferred method to
specify the type is using a variable annotation (see :pep:`526`).
This argument is provided for backwards-compatibility and for usage
with `make_class`. Regardless of the approach used, the type will
be stored on ``Attribute.type``.
Please note that *attrs* doesn't do anything with this metadata by
itself. You can use it as part of your own code or for `static type
checking <types>`.
kw_only (bool):
Make this attribute keyword-only in the generated ``__init__`` (if
``init`` is False, this parameter is ignored).
on_setattr (~typing.Callable | list[~typing.Callable] | None | ~typing.Literal[attrs.setters.NO_OP]):
Allows to overwrite the *on_setattr* setting from `attr.s`. If left
None, the *on_setattr* value from `attr.s` is used. Set to
`attrs.setters.NO_OP` to run **no** `setattr` hooks for this
ttribute -- regardless of the setting in `define()`.
lias (str | None):
Override this attribute's parameter name in the generated
``__init__`` method. If left None, default to ``name`` stripped
of leading underscores. See `private-attributes`.
.. versionadded:: 20.1.0
.. versionchanged:: 21.1.0
*eq*, *order*, and *cmp* also accept a custom callable
.. versionadded:: 22.2.0 *alias*
.. versionadded:: 23.1.0
The *type* parameter has been re-added; mostly for `attrs.make_class`.
Please note that type checkers ignore this metadata.
.. seealso::
`attr.ib`
a_asdict
T ainst
recurse
filter
value_serializer
retain_collection_types

Same as `attr.asdict`, except that collections types are always retained
nd dict is always used as *dict_factory*.
.. versionadded:: 21.3.0
a_astuple
T ainst
recurse
filter
retain_collection_types

Same as `attr.astuple`, except that collections types are always retained
nd `tuple` is always used as the *tuple_factory*.
.. versionadded:: 21.3.0

These are keyword-only APIs that call `attr.s` and `attr.ib` with different
default values.
a__doc__
a__file__
origin
has_location
a__cached__
partial

T asetters
a_funcs
T aasdict
asdict
T aastuple
astuple
a_make
T a_DEFAULT_ON_SETATTR
aNOTHING
a_frozen_setattrs
attrib
attrs
aNOTHING
exceptions
T aUnannotatedAttributeError
T nD athese
repr
unsafe_hash
hash
init
slots
frozen
weakref_slot
str
auto_attribs
kw_only
cache_hash
auto_exc
eq
order
auto_detect
getstate_setstate
on_setattr
field_transformer
match_args
nnnnntFtFnFptnFtnnntadefine
mutable
D afrozen
on_setattr
tnadefault
validator
metadata
type
converter
factory
alias
field
D arecurse
filter
value_serializer
tnnD arecurse
filter
tnuattr\_next_gen.py
u<module attr._next_gen>
T ainst
recurse
filter
value_serializer
T ainst
recurse
filter
T amaybe_cls
these
repr
unsafe_hash
hash
init
slots
frozen
weakref_slot
str
auto_attribs
kw_only
cache_hash
auto_exc
eq
order
auto_detect
getstate_setstate
on_setattr
field_transformer
match_args
do_it
wrap
T acls
auto_attribs
these
repr
hash
unsafe_hash
init
slots
frozen
weakref_slot
str
kw_only
cache_hash
auto_exc
eq
order
auto_detect
getstate_setstate
on_setattr
field_transformer
match_args
T aauto_detect
auto_exc
cache_hash
eq
field_transformer
frozen
getstate_setstate
hash
init
kw_only
match_args
on_setattr
order
repr
slots
str
these
unsafe_hash
weakref_slot
T acls
frozen
on_setattr
had_on_setattr
base_cls
msg
auto_attribs
do_it
T aauto_attribs
do_it
frozen
on_setattr
a__spec__
.attr._version_info
5
split
T w.aappend
T afinal
l l T ayear
minor
micro
releaselevel

Parse *s* and return a _VersionInfo.
astuple
other

Ensure *other* is a tuple of a valid length.
Returns a possibly transformed *other* and ourselves as a tuple of
the same length as *other*.
a_ensure_tuple
a__doc__
a__file__
origin
has_location
a__cached__
total_ordering
a_funcs
T aastuple
a_make
T aattrib
attrs
attrib
attrs
T FptpT aeq
order
slots
frozen
