// ============================================================================
// V8 TITAN C-DECOMPILER OUTPUT
// Generated C++ module file for: discovered_.numpy.ma.extras_at_13723505
// ============================================================================
#include "nuitka/prelude.h"
#include "nuitka/unfreezing.h"
#include "nuitka/builtins.h"

static PyObject *impl_MAxisConcatenator__makemat( PyObject *par_self ) {
    PyThreadState *tstate = PyThreadState_GET();
    PyObject *exception_type = NULL;
    PyObject *exception_value = NULL;
    PyTracebackObject *exception_tb = NULL;
    NUITKA_MAY_BE_UNUSED int exception_lineno = 0;

    // Empty block
}

static PyObject *impl_MAxisConcatenator____getitem__( PyObject *par_self ) {
    PyThreadState *tstate = PyThreadState_GET();
    PyObject *exception_type = NULL;
    PyObject *exception_value = NULL;
    PyTracebackObject *exception_tb = NULL;
    NUITKA_MAY_BE_UNUSED int exception_lineno = 0;

    // --- FRAME VARIABLE ALLOCATION ---
    PyObject *var_None = NULL;
    PyObject *var_False = NULL;
    PyObject *var_None = NULL;
    PyObject *var_False = NULL;
    PyObject *var_left = NULL;
    PyObject *var_right = NULL;
    PyObject *var_None = NULL;
    PyObject *var_anpfunc = NULL;
    PyObject *var_kwargs = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_self = NULL;
    PyObject *var_key = NULL;
    PyObject *var___class__ = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_rowvar = NULL;
    PyObject *var_allow_masked = NULL;
    PyObject *var_xmask = NULL;
    PyObject *var_axis = NULL;
    PyObject *var_tup = NULL;
    PyObject *var_xnm_dtype = NULL;
    PyObject *var_xnotmask = NULL;
    PyObject *var_mask = NULL;
    PyObject *var_idx = NULL;
    PyObject *var_None = NULL;
    PyObject *var_npfunc = NULL;
    PyObject *var_arys = NULL;
    PyObject *var_kwargs = NULL;
    PyObject *var_out = NULL;
    PyObject *var__fromnxfunction = NULL;
    PyObject *var_decorator = NULL;
    PyObject *var_npfunc = NULL;
    PyObject *var_arys = NULL;
    PyObject *var_args = NULL;
    PyObject *var_kwargs = NULL;
    PyObject *var_npfunc = NULL;
    PyObject *var_None = NULL;
    PyObject *var_aargs = NULL;
    PyObject *var_kwargs = NULL;
    PyObject *var_None = NULL;
    PyObject *var_aaxis = NULL;
    PyObject *var_out = NULL;
    PyObject *var_overwrite_input = NULL;
    PyObject *var_fill_value = NULL;
    PyObject *var_asorted = NULL;
    PyObject *var_indexer = NULL;
    PyObject *var_idx = NULL;
    PyObject *var_odd = NULL;
    PyObject *var_mid = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_counts = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_func1d = NULL;
    PyObject *var_axis = NULL;
    PyObject *var_arr = NULL;
    PyObject *var_args = NULL;
    PyObject *var_kwargs = NULL;
    PyObject *var_nd = NULL;
    PyObject *var_ind = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_True = NULL;
    PyObject *var_None = NULL;
    PyObject *var_outshape = NULL;
    PyObject *var_res = NULL;
    PyObject *var_asscalar = NULL;
    PyObject *var_dtypes = NULL;
    PyObject *var_outarr = NULL;
    PyObject *var_Ntot = NULL;
    PyObject *var_func = NULL;
    PyObject *var_None = NULL;
    PyObject *var_aaxes = NULL;
    PyObject *var_val = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_axis = NULL;
    PyObject *var_args = NULL;
    PyObject *var_None = NULL;
    PyObject *var_aaxis = NULL;
    PyObject *var_weights = NULL;
    PyObject *var_returned = NULL;
    PyObject *var_keepdims = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_keepdims_kw = NULL;
    PyObject *var_avg = NULL;
    PyObject *var_scl = NULL;
    PyObject *var_wgt = NULL;
    PyObject *var_None = NULL;
    PyObject *var_amask = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_rowvar = NULL;
    PyObject *var_allow_masked = NULL;
    PyObject *var_arr = NULL;
    PyObject *var_axis = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_rowvar = NULL;
    PyObject *var_bias = NULL;
    PyObject *var_allow_masked = NULL;
    PyObject *var_ddof = NULL;
    PyObject *var_xnotmask = NULL;
    PyObject *var_fact = NULL;
    PyObject *var_mask = NULL;
    PyObject *var_npfunc = NULL;
    PyObject *var_wrapper = NULL;
    PyObject *var_arr = NULL;
    PyObject *var_to_end = NULL;
    PyObject *var_to_begin = NULL;
    PyObject *var_ed = NULL;
    PyObject *var_arrays = NULL;
    PyObject *var_None = NULL;
    PyObject *var_wmwiaresult = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_wmaunmasked = NULL;
    PyObject *var_ar1 = NULL;
    PyObject *var_ar2 = NULL;
    PyObject *var_assume_unique = NULL;
    PyObject *var_invert = NULL;
    PyObject *var_rev_idx = NULL;
    PyObject *var_ar = NULL;
    PyObject *var_order = NULL;
    PyObject *var_sar = NULL;
    PyObject *var_bool_ar = NULL;
    PyObject *var_flag = NULL;
    PyObject *var_indx = NULL;
    PyObject *var_ar1 = NULL;
    PyObject *var_ar2 = NULL;
    PyObject *var_assume_unique = NULL;
    PyObject *var_aux = NULL;
    PyObject *var_element = NULL;
    PyObject *var_test_elements = NULL;
    PyObject *var_assume_unique = NULL;
    PyObject *var_invert = NULL;
    PyObject *var_cls = NULL;
    PyObject *var_arr = NULL;
    PyObject *var_data = NULL;
    PyObject *var___class__ = NULL;
    PyObject *var_None = NULL;
    PyObject *var_aaxis = NULL;
    PyObject *var_None = NULL;
    PyObject *var_aaxis = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_shape = NULL;
    PyObject *var_dtype = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_acompressed = NULL;
    PyObject *var_it = NULL;
    PyObject *var_mask = NULL;
    PyObject *var_None = NULL;
    PyObject *var_aaxis = NULL;
    PyObject *var_nd = NULL;
    PyObject *var_result = NULL;
    PyObject *var_other = NULL;
    PyObject *var_idx = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_deg = NULL;
    PyObject *var_rcond = NULL;
    PyObject *var_full = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_cov = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_rep = NULL;
    PyObject *var_asorted = NULL;
    PyObject *var_asorted = NULL;
    PyObject *var_axis = NULL;
    PyObject *var_ar1 = NULL;
    PyObject *var_ar2 = NULL;
    PyObject *var_assume_unique = NULL;
    PyObject *var_ar1 = NULL;
    PyObject *var_ar2 = NULL;
    PyObject *var_assume_unique = NULL;
    PyObject *var_aux = NULL;
    PyObject *var_auxf = NULL;
    PyObject *var_flag = NULL;
    PyObject *var_flag2 = NULL;
    PyObject *var_ar1 = NULL;
    PyObject *var_ar2 = NULL;
    PyObject *var_ar1 = NULL;
    PyObject *var_return_index = NULL;
    PyObject *var_return_inverse = NULL;
    PyObject *var_output = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_None = NULL;
    PyObject *var_args = NULL;
    PyObject *var_kwargs = NULL;
    PyObject *var__fromnxfunction = NULL;
    PyObject *var_npfunc = NULL;
    PyObject *var__fromnxfunction = NULL;
    PyObject *var_npfunc = NULL;

    // --- HEURISTIC MACRO EXECUTION TRACE ---
    PyObject *str_const_0 = MAKE_STRING('__static_attributes__');
    PyObject *str_const_1 = MAKE_STRING('__orig_bases__');
    PyObject *str_const_2 = MAKE_STRING('mr_class');
    PyObject *str_const_3 = MAKE_STRING('Translate slice objects to concatenation along the first axis.\n\n    This is the masked array version');
    // Discovered Timeout Logic
    time_sleep((double)1768 / 1000.0);
    PyObject *str_const_5 = MAKE_STRING('mr_class.__init__');
    PyObject *str_const_6 = MAKE_STRING('mr_');
    PyObject *tuple_7 = MAKE_TUPLE("('True',)");
    PyObject *str_const_8 = MAKE_STRING('notmasked_edges');
    PyObject *str_const_9 = MAKE_STRING('notmasked_contiguous');
    PyObject *str_const_10 = MAKE_STRING('clump_unmasked');
    PyObject *str_const_11 = MAKE_STRING('clump_masked');
    PyObject *str_const_12 = MAKE_STRING('numpy\\ma\\extras.py');
    PyObject *str_const_13 = MAKE_STRING('T\x03a.0');
    PyObject *str_const_14 = MAKE_STRING('T\x04a.0');
    PyObject *str_const_15 = MAKE_STRING('axis');
    PyObject *str_const_16 = MAKE_STRING('axis');
    PyObject *str_const_17 = MAKE_STRING('<module numpy.ma.extras>');
    PyObject *tuple_18 = MAKE_TUPLE("('__class__',)");
    PyObject *tuple_19 = MAKE_TUPLE("('self',)");
    PyObject *str_const_20 = MAKE_STRING('ymask');
    PyObject *str_const_21 = MAKE_STRING('common_mask');
    // Discovered Timeout Logic
    time_sleep((double)104 / 1000.0);
    PyObject *str_const_23 = MAKE_STRING('low_high');
    PyObject *str_const_24 = MAKE_STRING('replace_masked');
    PyObject *str_const_25 = MAKE_STRING('holdshape');
    PyObject *str_const_26 = MAKE_STRING('max_dtypes');
    PyObject *str_const_27 = MAKE_STRING('result');
    PyObject *str_const_28 = MAKE_STRING('res');
    PyObject *str_const_29 = MAKE_STRING('result_dtype');
    PyObject *tuple_30 = MAKE_TUPLE("('None',)");
    PyObject *str_const_31 = MAKE_STRING('T\x06wxaaxis');
    PyObject *str_const_32 = MAKE_STRING('data');
    PyObject *str_const_33 = MAKE_STRING('axes');
    PyObject *str_const_34 = MAKE_STRING('axis');
    PyObject *str_const_35 = MAKE_STRING('corr');
    PyObject *str_const_36 = MAKE_STRING('std');
    PyObject *str_const_37 = MAKE_STRING('data');
    PyObject *str_const_38 = MAKE_STRING('result');
    PyObject *tuple_39 = MAKE_TUPLE("('_fromnxfunction',)");
    PyObject *tuple_40 = MAKE_TUPLE("('seq',)");
    PyObject *str_const_41 = MAKE_STRING('maskedval');
    PyObject *str_const_42 = MAKE_STRING('T\x02aarr');
    PyObject *str_const_43 = MAKE_STRING('T\x06waaaxis');
    PyObject *str_const_44 = MAKE_STRING('out');
    PyObject *str_const_45 = MAKE_STRING('overwrite_input');
    PyObject *str_const_46 = MAKE_STRING('keepdims');
    // Discovered Timeout Logic
    time_sleep((double)84 / 1000.0);
    PyObject *str_const_48 = MAKE_STRING('aaxis');
    PyObject *str_const_49 = MAKE_STRING('idx');
    PyObject *str_const_50 = MAKE_STRING('not_m');
    PyObject *str_const_51 = MAKE_STRING('axis');

    // Return block
    return Py_None;

exception_handler:
    // Nuitka Exception Routing
    RESTORE_ERROR_OCCURRED(tstate, exception_type, exception_value, exception_tb);
    return NULL;
}
