[package]
name = "ebpf-monitor"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aya = { git = "https://github.com/aya-rs/aya", rev = "8015e100796c550804ccf8fea691c63ec1ac36b8", features = ["async_tokio"] }
aya-log = { git = "https://github.com/aya-rs/aya", rev = "8015e100796c550804ccf8fea691c63ec1ac36b8" }
ebpf-monitor-common = { path = "../ebpf-monitor-common", features = ["user"] }
anyhow = "1"
env_logger = "0.10"
libc = "0.2"
log = "0.4"
tokio = { version = "1.38", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }
bytes = "1.11"

[[bin]]
name = "ebpf-monitor"
path = "src/main.rs"
