/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const web_add_unwhitelisted_subdomain: (a: number, b: number) => number;
export const web_alloc: (a: number) => number;
export const web_apk_loaded: () => number;
export const web_free: (a: number, b: number) => void;
export const web_free_str: (a: number) => void;
export const web_inspect_url: (a: number, b: number, c: number) => number;
export const web_inspect_url_content: (a: number, b: number, c: number, d: number, e: number) => number;
export const web_is_unwhitelisted_subdomain: (a: number, b: number) => number;
export const web_load_benign_whitelist: (a: number, b: number) => number;
export const web_load_model: (a: number, b: number, c: number) => number;
export const web_load_url_rules: (a: number, b: number) => number;
export const web_load_url_whitelist: (a: number, b: number) => number;
export const web_load_yara: (a: number, b: number) => number;
export const web_load_yara_rules: (a: number, b: number) => number;
export const web_load_yara_src: (a: number, b: number) => number;
export const web_output_len: () => number;
export const web_scan_bytes: (a: number, b: number, c: number, d: number) => number;
export const web_scan_bytes_ex: (a: number, b: number, c: number, d: number, e: number, f: bigint, g: bigint, h: bigint) => number;
export const web_scan_url: (a: number, b: number) => number;
export const web_self_test: () => number;
export const web_set_registry_rules: (a: number, b: number) => number;
export const web_set_string_rules: (a: number, b: number) => number;
export const wasm_bindgen_25783ceea4f8f12a___convert__closures_____invoke___wasm_bindgen_25783ceea4f8f12a___JsValue__wasm_bindgen_25783ceea4f8f12a___JsValue__wasm_bindgen_25783ceea4f8f12a___JsValue__wasm_bindgen_25783ceea4f8f12a___JsValue__wasm_bindgen_25783ceea4f8f12a___JsValue__true_: (a: number, b: number, c: any, d: any, e: any, f: any) => any;
export const __wbindgen_malloc_command_export: (a: number, b: number) => number;
export const __wbindgen_realloc_command_export: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store_command_export: (a: number) => void;
export const __externref_table_alloc_command_export: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure_command_export: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
