"""
nuitka_source_reconstructor.py

Advanced Nuitka/Cython source code reconstructor.
Analyzes the constants blob to reconstruct Python source code as fully as possible.

Strategy:
1. Parse all constants in order - Nuitka stores them in code-generation order
2. Identify module-level constants (images, server lists, VK codes)
3. Detect class definitions and their methods via METHOD_REF patterns
4. Extract function signatures from packed null-separated argument names
5. Reconstruct variable assignments, dict/list literals, and control flow hints
6. Generate full Python source with proper structure
"""
import nuitka_deobfuscate
from pathlib import Path
from collections import OrderedDict
import re
import struct

def decode_bytes_safe(val):
    """Decode bytes to string safely."""
    if isinstance(val, str):
        return val
    try:
        return val.decode('utf-8')
    except:
        try:
            return val.decode('latin-1')
        except:
            return repr(val)

def parse_packed_names(data):
    """Parse Nuitka's null-separated packed constant format.
    Format: tag+name\0tag+name\0...
    Tags: a=arg, w=keyword, u=unicode, p=positional, T=count, D=dict, O=optional
    """
    if isinstance(data, str):
        raw = data.encode('utf-8', errors='replace')
    else:
        raw = bytes(data)
    
    segments = []
    current = b''
    for byte in raw:
        if byte == 0:
            if current:
                segments.append(current)
            current = b''
        else:
            current += bytes([byte])
    if current:
        segments.append(current)
    
    result = []
    for seg in segments:
        text = seg.decode('utf-8', errors='replace')
        if len(text) < 2:
            result.append(('raw', text))
            continue
        tag = text[0]
        name = text[1:]
        if tag == 'a':
            result.append(('arg', name))
        elif tag == 'w':
            result.append(('kw', name))
        elif tag == 'u':
            result.append(('str', name))
        elif tag == 'p':
            result.append(('pos', name))
        elif tag == 'T':
            result.append(('count', name))
        elif tag == 'D':
            result.append(('dict_size', name))
        elif tag == 'O':
            result.append(('type', name))
        else:
            result.append(('raw', text))
    return result

def is_b64_image(val):
    """Check if a value is a base64-encoded image."""
    s = decode_bytes_safe(val) if isinstance(val, (bytes, bytearray)) else str(val)
    return 'iVBORw0KGgo' in s or 'JFIF' in s

def reconstruct_module(section_name, items):
    """Reconstruct a full Python module from its constants."""
    
    lines = []
    lines.append(f'"""')
    lines.append(f'Reconstructed source for module: {section_name}')
    lines.append(f'Total constants: {len(items)}')
    lines.append(f'Generated by nuitka_source_reconstructor.py')
    lines.append(f'"""')
    lines.append('')
    
    # Phase 1: Identify all constants and their roles
    module_vars = OrderedDict()  # name -> value
    classes = OrderedDict()      # class_name -> {methods: [{name, args}], attrs: []}
    functions = []               # [{name, args, locals}]
    imports_hints = set()        # Guessed imports
    images = OrderedDict()       # name -> "(base64 data)"
    vk_map = OrderedDict()       # VK constant name -> value
    server_list = []
    server_config = {}
    
    # State machine for parsing
    current_class = None
    last_method_name = None
    last_bytes_name = None
    i = 0
    
    while i < len(items):
        item = items[i]
        
        # --- Base64 images (paired: name, data) ---
        if isinstance(item, (bytes, bytearray)):
            name = decode_bytes_safe(item)
            if name.endswith('_B64') and i + 1 < len(items):
                next_item = items[i + 1]
                if is_b64_image(next_item):
                    images[name] = f"(base64 image data, {len(decode_bytes_safe(next_item))} chars)"
                    i += 2
                    continue
            
            # VK_ constants (paired: name, value)
            if name.startswith('VK_'):
                # Look for associated numeric value
                if i + 1 < len(items) and isinstance(items[i + 1], (int, float)):
                    vk_map[name] = items[i + 1]
                elif i > 0 and isinstance(items[i - 1], (int, float)):
                    vk_map[name] = items[i - 1]
                else:
                    vk_map[name] = '...'
                i += 1
                continue
        
        # --- Server names ---
        if isinstance(item, (bytes, bytearray)):
            name = decode_bytes_safe(item)
            if name in ('AKINGAMING', 'ArdreamPRO', 'DeathKO', 'DeathMYKO', 
                        'DrakinGame', 'ESKO', 'FELIX', 'GmrGame', 'HomekoWorld',
                        'KKingdom', 'KNIGHT59', 'DEATHMATCH', 'KO4FUN', 'LOGOSWAR',
                        'MonsterKO', 'OCKO', 'TURKKO', 'YourKO', 'ASS78'):
                server_list.append(name)
                i += 1
                continue
        
        # --- List/Dict literals ---
        if isinstance(item, list):
            # Server list or config
            decoded = [decode_bytes_safe(x) if isinstance(x, (bytes, bytearray)) else repr(x) for x in item[:50]]
            if last_bytes_name:
                module_vars[last_bytes_name] = decoded
            else:
                module_vars[f'_list_{i}'] = decoded
            i += 1
            continue
        
        if isinstance(item, dict):
            decoded = {}
            for k, v in list(item.items())[:30]:
                dk = decode_bytes_safe(k) if isinstance(k, (bytes, bytearray)) else repr(k)
                dv = repr(v)[:100] if not isinstance(v, (bytes, bytearray)) else decode_bytes_safe(v)[:100]
                decoded[dk] = dv
            if last_bytes_name:
                module_vars[last_bytes_name] = decoded
            else:
                module_vars[f'_dict_{i}'] = decoded
            i += 1
            continue
        
        # --- Class/method detection ---
        if isinstance(item, str):
            if '.' in item and not item.startswith('.'):
                parts = item.split('.', 1)
                cls_name = parts[0]
                method_name = parts[1]
                
                if cls_name not in classes:
                    classes[cls_name] = {'methods': [], 'attrs': [], 'slots': None}
                classes[cls_name]['methods'].append({'name': method_name, 'args': ['self'], 'index': i})
                current_class = cls_name
                last_method_name = method_name
                i += 1
                continue
        
        # --- Tuples (often __slots__ or arg names) ---
        if isinstance(item, tuple):
            decoded_tuple = tuple(decode_bytes_safe(x) if isinstance(x, (bytes, bytearray)) else x for x in item)
            
            # Check if it's __slots__
            if last_bytes_name == '__slots__' and current_class:
                classes[current_class]['slots'] = decoded_tuple
            # Check if prev item was a class reference
            elif all(isinstance(x, str) for x in decoded_tuple):
                # Could be arg names if right after a method
                if current_class and last_method_name:
                    # Try to match to the last method
                    for m in reversed(classes.get(current_class, {}).get('methods', [])):
                        if m['name'] == last_method_name:
                            m['args'] = list(decoded_tuple)
                            break
            i += 1
            continue
        
        # --- Packed name structures (function signatures) ---
        if isinstance(item, (bytes, bytearray)):
            name = decode_bytes_safe(item)
            if '\x00' in name and len(name) > 5:
                parsed = parse_packed_names(item)
                args = [n for t, n in parsed if t == 'arg']
                method_refs = [n for t, n in parsed if t == 'str' and '.' in n]
                
                if args:
                    # Associate with most recent method
                    if method_refs:
                        for ref in method_refs:
                            parts = ref.split('.', 1)
                            if len(parts) == 2:
                                cls_name, method_name = parts
                                if cls_name not in classes:
                                    classes[cls_name] = {'methods': [], 'attrs': [], 'slots': None}
                    
                    if current_class and classes.get(current_class, {}).get('methods'):
                        # Apply args to most recent method without full args
                        for m in reversed(classes[current_class]['methods']):
                            if m['args'] == ['self']:
                                m['args'] = ['self'] + args
                                break
                i += 1
                continue
        
        # --- Bytes that are attribute/function names ---
        if isinstance(item, (bytes, bytearray)):
            name = decode_bytes_safe(item)
            if name.startswith('_') and current_class:
                classes[current_class]['attrs'].append(name)
            last_bytes_name = name
        elif isinstance(item, str):
            last_bytes_name = item
        else:
            last_bytes_name = None
        
        i += 1
    
    # Phase 2: Generate imports
    lines.append('# === IMPORTS (inferred from dependencies) ===')
    if images:
        lines.append('import base64')
        lines.append('from io import BytesIO')
    
    # Detect imports from attribute/method usage
    import_map = {
        'CTk': 'import customtkinter as ctk',
        'CTkButton': 'from customtkinter import CTkButton, CTkEntry, CTkLabel, CTkFrame',
        'CTkTextbox': 'from customtkinter import CTkTextbox, CTkTabview, CTkScrollableFrame',
        'mss': 'import mss',
        'MSS': 'from mss import mss as MSS',
        'keyboard': 'from pynput import keyboard',
        'mouse': 'from pynput import mouse',
        'win32api': 'import win32api',
        'win32con': 'import win32con',
        'ctypes': 'import ctypes',
        'threading': 'import threading',
        'time': 'import time',
        'json': 'import json',
        'os': 'import os',
        'sys': 'import sys',
        'tkinter': 'import tkinter as tk',
        'PIL': 'from PIL import Image, ImageTk',
        'nacl': 'import nacl',
        'requests': 'import requests',
        'urllib': 'import urllib.request',
        'subprocess': 'import subprocess',
    }
    
    seen_imports = set()
    all_text = ' '.join(str(x) for x in items[:200])
    for key, imp in import_map.items():
        if key in str(classes) or key in all_text:
            if imp not in seen_imports:
                lines.append(imp)
                seen_imports.add(imp)
    
    lines.append('')
    
    # Phase 3: Module-level constants
    lines.append('# === MODULE CONSTANTS ===')
    lines.append('')
    
    # Images
    if images:
        lines.append('# --- Base64 Encoded Images ---')
        for name, desc in images.items():
            lines.append(f'{name} = "{desc}"')
        lines.append('')
    
    # Server list
    if server_list:
        lines.append('# --- Supported Servers ---')
        lines.append(f'SUPPORTED_SERVERS = {server_list}')
        lines.append('')
    
    # Server config
    for name, val in module_vars.items():
        if isinstance(val, dict):
            lines.append(f'# --- {name} ---')
            lines.append(f'{name} = {{')
            for k, v in val.items():
                lines.append(f'    {repr(k)}: {repr(v)},')
            lines.append('}')
            lines.append('')
        elif isinstance(val, list):
            lines.append(f'{name} = {val}')
            lines.append('')
    
    # VK Map
    if vk_map:
        lines.append('# --- Virtual Key Constants ---')
        for name, val in vk_map.items():
            lines.append(f'{name} = {val}')
        lines.append('')
    
    # Phase 4: Classes
    for cls_name, cls_data in classes.items():
        methods = cls_data['methods']
        attrs = cls_data['attrs']
        slots = cls_data['slots']
        
        if not methods and not attrs:
            continue
        
        lines.append(f'')
        lines.append(f'class {cls_name}:')
        
        if slots:
            lines.append(f'    __slots__ = {slots}')
            lines.append(f'')
        
        # Instance attributes (from bytes items starting with _)
        unique_attrs = sorted(set(attrs))
        if unique_attrs:
            lines.append(f'    # Instance attributes:')
            for attr in unique_attrs[:50]:
                lines.append(f'    #   self.{attr}')
            lines.append(f'')
        
        # Methods
        seen_methods = set()
        for m in methods:
            method_name = m['name']
            if method_name in seen_methods:
                continue
            seen_methods.add(method_name)
            
            args = m.get('args', ['self'])
            arg_str = ', '.join(args)
            
            lines.append(f'    def {method_name}({arg_str}):')
            lines.append(f'        ...')
            lines.append(f'')
    
    # Phase 5: Standalone functions
    for func in functions:
        name = func.get('name', f'_func_{func.get("index", "?")}')
        args = func.get('args', [])
        arg_str = ', '.join(args) if args else ''
        lines.append(f'def {name}({arg_str}):')
        lines.append(f'    ...')
        lines.append(f'')
    
    return '\n'.join(lines)


def main():
    blob_path = Path('rcdata_10_3.bin')
    data = blob_path.read_bytes()
    sections = nuitka_deobfuscate.decode_blob(data)
    
    out_dir = Path('restore_deep_ultra') / 'reconstructed_source'
    out_dir.mkdir(parents=True, exist_ok=True)
    
    # Process ALL metadata sections
    for section_name, items in sections.items():
        if not items or len(items) < 10:
            continue
        
        # Skip pure bytecode sections (stdlib)
        has_non_bytecode = False
        for item in items[:100]:
            if isinstance(item, str) and '.' in item:
                has_non_bytecode = True
                break
            if isinstance(item, dict):
                has_non_bytecode = True
                break
        
        if not has_non_bytecode:
            continue
        
        print(f"[*] Reconstructing: {section_name} ({len(items)} items)")
        
        try:
            source = reconstruct_module(section_name, items)
            
            # Clean section name for filename
            safe_name = re.sub(r'[<>:"/\\|?*]', '_', section_name)
            safe_name = safe_name[:80]
            
            (out_dir / f'{safe_name}.py').write_text(source, encoding='utf-8')
        except Exception as e:
            print(f"  [!] Error: {e}")
    
    print(f"\n[*] Reconstructed sources saved to: {out_dir}")

if __name__ == '__main__':
    main()
