#!/usr/bin/env python3
"""
extract_sbox.py  --  Extract the 256-byte S-box (byte_38B57EC20) and
                     generate a C header that can be compiled into blob_loader.

Usage:
    python3 extract_sbox.py  program.exe  [--rva 0x57EC20]

The RVA (Relative Virtual Address) of byte_38B57EC20 can be read from:
  - IDA Pro: the address shown in the disassembly (0x38B57EC20 minus imagebase)
  - Ghidra: the address column
  - x64dbg: right-click → "Follow in Dump"

Default imagebase for this binary appears to be 0x38B000000 (PE optional header).
"""

import struct
import sys
import os

def rva_to_file_offset(pe_data: bytes, rva: int) -> int:
    """Convert a Relative Virtual Address to a file offset using PE section headers."""
    # Parse PE header offset
    pe_offset = struct.unpack_from('<I', pe_data, 0x3C)[0]
    sig = pe_data[pe_offset:pe_offset+4]
    if sig != b'PE\x00\x00':
        raise ValueError(f"Not a valid PE file (got {sig!r})")

    # COFF header
    machine            = struct.unpack_from('<H', pe_data, pe_offset + 4)[0]
    num_sections       = struct.unpack_from('<H', pe_data, pe_offset + 6)[0]
    optional_hdr_size  = struct.unpack_from('<H', pe_data, pe_offset + 20)[0]

    # Optional header starts at pe_offset + 24
    opt_offset = pe_offset + 24
    magic = struct.unpack_from('<H', pe_data, opt_offset)[0]
    if magic == 0x20B:   # PE32+ (64-bit)
        imagebase = struct.unpack_from('<Q', pe_data, opt_offset + 24)[0]
    elif magic == 0x10B: # PE32 (32-bit)
        imagebase = struct.unpack_from('<I', pe_data, opt_offset + 28)[0]
    else:
        raise ValueError(f"Unknown PE magic: 0x{magic:04X}")

    print(f"[pe] ImageBase=0x{imagebase:016X}  sections={num_sections}")

    # Section table starts after optional header
    section_offset = pe_offset + 24 + optional_hdr_size
    for i in range(num_sections):
        off = section_offset + i * 40
        name           = pe_data[off:off+8].rstrip(b'\x00').decode('ascii','replace')
        virtual_size   = struct.unpack_from('<I', pe_data, off + 8)[0]
        virtual_addr   = struct.unpack_from('<I', pe_data, off + 12)[0]
        raw_size       = struct.unpack_from('<I', pe_data, off + 16)[0]
        raw_offset     = struct.unpack_from('<I', pe_data, off + 20)[0]

        if virtual_addr <= rva < virtual_addr + max(virtual_size, raw_size):
            delta = rva - virtual_addr
            file_off = raw_offset + delta
            print(f"[pe] RVA 0x{rva:X} -> section '{name}' -> file offset 0x{file_off:X}")
            return file_off

    raise ValueError(f"RVA 0x{rva:X} not found in any section")


def extract_sbox(exe_path: str, absolute_addr: int = 0x38B57EC20,
                 imagebase: int = None) -> bytes:
    """
    Extract 256 bytes from the binary at the given absolute virtual address.

    absolute_addr: the address as shown in IDA (e.g. 0x38B57EC20)
    imagebase:     override auto-detected PE imagebase if needed
    """
    with open(exe_path, 'rb') as f:
        data = f.read()

    # Auto-detect imagebase from PE header
    pe_off = struct.unpack_from('<I', data, 0x3C)[0]
    opt_off = pe_off + 24
    magic = struct.unpack_from('<H', data, opt_off)[0]
    if imagebase is None:
        if magic == 0x20B:
            imagebase = struct.unpack_from('<Q', data, opt_off + 24)[0]
        else:
            imagebase = struct.unpack_from('<I', data, opt_off + 28)[0]

    rva = absolute_addr - imagebase
    print(f"[sbox] addr=0x{absolute_addr:X}  imagebase=0x{imagebase:X}  rva=0x{rva:X}")

    file_off = rva_to_file_offset(data, rva)
    sbox = data[file_off : file_off + 256]
    if len(sbox) != 256:
        raise ValueError(f"Could not read 256 bytes at file offset 0x{file_off:X}")
    return sbox


def write_sbox_header(sbox: bytes, out_path: str = "sbox.h"):
    """Write the S-box as a C header for compilation into blob_loader."""
    lines = ["/* Auto-generated by extract_sbox.py */",
             "#pragma once",
             "#include <stdint.h>",
             "",
             "/* 256-byte S-box extracted from Nuitka compiled binary.",
             "   Pass to blob_set_sbox() before calling blob_verify(). */",
             "static const uint8_t NUITKA_SBOX[256] = {"]
    for row in range(16):
        vals = ", ".join(f"0x{sbox[row*16 + col]:02X}" for col in range(16))
        lines.append(f"    {vals},")
    lines[-1] = lines[-1].rstrip(',')  # remove trailing comma on last row
    lines += ["};", ""]
    with open(out_path, 'w') as f:
        f.write('\n'.join(lines))
    print(f"[sbox] Written C header to: {out_path}")
    print(f"[sbox] Include in main.c and call: blob_set_sbox(NUITKA_SBOX);")


def write_sbox_bin(sbox: bytes, out_path: str = "sbox.bin"):
    with open(out_path, 'wb') as f:
        f.write(sbox)
    print(f"[sbox] Raw S-box written to: {out_path}")


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Extract Nuitka S-box from compiled binary')
    parser.add_argument('exe', help='Path to the Nuitka compiled .exe')
    parser.add_argument('--addr', default='0x38B57EC20',
                        help='Absolute VA of byte_38B57EC20 (from IDA, default: 0x38B57EC20)')
    parser.add_argument('--imagebase', default=None,
                        help='Override imagebase (e.g. 0x38B000000)')
    parser.add_argument('--out-h',   default='sbox.h',   help='Output C header path')
    parser.add_argument('--out-bin', default='sbox.bin', help='Output raw binary path')
    args = parser.parse_args()

    addr = int(args.addr, 0)
    ib   = int(args.imagebase, 0) if args.imagebase else None

    print(f"[sbox] Extracting from: {args.exe}")
    sbox = extract_sbox(args.exe, addr, ib)

    print(f"[sbox] First 16 bytes: {sbox[:16].hex(' ')}")
    write_sbox_header(sbox, args.out_h)
    write_sbox_bin(sbox, args.out_bin)

    # Sanity check: a valid S-box should be a permutation (all 256 values present)
    if sorted(sbox) == list(range(256)):
        print("[sbox] ✓ Valid permutation (all 256 values present)")
    else:
        print("[sbox] ⚠ Not a permutation — verify the address is correct")
        dupes = [b for b in range(256) if sbox.count(b) > 1]
        print(f"[sbox]   Duplicates: {dupes[:8]}...")
