name: dotnet-megadumper-ci

on:
  push:
    branches: ["**"]
    paths:
      - 'MegaDumper/**'
      - '.github/workflows/dotnet-megadumper.yml'
  pull_request:
    branches: ["**"]
    paths:
      - 'MegaDumper/**'
      - '.github/workflows/dotnet-megadumper.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Enable long paths
      run: git config --global core.longpaths true

    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore MegaDumper/MegaDumper.sln

    - name: Publish MegaDumper
      run: dotnet publish MegaDumper/MegaDumper/MegaDumper.csproj -c Release -r win-x64 --self-contained false

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: dumper-release
        path: MegaDumper/MegaDumper/bin/Release/net8.0-windows/publish/
