name: dotnet-megadumper-ci

on:
  push:
    branches: ["**"]
    paths:
      - 'MegaDumper/**'
      - '.github/workflows/dotnet-megadumper.yml'
  pull_request:
    branches: ["**"]
    paths:
      - 'MegaDumper/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Enable long paths
      run: git config --global core.longpaths true

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore MegaDumper/MegaDumper.sln

    - name: Build MegaDumper
      run: dotnet build MegaDumper/MegaDumper.sln --configuration Release --no-restore

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: megadumper-release
        path: MegaDumper/MegaDumper/bin/Release/
