name: Owlyshield Full Features Windows

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  check-windows:
    name: Cargo Check (Full Features) - Windows
    runs-on: windows-latest
    defaults:
      run:
        working-directory: Owlyshield/owlyshield_predict

    steps:
    - name: Enable Git long paths
      run: git config --global core.longpaths true
      working-directory: ${{ github.workspace }}
    - uses: actions/checkout@v6
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Assembly Tools (yasm)
      run: choco install nasm
      
    - name: Cache Cargo
      uses: Swatinem/rust-cache@v2
      
    - name: Cargo check (All Features)
      run: cargo check --features novelty,malware,hydradragon,behavior_engine,firewall,sanctum --verbose
