name: Publish Sanctum Injected DLL

on:
  push:
    branches: ["**"]
    paths:
      - 'Sanctum/injected_dll/**'
      - 'Sanctum/shared_std/**'
      - 'Sanctum/shared_no_std/**'
      - 'Sanctum/Cargo.toml'
      - 'Sanctum/Cargo.lock'
      - '.github/workflows/publish-sanctum-injected-dll.yml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-stage:
    runs-on: windows-2022
    steps:
      - name: Enable Git long paths
        run: git config --global core.longpaths true
      - uses: actions/checkout@v6
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Update Cargo.lock
        working-directory: Sanctum
        run: cargo update
      - name: Build injected_dll
        working-directory: Sanctum
        run: cargo build --release -p injected_dll
      - name: Stage
        shell: pwsh
        run: |
          $dist = "hydradragon/Sanctum/System32"
          New-Item -ItemType Directory -Force -Path $dist
          Copy-Item "Sanctum/target/release/sanctum.dll" "$dist/" -Force
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: sanctum-injected-dll
          path: hydradragon/Sanctum/System32/sanctum.dll
          if-no-files-found: error
      - name: Create PR
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(sanctum): update injected dll binary"
          title: "Update Sanctum Injected DLL Binary"
          add-paths: |
            hydradragon/Sanctum/System32/sanctum.dll
            Sanctum/Cargo.lock
          branch: "auto-update-sanctum-injected-dll"
          base: ${{ github.ref_name }}
          delete-branch: true
          labels: binaries, automated-pr, sanctum, injected-dll
