name: Publish TinyAntivirus

on:
  push:
    branches: ["**"]
    paths:
      - 'TinyAntivirus/**'
    paths-ignore:
      - 'hydradragon/**'
      - '.github/**'
      - '.agent/**'
      - 'yarGen/**'
      - '**.md'

jobs:
  build-and-stage:
    runs-on: windows-2022
    steps:
      - name: Enable Git long paths
        run: git config --global core.longpaths true
      - uses: actions/checkout@v6
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v3
      - name: Build
        run: msbuild TinyAntivirus/TinyAntivirus.sln /p:Configuration=Release /p:Platform=x64
      
      - name: Stage
        shell: pwsh
        run: |
          $dist = "hydradragon/TinyAntivirus"
          New-Item -ItemType Directory -Force -Path $dist
          Copy-Item "TinyAntivirus/x64/Release/TinyAvConsole.exe" "$dist/" -Force
          
      - name: Create PR
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(tinyav): update binaries"
          title: "🚀 Update TinyAntivirus Binaries"
          branch: "auto-update-tinyav"
          base: ${{ github.ref_name }}
          delete-branch: true
