name: Publish Owlyshield Minifilter

on:
  push:
    branches: ["**"]
    paths:
      - "Owlyshield/owlyshield_minifilter/**"
      - ".github/workflows/publish-owlyshield-minifilter.yml"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  WDK_URL: https://go.microsoft.com/fwlink/?linkid=2335869

jobs:
  publish:
    runs-on: windows-2022
    steps:
      - name: Enable Git long paths
        run: git config --global core.longpaths true

      - uses: actions/checkout@v6

      - name: Set up MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup WDK
        shell: pwsh
        run: |
          $wdkSetupPath = "$Env:TEMP\wdksetup.exe"
          (New-Object Net.WebClient).DownloadFile("${{ env.WDK_URL }}", $wdkSetupPath)
          Start-Process -FilePath $wdkSetupPath -ArgumentList "/quiet" -NoNewWindow -Wait

      - name: Build Minifilter
        run: msbuild Owlyshield/owlyshield_minifilter/RWatch.sln /p:Configuration=Release /p:Platform=x64

      - name: Stage Minifilter Files
        shell: pwsh
        run: |
          $source = "Owlyshield/owlyshield_minifilter/x64/Release"
          $destination = "hydradragon/Owlyshield/OwlyshieldRansomFilter"
          $files = @(
            "OwlyshieldRansomFilter.sys",
            "OwlyshieldRansomFilter.inf",
            "owlyshieldransomfilter.cat",
            "OwlyshieldRansomFilter.cer"
          )
          New-Item -ItemType Directory -Force -Path $destination | Out-Null

          Get-ChildItem -Path $source -Recurse -File |
            Where-Object { $_.Name -in $files } |
            ForEach-Object { Copy-Item $_.FullName -Destination $destination -Force }

      - name: Check for publishable changes
        id: check_changes
        uses: ./.github/actions/check-publishable-changes
        with:
          paths: |
            hydradragon/Owlyshield/OwlyshieldRansomFilter
      - name: Create PR
        if: steps.check_changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(owlyshield): update minifilter binaries"
          title: "Update Owlyshield minifilter binaries"
          body: "Automated minifilter driver build output update."
          branch: "auto-update-owlyshield-minifilter"
          base: ${{ github.ref_name }}
          delete-branch: true
          labels: binaries, automated-pr, owlyshield
