name: vs2022hydradragonav-ci

on:
  push:
    branches: ["**"]
    paths:
      - 'HydraDragonAV/**'
      - '.github/workflows/vs2022hydradragonav.yml'
  pull_request:
    branches: ["**"]
    paths:
      - 'HydraDragonAV/**'
      - '.github/workflows/vs2022hydradragonav.yml'
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: "HydraDragonAV/HydraDragonAV.sln"
  BUILD_BIN_DIR: "./HydraDragonAV/x64/"

permissions:
  contents: read

jobs:
  win-build:
    runs-on: windows-2022
    strategy:
      matrix:
        BUILD_CONFIGURATION: [Release, Debug]
        PLATFORM: [x64]

    steps:
    - name: Enable long paths
      run: git config --global core.longpaths true

    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3
      
    - name: Build HydraDragonAV
      run: msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} /p:Platform=${{matrix.PLATFORM}} "${{env.SOLUTION_FILE_PATH}}"

    - name: Upload build directory 
      if: matrix.BUILD_CONFIGURATION == 'Release'
      uses: actions/upload-artifact@v7
      with:
        name: hydradragonav_release_binaries_${{matrix.PLATFORM}}
        path: |
          ${{ env.BUILD_BIN_DIR }}${{matrix.BUILD_CONFIGURATION}}/**
          !${{ env.BUILD_BIN_DIR }}${{matrix.BUILD_CONFIGURATION}}/**/*.cer
