name: vs2022zillya-ci

on:
  push:
    branches: ["**"]
    paths:
      - 'ZillyaAVEngineSDK/**'
      - '.github/workflows/vs2022zillya.yml'
  pull_request:
    branches: ["**"]
    paths:
      - 'ZillyaAVEngineSDK/**'
      - '.github/workflows/vs2022zillya.yml'
  workflow_dispatch:

env:
  BUILD_BIN_DIR: "ZillyaAVEngineSDK/out/Win32"

permissions:
  contents: read

jobs:
  win-build:
    runs-on: windows-2022
    strategy:
      matrix:
        BUILD_CONFIGURATION: [Release, Debug]
        PLATFORM: [Win32]

    steps:
    - name: Enable long paths
      run: git config --global core.longpaths true

    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3

    - name: Build Zillya AVEngine SDK
      shell: pwsh
      working-directory: ZillyaAVEngineSDK
      run: powershell -ExecutionPolicy Bypass -File .\build\vs2022\Build-VS2022.ps1 -Configuration ${{ matrix.BUILD_CONFIGURATION }} -Platform ${{ matrix.PLATFORM }}

    - name: Upload release build outputs
      if: matrix.BUILD_CONFIGURATION == 'Release'
      uses: actions/upload-artifact@v7
      with:
        name: zillya_vs2022_release_binaries_${{ matrix.PLATFORM }}
        path: |
          ${{ env.BUILD_BIN_DIR }}/${{ matrix.BUILD_CONFIGURATION }}/*.exe
          ${{ env.BUILD_BIN_DIR }}/${{ matrix.BUILD_CONFIGURATION }}/*.dll
          ${{ env.BUILD_BIN_DIR }}/${{ matrix.BUILD_CONFIGURATION }}/*.lib
          ${{ env.BUILD_BIN_DIR }}/${{ matrix.BUILD_CONFIGURATION }}/*.pdb
        if-no-files-found: error
