name: vs2022reddbg-ci

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:
env:
  # WDK for Windows 11, version 25H2
  WDK_URL: https://go.microsoft.com/fwlink/?linkid=2335869
  
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: Owlyshield/RedDbg/RedDbg/RedDbg.sln

  RELEASE_ZIP_FILE_NAME: reddbg

  BUILD_BIN_DIR: ./Owlyshield/RedDbg/RedDbg/x64/

jobs:
  win-amd64-build:
    runs-on: windows-2022
    strategy:
      matrix:
        BUILD_CONFIGURATION: [Release, Debug]
        PLATFORM: [x64]

    steps:
    - name: Enable long paths
      run: git config --global core.longpaths true

    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Checkout submodules recursively
      run: git submodule update --init --recursive --remote
    
    - name: Setup WDK version 25H2
      run: |
        $wdkSetupPath = "$Env:TEMP\wdksetup.exe"
        (New-Object Net.WebClient).DownloadFile('${{env.WDK_URL}}', $wdkSetupPath)
        Start-Process -FilePath $wdkSetupPath -ArgumentList "/quiet" -NoNewWindow -Wait     

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Fix WDK tools path
      run: |
        $wdk_bin = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x86"
        if (Test-Path $wdk_bin) {
          echo "$wdk_bin" >> $env:GITHUB_PATH
          Write-Host "Added $wdk_bin to PATH"
        } else {
          Write-Host "Warning: WDK bin path not found at $wdk_bin"
        }
      shell: pwsh

    - name: Build RedDbg solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} /p:Platform=${{matrix.PLATFORM}} ${{env.SOLUTION_FILE_PATH}}
    
    - name: Upload build directory 
      uses: actions/upload-artifact@v7
      with:
        name: reddbg_build_files_${{matrix.BUILD_CONFIGURATION}}
        path: ${{ env.BUILD_BIN_DIR }}
