[package]
name = "hydradragon-controller-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.6", features = ["csr"] }
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
serde_json = "1.0"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "HtmlElement",
    "Window",
    "Document", 
    "Event", 
    "SubmitEvent", 
    "HtmlInputElement", 
    "HtmlSelectElement",
    "EventTarget",
    "Location",
    "console"
] }

[package.metadata.leptos]
name = "hydradragon-controller-ui"
site-root = "dist"
site-pkg-dir = "pkg"
style-file = "style.css"
